### ISSUE TITLE
Ta fram use case och wireframes för handläggare

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#266]
**Acceptance criteria**
Prioriterad lista och översikt på valda användningsfall
Uppdaterad översikt i Figma på 3-5 flöden/användningsfall.

**Beskrivning**
Inledningsvis behöver vi välja prioriterade användningsfall. Här finns översikter.
https://app.diagrams.net/#G1MkwMcpw5GvfedMBtM9YH0q4uInWmLpi1

Det finns även översikter i Figma som Gabriella har arbetat med.
[noQ-flödesskiss](https://www.figma.com/file/w9pDi7qsOmiqDuRWo6bL4V/noQ-fl%C3%B6desskiss?type=whiteboard&node-id=0-1&t=Z4EUTMRavbTTIUKd-0)

**Comment by elajth** [comment]
**Acceptance criteria**
Prioriterad lista och översikt på valda användningsfall
Uppdaterad översikt i Figma på 3-5 flöden/användningsfall.

**Beskrivning**
Inledningsvis behöver vi välja prioriterade användningsfall. Här finns översikter.
https://app.diagrams.net/#G1MkwMcpw5GvfedMBtM9YH0q4uInWmLpi1

Det finns även översikter i Figma som Gabriella har arbetat med.
[noQ-flödesskiss](https://www.figma.com/file/w9pDi7qsOmiqDuRWo6bL4V/noQ-fl%C3%B6desskiss?type=whiteboard&node-id=0-1&t=Z4EUTMRavbTTIUKd-0)

**Comment by Overath** [comment]
Kan någon sätta denna till done?

**Comment by Overath** [comment]
Någon redo?

**Comment by overath2** [comment]
Ping @Mrsluggan för review

**Comment by overath2** [comment]
Hur mår denna ticket?

**Comment by FannyBacklin** [comment]
Eric har utmaning i att få tag på Johan, vad jag förstår kommer inte Eric in för att kunna reviewa denna.

**Comment by elajth** [comment]
Jag kollar över den här under nästa vecka men jag tror att vi bara sätter den till Done. Jag ser om vi redan har Wireframes och Use Cases

**Comment by overath2** [comment]
Ping @elajth . Vad händer här?

**Comment by elajth** [comment]
Vi stänger den!
