### ISSUE TITLE
Update "Workflow" on Drive (confluence) for Github Projects

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#269]
As a NoQ member, I want to read about the story workflow, 
So that I can work effectively with Github Projects

Acceptance Criteria
Given that I open the workflow file
When reading the part about workflow
Then I have an updated workflow with github projects

Definition of Done
OK from wingmate
Uploaded to Drive

Subtasks or tasks
#

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel. Ping @elajth
