### ISSUE TITLE
EPIC: Boendet (was härbärget)

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#270]
Vi tror att en tjänst för boenden (härbärgen, akutboenden, stödboenden och framöver även privata boenden som hotell egna hem etc) kommer hjälpa till med administrationen på boendet så tid kan läggas på mer värdeskapande arbete. Till skillnad från idag då mycket sker manuellt och med åldrade eller oflexibla IT-system. Vi vet att detta är sant när boenden säger att de vill använda  vår tjänst.

Deliverables: 
Backend i Python/Django/NinjaAPI för härbärget
Frontend i React för härbärget

**Acceptance criteria:**

- Härbärget kan se och hantera inkommande förfrågningar från brukare
- Härbärget kan se sin rumsöversikt
- Härbärget kan ändra sina kontaktuppgifter 
- Härbärget kan CRUDa rumstyper och tillgängliga rum
- Härbärget kan rapportera på bokningar
- Härbärget kan ta fram fakturaunderlag från systemet

**Stories**

- [x] #271 
- [x] #387
- [x] #388
- [x] #423

**Comment by FannyBacklin** [comment]
Första steg: Team gul bryter ner den här till mindre user storys.

**Comment by Overath** [comment]
Har skapat ett embryo till enkät vi kan skicka ut:
https://docs.google.com/forms/d/e/1FAIpQLSfrTZaEW-xGEiD3AMbfgabNgt7NUKqpgiqh_5dz2z-HQqX9RA/viewform?usp=sharing

**Comment by Overath** [comment]
Här lista över härbärgen: https://docs.google.com/spreadsheets/d/1SnvmuGPEy5PnuaZFDXB7MBAURaDVk3UH1CfQGMOlIqs/edit?usp=sharing

**Comment by overath2** [comment]
Denna uppfyller inte våra krav i Playbook för tickets i Github. Läs mer här: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.cg0m06jyj586
Jag sätter den i korrekt status. När åtgärdat flytta tillbaka denna.
/o

**Comment by overath2** [comment]
@natischmidt Kan du dra denna?

**Comment by natischmidt** [comment]
> @natischmidt Kan du dra denna?


- Härbärget kan ändra sina kontaktuppgifter
- Härbärget kan rapportera på bokningar

är int påbörjat

**Comment by overath2** [comment]
Här viktig input: https://docs.google.com/spreadsheets/d/1XOImqNU_g60BWypP0px81jF-qHJb1BjjVgqkXgfs9k8/edit?usp=sharing

**Comment by overath2** [comment]
Hej alla assignees. Jag skulle vilja ha en assignee/driver/epic owner på alla epics enligt principen "för många kockar". Kan ni flytta över er till fältet Wingmate istället och kan någon räcka upp handen som epic owner?

**Comment by overath2** [comment]
Se även https://docs.google.com/presentation/d/13eRs4bCL9AtUPST6hW5dj_hvTEtqnuhcl1_in5tfZcs/edit?usp=drivesdk

**Comment by overath2** [comment]
Uppdaterad kravspecifikation: https://drive.google.com/file/d/1qi082jRbWu4oZZIaqHL2p6gJBTGxX2Cs/view?usp=drive_link
Ping @natischmidt

**Comment by overath2** [comment]
Obs! Gästen och volontärer använder mobilt gränssnitt medan handläggare och admin/boende använder PC. Respektive login måste optimeras för detta.

**Comment by overath2** [comment]
Status @natischmidt ?

**Comment by natischmidt** [comment]
@overath2 alla subtask e klara för denna

**Comment by overath2** [comment]
Kan wingmate dra till done?
