### ISSUE TITLE
Härbärgets Administrera-sida

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#271]
**Beskrivning**

Som en admin på ett härbärge vill jag ha kunna ändra info och status på en sovplats så våra brukare kan se dessa med rätt info/status.

**Acceptance criteria**

AC1:
Förutsatt jag är på admin-sidan
När jag uppdaterar info och status för ett rum
Då skrivs den nya infon till databasen och
Den nya infon uppdateras för hela härbärget

*Info:
Typ: Dubbelsäng över/under, singelsäng, madrass.
Läge: Sovsal, dubbelrum, eget rum
*Status: 
Ledig/Upptagen/Avstängd

**Definition of Done**
OK from wingmate
Code checked in
Max 5 min demo video

**Subtasks**
- [ ] #288

**Comment by FannyBacklin** [comment]
Inkluderad och genomförd i ticket #5.

**Comment by Gafrelek** [comment]
@FannyBacklin So this can be closed?
