### ISSUE TITLE
Visa förfrågningar

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#272]
**Beskrivning**
Som en användare av härbärgets "förfrågningssida" behöver jag en lista på aktiva förfrågningar
så att jag kan se info om varje förfrågning

**Acceptance Criteria**
1. Förutsatt att jag är på förfrågningssidan
Och vill visa aktiva förfrågningar
Då kommer aktiva förfrågningar upp

2. Förutsatt jag ser aktiva förfrågningar
När jag klickar på en förfrågning
Då kommer följande info om den förfrågningen upp
- Datum för förfrågning gjord
- Datum för incheck
- Datum för utcheck
- Brukare: Namn

**Subtasks**
#289 

**Definition of Done**
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Overath** [comment]
Hola @patryk-banach hur går det här?

**Comment by FannyBacklin** [comment]
Inkluderad och genomförd i ticket #5.
