### ISSUE TITLE
Checka in brukare

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#277]
**Beskrivning**
Som en admin på ett härbärge behöver jag kunna anteckna i systemet att brukaren ankommit till härbärgen så vi vet hur många och var brukarna är och sover.

**Acceptance Criteria**
* AC1:
Förutsatt en brukare anlänt till härbärget och jag ser knappen “checka in”
När klickar på den knappen
Då registreras tiden för incheckningen

**Subtasks**
#

**Definition of Done**
OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by SelsabeelA** [comment]
Hej! Jag hittade inte Figma-designen för det här! Jag vill bara säkerställa att "Checka ut"-knappen ska placeras där jag har gjort i grönt? 
![image](https://github.com/user-attachments/assets/d5948135-5e9c-4b54-86c2-472dd5b88997)

**Comment by FannyBacklin** [comment]
@natischmidt kikar du på denna när du har tid :)
