### ISSUE TITLE
Lista över härbärgen

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#279]
Som en brukare vill jag kunna se vilka härbärgen som har lediga sovplatser så jag kan boka detta.

**Acceptance Criteria**
Enligt godkänd design i Figma

**Definition of Done**
OK from wingmate
Code checked in
All subtasks done or cancelled
5 min demo

**Comment by LucyMoth** [comment]
API klar, UX och frontend behövs

**Comment by overath2** [comment]
Hej @DiakoIsmail ! När kan denna starta?

**Comment by FannyBacklin** [comment]
@jani-at-noq Har vi någon annan än Gregor som kan vara wingmate på denna eller ska han kika på dessa? :)

**Comment by jani-at-noq** [comment]
Gregor kommer inte titta på detta tror jag. Jag frågar efter ny wingmate.

**Comment by jani-at-noq** [comment]
https://github.com/noQ-sweden/noQ-Frontend/pull/42

**Comment by overath2** [comment]
Hur är status här?

**Comment by FannyBacklin** [comment]
@jani-at-noq vem är wingmate på denna?

**Comment by patrik-pwned** [comment]
Jag och Ove utgår ifrån denna lista: https://docs.google.com/spreadsheets/d/1spC3rpzhPONIb56-10wlM6hMJIypNWZot05_sdqoPoE/edit?gid=0#gid=0

Finns det ytterligare en lista med härbärgena?

**Comment by overath2** [comment]
Här en till: https://docs.google.com/spreadsheets/d/1SnvmuGPEy5PnuaZFDXB7MBAURaDVk3UH1CfQGMOlIqs/edit?usp=sharing

**Comment by patrik-pwned** [comment]
Innehållet i listan har jag redan lagt in länken/filen jag bifogade. Lite förvirrande att ha olika listor  :)

**Comment by overath2** [comment]
Instämmer. Bra om vi mergar till en "master". Det var ambitionen med "externa" filen.

**Comment by patrik-pwned** [comment]
@jani-at-noq vet du om denna ticket ska fortsätta vara i in-review?

**Comment by jani-at-noq** [comment]
done
