### ISSUE TITLE
Gästens startsida

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#280]
Som en gäst vill jag ha en startsida när jag loggat in så att jag kan få en överblick över det som är viktigt för mig. 

Jag vill kunna:
- Påbörja bokning
- Se mina bokningar

**Definition of Done**
OK from wingmate
OK from PO
5 min demo video

**Comment by LucyMoth** [comment]
Är tanken här att allergier är ett fritt skrivfält eller typ en ja/nej checkbox for t.ex pälsallergi, nötallergi etc? 😁

**Comment by overath2** [comment]
Jag ändrar lite i denna. Denna story borde heta "mina inställningar". Jag skapar den för en senare dag.
Gästens startsida ska se ut som boendets startsida fast med andra moduler i översikten. Se även
https://docs.google.com/presentation/d/13eRs4bCL9AtUPST6hW5dj_hvTEtqnuhcl1_in5tfZcs/edit?usp=sharing

**Comment by FannyBacklin** [comment]
@callekrook  har du möjlighet att kika på denna som är "in review"?

**Comment by callekrook** [comment]
Yes jag håller på med det.
