### ISSUE TITLE
Boka sovplats

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#281]
**Beskrivning**
Som en gäst vill jag kunna boka ett (1) ledigt härbärge så jag kan få en reserverad sovplats där.

**Acceptance Criteria**
 Enligt godkänd design i Figma

**Subtasks**
#

**Definition of Done**
OK from wingmate
Code checked in
All subtasks done or cancelled
5 min demo video

**Comment by overath2** [comment]
Hej @DiakoIsmail ! När kan denna starta?

**Comment by FannyBacklin** [comment]
@jani-at-noq Har vi någon annan än Gregor som kan vara wingmate på denna eller ska han kika på dessa? :)

**Comment by jani-at-noq** [comment]
Allt är fixat i ticket https://github.com/orgs/noQ-sweden/projects/13/views/1?sliceBy%5Bvalue%5D=Neptunus&filterQuery=&pane=issue&itemId=75850765

**Comment by jani-at-noq** [comment]
https://github.com/noQ-sweden/noQ-Frontend/pull/42

**Comment by overath2** [comment]
@Gafrelek har slutat. Vem är wingmate?

**Comment by overath2** [comment]
Jag godkänner denna och srtänger.
