### ISSUE TITLE
Lista över brukare

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#283]
**Beskrivning**
Som en handläggare på socialtjänsten behöver jag se en lista på alla brukare som har bokat sovplatser via appen så jag kan få en överblick och godkänna/neka bokningar.

**Acceptance Criteria**
* AC1:
Förutsatt jag är inloggad och ser en lista över brukare
När jag klickar på en brukare
Då ser jag bokningshistorik med möjlighet tilll godkänna/neka en bokning samt brukarens preferenser.

**Subtasks**
#

**Definition of Done**
OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by Overath** [comment]
Vad är status här?
