### ISSUE TITLE
Avboka tilldelad sovplats

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#285]
**Beskrivning**
Som en gäst eller volontär vill jag kunna avboka en reserverad sovplats så jag kan boka annan om det inte skulle passa

**Acceptance Criteria**
* AC1:
Förutsatt det finns minst 1 förfrågning eller tilldelad sovplats OCH brukaren är inne på sin sida,
När brukaren klickar på avboka den sovplatsen
Då avbokas förfrågan/tilldelade platsen och härbärget uppdateras

**Subtasks**

**Definition of Done**
OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by overath2** [comment]
Denna blev ej ready i sprintplaneringen så jag flyttar till sprint 11
