### ISSUE TITLE
Ta fram användningsfall och wireframes för härbärgens hantering av brukare

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#286]
**Beskrivning**

Som medlem I NoQ vill jag kunna se härbärgets Användarfall och Wireframe
så att jag kan se hur produktens design kan göras

**Acceptance criteria**

Förutsatt att jag kollar efter Wireframes i Figjam
När jag tittar på Härbärgets användarfall och wireframes
Då ser jag härbärgets användarfall och wireframes

https://www.figma.com/file/w9pDi7qsOmiqDuRWo6bL4V/noQ-fl%C3%B6desskiss?type=whiteboard&node-id=0-1&t=KuTt5ZUkmVCLR9Gr-0

Se även flöde här: https://drive.google.com/file/d/1rt0TqPxOLHIrzmsuIasCXsVZi3Tglebf/view?usp=sharingAnslut ditt Google-konto 

**DoD**
OK from wingmate

**Comment by Overath** [comment]
Kan någon sätta denna till done?

**Comment by SebbeKarner88** [comment]
Jag misst5änker att denna är done, jag har lite dålig koll på vad Wireframe är :)
