### ISSUE TITLE
API Härbärgets förstasida

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#287]
### Beskrivning

Som frontend-utvecklare i NoQ vill jag hämta information från härbärget
så att det kan visas på härbärgets startsida

###Acceptance Criteria

Minst följande ska gå att få fram:

Hur många aktiva förfrågningar som väntar på att behandlas
Hur många är dagens arrivals
Hur många dagens departures
Hur många som bor just nu
Hur många lediga sovplatser uppdelat på typ av sovplats

### Definition of Done

OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by LucyMoth** [comment]
Kod incheckad, bara att se över och merga 😄
