### ISSUE TITLE
API Administrera sovplats

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#288]
### Beskrivning

Som en utvecklare vill jag kunna ta emot och skicka info till APIet om ett härbärgets sovplatser 
så att jag kan bygga en funktion för härbärget att uppdatera sovplatser

### Acceptance criteria

-AC1:
APIet ska skicka (R):
Typ: Dubbelsäng över/under, singelsäng, madrass.
Läge: Sovsal, dubbelrum, eget rum
Status: Ledig/Upptagen/Avstängd

-AC2:
APIet ska ta emot (U):
Typ: Dubbelsäng över/under, singelsäng, madrass.
Läge: Sovsal, dubbelrum, eget rum
Status: Ledig/Upptagen/Avstängd

### Subtasks
#271 

### Definition of Done
OK from wingmate
Code checked in

**Comment by FannyBacklin** [comment]
@Ovura-noq Skulle du kunna vara wingmate för denna och kika på den nu när den är "in review"?
