### ISSUE TITLE
API Visa förfrågningar

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#289]
### Beskrivning
Som utvecklare behöver jag data från APIet som visar ett härbärges förfrågningar 
Så att jag kan visa förfrågningarna och dess data på frontend

### Acceptance Criteria
AC1:
API:et ska skicka:
Förfrågning med
Datum för förfrågning gjord
Datum för incheck
Datum för utcheck
Brukare: Namn

### Subtasks
#272 

### Definition of Done
OK from wingmate
Code checked in

**Comment by Overath** [comment]
Hola! Kan vi få denna reviewad?

**Comment by Overath** [comment]
Kan någon sätta denna till done?
