### ISSUE TITLE
API Godkänn förfrågning

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#290]
### Beskrivning
Som utvecklare behöver jag ha ett API som skickar data om en förfrågning samt tar emot data
så att jag kan bygga en funktion som godkänner eller nekar en förfrågning

### Acceptance Criteria

AC1:
API:et ska skicka (R):
Aktiva förfrågningar för det aktuella härbärget

AC2:
API:et ska ta emot (U):
Godkänd eller nekad förfrågning

### Subtasks
#273 

### Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by jani-at-noq** [comment]
Detta är för härbärget, och båda AC är uppfyllda. Borde vara team Mars och closed. Jag sätter ticket som closed.
