### ISSUE TITLE
API Tilldela sovplats

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#292]
### Beskrivning
Som utvecklare behöver jag ha et API som tar emot en sovplats-tilldelning
så att jag kan bygga en funktion som tilldelar en brukare till en sovplats

### Acceptance Criteria

AC1:
API:et ska ta emot (U):
Data om att brukare tilldelats en sovplats på härbärget

### Subtasks
#274

### Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by Overath** [comment]
Hola! Kan vi få denna reviewad och klar?
