### ISSUE TITLE
Fixa gratiskonton på det som behövs (ex Google, Slack)

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#296]
###Beskrivning

Som en noQare vill jag ha bra vertyg att jobba med som inte kostar för mycket så jag kan jobba effektivt och inte belasta vår ekonomi.

###Acceptance Criteria

AC1:
Förutsatt jag loggar in på techsoup
När jag tittar i kontoslag
Då är vi godkända för deras tjänster

AC2:
Förutsatt jag loggar in på Slack som admin
När jag tittar i kontoslag
Då är vi godkända för deras fria tjänster

AC3:
Förutsatt jag loggar in på Google suite som admin
När jag tittar i admin
Då är vi godkända för deras fria tjänster
###Subtasks

###Definition of Done

OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by Overath** [comment]
Time för review @jonsing .

**Comment by jonsing** [comment]
Vad jag vet så är allt detta fixat! Drar till done.
