### ISSUE TITLE
Sätta en målarkitektur ink hur jobba med GitHub

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#297]
Som en noQare vill jag ha en arkitektur som kan vägleda mig i hur vi jobbar så vi kan jobba enhetligt och effektivt.
###Acceptance Criteria

AC1:
Förutsatt att vi är klara med sprint 24:6
När vi tittar i vår wiki (eller liknade) 
Så har vi en plan för sättande av en målarkitektur inkluderade delar av nedanstående inspiration

###Inspiration

En målarchitektur för ett webbprojekt kan inkludera flera komponenter och beslut som tas för att uppnå specifika mål. Vanliga ingredienser kan vara:

1. Tekniska komponenter: Detta kan innefatta webbserver, databaser, frontendramverk, backendramverk, samt olika verktyg och bibliotek för att hantera olika delar av webbplatsen.

2. Infrastruktur: Beslut om hostingmiljö, molntjänster, nätverkskonfiguration och skalbarhetsstrategier ingår vanligtvis i målarchitekturen.

3. Säkerhet: Implementering av säkerhetsåtgärder som HTTPS, användarautentisering och auktorisering, datakryptering och skydd mot skadlig programvara är viktiga för att säkerställa webbplatsens integritet och användares säkerhet.

4. Prestanda: Optimering av laddningstider, cachning, resursminimering och skalning för att säkerställa snabb och effektiv prestanda för webbplatsen.

5. Skalbarhet: Planering för att hantera ökande belastning och användartrafik genom skalbara arkitekturdesign och resursallokering.

6. Användarupplevelse: Designbeslut som rör användargränssnitt, navigering, responsivitet och tillgänglighet som påverkar användarupplevelsen.

7. Underhåll och support: Strategier för att hantera kodunderhåll, buggfixar, uppdateringar och support för användare.

8. Integrationer: Planering för integrationer med tredjepartstjänster, API:er och andra system som behövs för att webbplatsen ska fungera korrekt och effektivt.

Genom att definiera och dokumentera en tydlig målarchitektur kan utvecklingsteamet ha en vägledning för att säkerställa att webbprojektet uppfyller sina mål och krav på ett effektivt sätt.

###Subtasks

###Definition of Done

OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by Overath** [comment]
Den ser bra ut. Det enda jag funderar över om att nämna att vi dokumenterar i GitHubs wiki (men det kanske står i länken?) iom att du skrivit här istället för Google Drive. Men jag drar till done. Demo imorgon.

**Comment by jonsing** [comment]
Bra kommentar. Jag lägger till ett stycke om dokumentation.
