### ISSUE TITLE
Grafisk profil 

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#320]
###Beskrivning
Som besökare på vår hemsida behöver jag känna att våra sidor är konsistenta och snygga så att känner att noQ är professionella.

###Acceptance Criteria
Förutsatt jag klickar runt på vår hemsida eller intranät samt använder vara mallar i Google Drive.
När jag ska söka information eller skapa dokument.
Då känner jag igen noQ

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo

**Comment by Overath** [comment]
Vi behöver en enhetlig grafisk profil internt och externt så det framgår att vi är vi.
Jag har skapat en mapp för detta som ligger här: https://drive.google.com/drive/folders/128xJUAapi0v8HeOcT3X-8BteHBEY4zHW?usp=drive_link

Där finns idag två dokument

Dokumentation av detta arbete som blir ett dokument med den grafiska profilen. I dokumentet har jag lagt in vad detta skall innehålla.
Dokument och brevmall som vi använder när vi skapar Google doc.
Jag vill även att alla grafiska element (ex logo, banner etc) vi ska använda finns i denna mapp

**Comment by Overath** [comment]
Tjohoo! Nyfiken på status?

**Comment by callekrook** [comment]
Vi satt med det lite igår och först gick det bra men sen gick det mindre bra. Vi kommer behålla den gröna och den gråa färgen som finns nu men försöker hitta två andra färger som fungerar ihop istället för den gula och blåa. Vi trodde att vi hade hittat två nya färger men dessa klarade inte tester enligt WCAG så vi fick skrota dem. Men vi jobbar vidare.

**Comment by Overath** [comment]
Hej @patryk-banach och @callekrook hur går det här?

**Comment by Overath** [comment]
@Marohaa kan du vara wingmate?

**Comment by overath2** [comment]
Hola @patryk-banach och @callekrook ! Jag satte mig som wingmate. Hojta när ni har något. Jag skulle vilja att denna är klar senast 1/8 så vi kan skapa banners för Hackathon sedan och även uppdatera vår hemsida. Och sist bjuda in till hackathon senast 1/9.

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @callekrook och @patryk-banach ?

**Comment by overath2** [comment]
Kan du kolla denna @FannyBacklin?

**Comment by overath2** [comment]
Vi har dubblett på denna. Kan @callekrook merga de två? Se #332

**Comment by FannyBacklin** [comment]
@callekrook  Kan du uppdatera den är tasken med guesstimat? :)

**Comment by callekrook** [comment]
Stänger denna då samma finns i #332
