### ISSUE TITLE
Nyheter

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#321]
###Beskrivning
Som en besökare på vår hemsida behöver jag ha nyheter så att jag kan hålla mig ajour med vad som händer med noQ och hemlöshet.

###Acceptance Criteria
AC1:Förutsatt jag är på vår hemsida
När jag letar efter nyheter 
Då hittar jag dessa lätt.
AC2:Förutsatt jag läser nyheter så hittar jag både interna nyheter från noQ men även externa (feed?)

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Overath** [comment]
@dianayamout eller @Marohaa vem kan bli min wingmate?

**Comment by overath2** [comment]
Jag sätter igång med denna nu i sommar. Söker wingmate.

**Comment by overath2** [comment]
@natischmidt och jag har startmöte idag.

**Comment by overath2** [comment]
Har nu skapat nyhetsfunktionen i WP men jag tycker det ser "billigt" ut. Kanske ska vi avvakta tills vi får nya designen på plats @natischmidt ? Annars kom gärna med förslag på hur får det snyggare.

**Comment by overath2** [comment]
Tycker vi kan sätta denna till done nu @natischmidt ? Vi får göra det snyggare med nytt tema och den nya grafiska profilen sen.

**Comment by natischmidt** [comment]
Yes

**Comment by overath2** [comment]
Kan du dra till Done @natischmidt ?
