### ISSUE TITLE
Nyhetsbrev

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#322]
###Beskrivning
Som en besökare på vår hemsida behöver jag kunna prenumerera på nyheter från noQ så att jag kan vara uppdaterad om vad som händer.

###Acceptance Criteria
Förutsatt jag är på vår hemsida 
När vill prenumerera 
Då kan jag göra det enkelt via en funktion 

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Overath** [comment]
Är detta något för er @Marohaa och @dianayamout

**Comment by Marohaa** [comment]
Ja, vi tar ansvar för detta. Har du några texter att lägga till i nyhetssektionen? De nuvarande nyheterna är inte välskrivna och saknar relevans för användarna.

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel.
