### ISSUE TITLE
Skapa FAQ för begrepp vi använder inom Scrum

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#355]

**Comment by Overath** [comment]
Sätter mig som wingmate. Jag tycker vi kan hänvisa till Scrumguiden mycket istället för att skapa hjulet. Jag har även "lingo" sparade vi kan återvinna.

**Comment by Overath** [comment]
Repone pga fel av mig

**Comment by Overath** [comment]
Kan vi fylla på här: https://docs.google.com/spreadsheets/d/1MBUD03BmmhyoAjMdEVZNig99SGFESrnNaptiq_OGnNI/edit?usp=sharing

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel. Ping
