### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#356]
###Beskrivning
Som en noQare behöver jag ha ett ställe för dokumentation av vår kod så att framtida noQare vet hur vi byggde.

###Acceptance Criteria
Förutsatt jag tittar i GitHub 
När klickar på wiki
Då ser jag en startsida med instruktioner samt en struktur av undersidor som gör det lätt att hitta.

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Gafrelek** [comment]
Added readme on main project page with general info, https://github.com/noQ-sweden
![image](https://github.com/noQ-sweden/noq/assets/30535027/bb806135-5711-42f2-8823-74b5238ee591)

Then separate wikis for front and backend? here is a good backend info in readme https://github.com/noQ-sweden/noq_backend_python already

**Comment by Overath** [comment]
Ideally 1 wiki for all but if we are choosing several repositories maybe 1
wiki each?
/Ove

Den fre 10 maj 2024 12:53Gregor Frelek ***@***.***> skrev:

**Comment by Gafrelek** [comment]
Frontend

    https://github.com/noQ-sweden/noQ-Frontend
    [Frontend wiki](https://github.com/noQ-sweden/noQ-Frontend/wiki)

Backend

    https://github.com/noQ-sweden/noq_backend_python
    [Backend wiki](https://github.com/noQ-sweden/noq_backend_python/wiki)

added links in readme/slack/guidebook
