### ISSUE TITLE
Poster för Hackathon

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#358]
Som en potentiell deltagare i noQs hackathon vill jag bli inspirerad att anmäla mig så jag kan deltaga.

AC:
Givet det är första anmälningsdatum för Hackathon, när jag tittar på noQs hemsida, så ser jag en lockande annons/banner och nyhet om detta som har den nya grafiska profilen.

**Comment by Overath** [comment]
KAn vi köra igång denna igen @patryk-banach när grafiska profilen är klar?

**Comment by overath2** [comment]
Denna vill jag ha klar sensat 1/9. Är beroende av #320

**Comment by overath2** [comment]
> När den grafiska profilen är klar kan jag anpassa den efter den och skapa det färdiga formatet! Frågan är vilka storlekar du behöver?
Skulle vilja ha en tvärs över vår hemsida:
![image](https://github.com/noQ-sweden/noq/assets/172486215/c8e3d28b-d0c8-4304-b9f8-db0b83c4ba99)

**Comment by overath2** [comment]
@patryk-banach var lade du dina tidigare förslag?

**Comment by overath2** [comment]
Kalla gärna mig som wingmate till ett startmöte om frågetecken?

**Comment by overath2** [comment]
@patryk-banach kan du dra denna?
