### ISSUE TITLE
Organisera ''vi som jobbar här'' efter kompetens/avdelning istället för att ha det så splittrat

### ISSUE THREAD

**Issue by patryk-banach** [noQ-sweden/noq#362]

**Comment by overath2** [comment]
@patryk är den aktuell fortfarande. Kan du skriva tydliga förväntningar/krav?

**Comment by overath2** [comment]
Sätter till done med anledning att detta inte kommer att göras. Om skaparen anser detta fel så sätt till backlog igen med kommentar varför.
