### ISSUE TITLE
Härbärge hämta data frontend

### ISSUE THREAD

**Issue by SebbeKarner88** [noQ-sweden/noq#368]
###Beskrivning
Som en härberge-användare behöver jag ha information om härbergets bokningar så att vi kan tillgodose oss informationen.

Utseende ska vara enligt dahsboard:
https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=2749-519&t=HrJ8nLqVk1TgT5HC-4

###Acceptance Criteria
Förutsatt inloggad som härbärge
När vi navigerar applikationen
Då ska vi få info om härbärgets beläggning, bokningar etc.

###Subtasks
- #459 -> Done
- #461 -> Done 
- #460 -> Done
- checkas in komponent
- kalender komponent
- internschema komponent

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Denna uppfyller inte våra krav i Playbook för tickets i Github. Läs mer här: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.cg0m06jyj586
Jag sätter den i korrekt status. När åtgärdat flytta tillbaka denna.
/o

**Comment by overath2** [comment]
@FannyBacklin kan du fixa att nån tar denna?
