### ISSUE TITLE
Struktur för rollbeskrivningar

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#369]
Som en noqare vill jag bara trygg i min roll så jag kan leverera enligt förväntningar samtidigt som jag lär mig

AC:
När jag tittar I vår playbook hittar jag ett kapitel om våra roller och hur en struktur för rollbeskrivning finns som mall.

Inspiration:
https://tvivla.se/att-vara-trygg-i-sin-roll/

**Comment by Overath** [comment]
Satte mig som wingmate här @FannyBacklin

**Comment by overath2** [comment]
Denna uppfyller inte våra krav i Playbook för tickets i Github. Läs mer här: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.cg0m06jyj586
Jag sätter den i korrekt status. När åtgärdat flytta tillbaka denna.
/o

**Comment by FannyBacklin** [comment]
Rollbeskrivningar status:

- [x] Projektledare / Scrum Master - @FannyBacklin 

- [ ] Produktägare  - @Overath 

- [ ] UX Designer - Carl-Johan @patryk-banach @inhyenoq Fredrik @RasmusOUX @kingli6  (Enas gärna om en rollbeskrivning just nu har vi fler) 

- [ ] Frontend - @SelsabeelA @SebbeKarner88 @xelleze @DMould123 @jani-at-noq @tobbe-joh @Gafrelek 

- [ ] backend - @jani-at-noq @KrisPett @marco-noq @IlonaKamash 

- [ ] Devlead - @natischmidt Carl-Johan @Mrsluggan @SebbeKarner88  Vi har 2  stycken, vilken gäller? 

- [X] Product Manager - @Overath 

- [X] Valberedning

Toolmasters:
- [X] Slackmasters @FannyBacklin @Mrsluggan 
- [ ] Githhub - @Gafrelek @Mrsluggan 
- [ ] Google workplace @inhyenoq @kingli6 
- [ ] Discord - @Mrsluggan @natischmidt 
- [ ] Canva - Diana & Marah
- [ ] Figma @inhyenoq Carl-Johan
- [ ] Google Sites Diana & Marah
- [ ] Wordpress Diana & Marah

**Comment by overath2** [comment]
Saknar styrelsemedlem, styrelsesuppleant, kassör, ordförande och sekreterare.
Jag skapar dessa.

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @FannyBacklin ?

**Comment by overath2** [comment]
Funkar @FannyBacklin ?

**Comment by FannyBacklin** [comment]
Yes, vi har alla rollbeskrivningar på plats nu vad jag kan se. Tack för hjälpen med styrelsens!
