### ISSUE TITLE
Hur vi ger feedback till varandra

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#380]
Som en noQare vill ha riktlinjer och råd för hur vi ger feedback till varandra så vi kan förbättra oss och skapa gemensa respekt.

AC:
Ett stycke i Playbooken om detta

- 1 till 1
- 1 till många (retrospektiv)
- många till 1
- många till många (retrospektiv)

**Comment by Overath** [comment]
Är detta något för er @patryk-banach och @Marohaa ?

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel. Ping
