### ISSUE TITLE
Mall för stories och epics

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#382]
**User story**:
Som en noQare behöver jag veta hur jag skapar epics och stories så att jag kan bidra med idéer.

**Acceptanskriteria**: 
Förutsatt jag ska skriva en story/epic, när jag tittar i vår Playbook, så ser jag ett kapitel om detta.

**Beskrivning**:  [Arbetsdokument här
](https://docs.google.com/document/d/1bCQaFQmU2iMiiBp2lCj-R3x08sUiL6pP6tWlj-HUVqU/edit?usp=sharing)
**Ready**: Se Playbook DoR (med länk)

**Done**: Se Playbook DoD (med länk)

**Comment by Overath** [comment]
@kingli6 kan du köra denna med mig som wingmate?

**Comment by Overath** [comment]
@kingli6 är du redo?

**Comment by kingli6** [comment]
Vad tycker du om det här: [Doc](https://docs.google.com/document/d/1if2skzT5uWb-OkkJU41pWPhQNKRY4NoJy43Um5cXxUw/edit?usp=sharing)

**Comment by Overath** [comment]
Bra! Se till att det finns länkat till playbook sedan kan jag testa.
