### ISSUE TITLE
Behärska GitHub 

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#385]
###Beskrivning
Som en produktägare, Scrum master och projektledare behöver vi ha stor kunskap om konfiguration och användande av GitHub så att vi kan jobba smidigt i verktyget.

###Acceptance Criteria
Förutsatt det är 15/6
När vi tittar I GitHub 
Då kan vi enkelt jobba i detta och så att det stödjer vårt arbetssätt. 

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Gafrelek** [comment]
Hi, I think you already know as much as I do or even more. @FannyBacklin do you have any topics i should explore?

**Comment by overath2** [comment]
Done
