### ISSUE TITLE
Härbärget - CRUDa Rumstyper och Tillgängliga Rum

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#388]
###Beskrivning
Som en administratör på härbärget 
behöver jag ha möjlighet att skapa, läsa, uppdatera och ta bort rumstyper och tillgängliga rum 
så att jag kan hålla systemet uppdaterat med aktuella rum

###Acceptance Criteria
Förutsatt jag är inloggad som administratör
När jag navigerar till rumshanteringssidan
 Då kan jag skapa, läsa, uppdatera och ta bort rumstyper och rum

###Subtasks
- #392
- #393
- #481 

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Denna uppfyller inte våra krav i Playbook för tickets i Github. Läs mer här: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.cg0m06jyj586
Jag sätter den i korrekt status. När åtgärdat flytta tillbaka denna.
/o

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @natischmidt ?

**Comment by natischmidt** [comment]
Ja, bara ändringar för PR kvar det ä på g
