### ISSUE TITLE
Fetch för att acceptera förfrågningar

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#391]
###Beskrivning
Som en utvecklare behöver jag implementera en funktion för att acceptera inkommande förfrågningar så att administratören kan godkänna dem.

###Acceptance Criteria
Förutsatt att en förfrågan är markerad, 
När administratören klickar på "Acceptera"
Då uppdateras förfrågans status till accepterad i databasen

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Overath** [comment]
Hinner vi klart denna i sprinten?

**Comment by natischmidt** [comment]
> Hinner vi klart denna i sprinten?

Nej, då allt är mockdata behövs en större omstrukturering än endast den fetchen denna ticket hänvisar till
