### ISSUE TITLE
CRUD för Rumstyper och Rum 

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#392]
###Beskrivning
Som en utvecklare behöver jag implementera CRUD-operationer för rumstyper och rum i backend så att administratören kan hantera dem.

###Acceptance Criteria
Förutsatt att CRUD-operationer för rumstyper och rum behövs
När jag implementerar dessa operationer i backend
Då kan administratören skapa, läsa, uppdatera och ta bort rumstyper och rum i systemet

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Ping @jani-at-noq för review

**Comment by jani-at-noq** [comment]
Jag tror den här är redan done: https://github.com/noQ-sweden/noq_backend_python/pull/30

**Comment by jani-at-noq** [comment]
@natischmidt Detta är väl levererad redan?

**Comment by natischmidt** [comment]
jep done
