### ISSUE TITLE
Frontend komponent för att hantera rumstyper och rum

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#393]
###Beskrivning
Som en utvecklare behöver jag designa komponenter som låter administratören hantera rumstyper och rum så att dessa kan administreras via användargränssnittet.

###Acceptance Criteria
Förutsatt att administratören är inloggad
När administratören navigerar till rumshanteringssidan
Då kan administratören skapa, läsa, uppdatera och ta bort rumstyper och rum genom användargränssnittet

###Subtasks
- Skapa mock api för product changes (baserad på #393)
- Skapa sida för att visa produkter
- Skapa sida för att ändra produkt eller skapa ny produkt

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Denna uppfyller inte våra krav i Playbook för tickets i Github. Läs mer här: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.cg0m06jyj586
Jag sätter den i korrekt status. När åtgärdat flytta tillbaka denna.
/o

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @natischmidt ?

**Comment by natischmidt** [comment]
Ja, bara lite ändringar för PR kvar
