### ISSUE TITLE
EPIC: Handläggaren (på Soc)

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#396]
Vi tror att ett digitalt stöd för handläggare på kommunen så att dessa kan se beläggning på härbärgen samt behov av brukarna så att de får en överblick över situationen för hemlösa är något som en handläggare skulle vilja ha. Till skillnad från idag då enda kontakrerna består i härbärgenas månatliga fakturering samt brukarnas eventuella besök.

Vi vet att detta är sant när en handläggare sagt att vårat stöd är en del av lösningen.

Stories:
- [#453](https://github.com/noQ-sweden/noq/issues/453) Skapa funktion se lediga platser boende **-> Done**
- [#516](https://github.com/noQ-sweden/noq/issues/516) Skapa funktionalitet, godkänn/neka bokning - handläggare **-> Done**
- [#517](https://github.com/noQ-sweden/noq/issues/517) Lägg till model som kopplar ihop boende och handläggare **-> Done**
- [#520](https://github.com/noQ-sweden/noq/issues/520) Skapa sidomeny för handläggare **-> Done**

**Comment by Overath** [comment]
Kan vi ses och diskutera?

**Comment by overath2** [comment]
Hej alla assignees. Jag skulle vilja ha en assignee/driver/epic owner på alla epics. Kan ni flytta över er till fältet Wingmate istället och kan någon räcka upp handen som epic owner?

**Comment by overath2** [comment]
Se även https://docs.google.com/presentation/d/13eRs4bCL9AtUPST6hW5dj_hvTEtqnuhcl1_in5tfZcs/edit?usp=drivesdk

**Comment by overath2** [comment]
Ping @FannyBacklin . Kan du kika på denna?

**Comment by overath2** [comment]
@jani-at-noq tror du denna blir klar enligt plan?

**Comment by jani-at-noq** [comment]
Det ser bra ut, så vi borde vara färdiga innan sprinten är slut.

**Comment by overath2** [comment]
Uppdaterad kravspecifikation: https://drive.google.com/file/d/1qi082jRbWu4oZZIaqHL2p6gJBTGxX2Cs/view?usp=drive_link
Ping @jani-at-noq

**Comment by overath2** [comment]
Obs! Gästen och volontärer använder mobilt gränssnitt medan handläggare och admin använder PC. Respektive login måste optimeras för detta.

**Comment by overath2** [comment]
Status  @jani-at-noq ?

**Comment by jani-at-noq** [comment]
Allt är klart. Du kan sätta Epic till done @overath2

**Comment by overath2** [comment]
Hurra!
