### ISSUE TITLE
Planera kommande rekrytering

### ISSUE THREAD

**Issue by patryk-banach** [noQ-sweden/noq#397]
Diskutera hur rekrytering gällande spetskompetens ska ske.

**Comment by Overath** [comment]
Jag är redo när du är @patryk-banach

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel. Ping @patryk-banach
