### ISSUE TITLE
EPIC: Miljöer

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#398]
Vi tror att en systemarkitektur där vi har olika miljöer med olika nivåer på säkerhet, tillgänglighet och prestanda är nödvändigt för att vi ska kunna bygga våra applikationer med en modern och skalbar arkitektur till skillnad från idag då vi har en miljö för utveckling, test, produktion etc.
Vi vet att detta är sant när vi satt upp fler än en miljö och finner det fungera.

Dokument för att beskriva deployment alternativ och arkitektur:
https://docs.google.com/presentation/d/1_uOMHUhDzGz8oVoecij03kRrmrzTMr3ILxx3DyNZseA/edit?usp=sharing

- [x] #463 
- [x] #462 

Test deployment in AWS lightsail

- [x] #474 
- [x] #475 
- [x] #485 
- [x] #583

**Comment by Overath** [comment]
Här vill jag att devlead + mentorer deltager. Ping @Mrsluggan , @cheijken @Marohaa , @SebbeKarner88 , @jonsing Andre och Flilip

**Comment by Overath** [comment]
Gärna en första workshop innan sommaren

**Comment by Overath** [comment]
Fokus skall vara på

1. Utvecklingsmiljö
2. Demo/Utbildningsmijö
3. Produktionsmiljö
4. Testmiljö

**Comment by Overath** [comment]
Först ut för att bryta ner denna är ett startmöte. Det team som tar sig an uppgiften bjuder in till detta med berörda.

**Comment by Overath** [comment]
Så här tänker jag: https://drive.google.com/file/d/1ANcKjYKp7HQ8-VGkwWdJWMZR3IpoeRMf/view?usp=drive_link

**Comment by jani-at-noq** [comment]
Added new subtask for creating the container for the application.

**Comment by overath2** [comment]
Denna är in progress va? Blir den klar till 10/10?

**Comment by overath2** [comment]
Funkar?

**Comment by overath2** [comment]
@natischmidt flyttar du den till in progress och kommenterar om den blir klar i augusti?

**Comment by natischmidt** [comment]
@jani-at-noq vad är statusen på denna o dess subtask?

**Comment by jani-at-noq** [comment]
Jag har uppdaterad beskrivningen. Vi har nu miljö som funkar, men den är inte optimalt och behöver ändras. Framförallt är det för dyrt tjänst just nu i Lightsail. Vi behöver flytta till billigare variant och då behöver vi göra om nyklarna och uppdatera pipeline. Det kommer vara lite skakigt tills vi har bestämt vilken deal är bäst i det långa loppet.

**Comment by overath2** [comment]
Denna är in progress va @natischmidt ?

**Comment by natischmidt** [comment]
> Denna är in progress va @natischmidt ?

Ja

**Comment by overath2** [comment]
Kan vi flytta denna från Sommar?

**Comment by overath2** [comment]
Flyttad in till team Jupiter som får driva denna vidare.

**Comment by overath2** [comment]
Can we close this epic @natischmidt ?

**Comment by overath2** [comment]
Vad händer @natischmidt ?

**Comment by natischmidt** [comment]
@overath2 en subtask till denna är kvar.

**Comment by overath2** [comment]
OK. Jag lägger den etta i nästa sprint. Men sedan en till va? Docker images?

**Comment by natischmidt** [comment]
> OK. Jag lägger den etta i nästa sprint. Men sedan en till va? Docker images?

Stämmer, men antigen är den inte länkat eller så har tasken inte skapas än.

**Comment by natischmidt** [comment]
laggt till docker subtask

**Comment by overath2** [comment]
Tasken hamnade i sprint 11.

**Comment by overath2** [comment]
Kan vi få denna klar i 11 @natischmidt ?

**Comment by natischmidt** [comment]
Jag kollar status på den subtasken som är kvar.
