### ISSUE TITLE
EPIC: Förbättra Härbärgen för att Öka Användarkomfort och Säkerhet

### ISSUE THREAD

**Issue by kingli6** [noQ-sweden/noq#399]
## Hypotes:
Vi tror att förbättring av härbärgen genom bättre hantering och underhåll av faciliteterna, inklusive säkerhets- och hygienåtgärder, kan hjälpa brukarna att känna sig tryggare och mer bekväma.

Till skillnad från idag då användarna undviker härbärgen på grund av dåliga förhållanden som droganvändning, dålig hygien och risk för stölder, så tror vi att detta skapar en mer attraktiv och säker miljö för alla användare.
Vi vet att detta är sant när följande mätbara mål uppnåtts:

- Minst 10 användare rapporterar förbättrade levnadsförhållanden i härbärgen.
- En minskning av rapporterade stölder och våldsincidenter med 50%.
- En ökning av antalet användare som väljer att bo i härbärgen med 20%.

## Beskrivning:
Härbärgen står inför flera problem, inklusive dålig hygien, säkerhetsproblem, och dålig hantering under helger. Vi har fått feedback från användare som nämner problem som droganvändning, sjukdomar, och stölder. Vi vill utforska och implementera lösningar som kan förbättra dessa förhållanden och därmed öka komfort och säkerhet för användarna.

På lång sikt strävar vi efter att förändra härbärget så att personer som tillfälligt behöver en sängplats ska kunna använda det. I länder som Kina finns det tjänster som spa-hus där man kan duscha, köpa mat, sova och umgås för en minimal kostnad. Priserna är ännu lägre under helgerna. Vi vill omvandla härbärget till en mer acceptabel plats som alla kan använda. Målet är att förvandla upplevelsen för hemlösa så att ingen ska kunna identifiera dem som sådana.

## Länk till Spike
https://github.com/orgs/noQ-sweden/projects/8/views/1?pane=issue&itemId=64552285

**Comment by overath2** [comment]
Kan bara 1 vara assignee/epic owner.

**Comment by overath2** [comment]
Vi stänger denna pga dublett.
