### ISSUE TITLE
Skapa login sida samt funktion

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#402]
###Beskrivning
Som en utvecklare behöver jag skapa 
en login-funktion och login-sida samt koppla 
dessa mot backend login API så att användare kan logga in.

###Acceptance Criteria
Förutsatt att användaren är på login-sidan
När användaren fyller i sina inloggningsuppgifter och skickar formuläret
Då ska användaren autentiseras mot backend och loggas in om uppgifterna är korrekta

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by SebbeKarner88** [comment]
Grymt!

**Comment by overath2** [comment]
This need to be integrated in Venus platform. Please collaboaret @jani-at-noq and @Ovura-noq
