### ISSUE TITLE
Visa loginsida endast i utloggat läge

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#403]
###Beskrivning
Som en utvecklare behöver jag ändra noQ så 
att det visar endast login-sidan om användaren
inte har loggat in så att obehöriga inte kan komma åt skyddade sidor.

###Acceptance Criteria
Förutsatt att användaren inte är inloggad
När användaren försöker navigera till en skyddad sida
Då omdirigeras användaren till login-sidan

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by jani-at-noq** [comment]
Patch för login gör detta, men utan någon vidare tanke för design eller kvalite. Jag ville bara testa att login funkar, så det är bra om du gör om App.jsx ändringar jag har lagt in.

**Comment by SebbeKarner88** [comment]
Super! nu kör vi! :)
