### ISSUE TITLE
Visa gruppbaserad info efter inloggning

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#404]
###Beskrivning
Som en utvecklare behöver jag ändra noQ så att gruppbaserad information 
visas efter login baserat på användarens roll så att användaren får relevant innehåll.

###Acceptance Criteria
Förutsatt att användaren har loggat in
När användaren har en specifik roll (t.ex. user eller host)
Då visas innehåll och sidor baserat på användarens roll

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by SebbeKarner88** [comment]
Riktigt snyggt!
