### ISSUE TITLE
Mallar I GitHub 

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#405]
###Beskrivning
Som en noQare behöver jag ha mallar i GitHub för de vanligaste tickets så att jag lätt kan skapa nya.

###Acceptance Criteria
Förutsatt det är 20/6
När tittar I GitHub
Då ser jag mallar för stories, epics och tasks. 

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Gafrelek** [comment]
could you give examples? 
this one is already set up
![Image](https://github.com/noQ-sweden/noq/assets/30535027/cdce90bf-e8c4-4829-bd8d-225cebad977a)

**Comment by Gafrelek** [comment]
![image](https://github.com/user-attachments/assets/6cea15e2-1525-4f5e-be02-c2909501cd03)
![image](https://github.com/user-attachments/assets/6934c19f-1d81-49c9-861d-fb71e9f51fb7)
![image](https://github.com/user-attachments/assets/a124f0df-b6c0-4c2f-ac5a-8eda9e96328b)

Found your templates, when new ticket is created those 2 are avaiable including template from you. Please check and close if its ok

**Comment by Gafrelek** [comment]
@overath2 can you check ?

**Comment by overath2** [comment]
@Gafrelek where do i find them for edit?

**Comment by overath2** [comment]
Looks ok now for me. All three templates available bot in pc/mobile. Creating demo then done?

**Comment by overath2** [comment]
Demo: https://drive.google.com/file/d/1hOhL6Bh-UV0m1rCnzWq-ZVM1NEGWrQQu/view?usp=drive_link
