### ISSUE TITLE
Add mocked Login API to enable testing of frontend with correct API data without running the backend

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#406]
###Beskrivning
Som en utvecklare behöver jag ha mock API för login funktionalitet så jag kan testa frontend implementation utan att starta backend.

###Acceptance Criteria
Användare kan logga in till appen med förbestämda använder uppgifter utan att frontend är kopplat till backend
utvecklare kan välja om man kör react med mock API eller med riktigt backend när mans startar npm server.

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

Development Branch for frontend: https://github.com/noQ-sweden/noQ-Frontend/tree/366-inloggningssida

**Comment by SebbeKarner88** [comment]
Toppen!
