### ISSUE TITLE
App script to automate Google Workplace onboarding

### ISSUE THREAD

**Issue by inhyenoq** [noQ-sweden/noq#411]
Build an app scripts to automate Google Workplace onboarding.

**New user routine**
Trigger: by request
Function:
1. Create an user on Google Workplace 
- required information: first name, last name, noq mail address, contact email (personal email)
2. Add noQ Gemensamma Kalender to the user account
`gam user [email address] add calendar c_7d4de8338a7cada36ed65a424a34cd0550293c642c34d2d998327b3d71e5cfa7@group.calendar.google.com reminder popup 10 notification email eventcreation colorindex 16`
3. Send an email to inform contact point to Google Account.
4. Send a email to ask Fanny to create Slack account. 

**Reminder routine**
Trigger: time based - automatically o the first day of every month
Function:
1. List users who have never logged in.
2. Send a reminder to their contact email.
3. Send the list to the super users.

**Comment by overath2** [comment]
Who is the wingmate?

**Comment by inhyenoq** [comment]
@kingli6 Could you take the wingmate role for this?

**Comment by overath2** [comment]
Looks interesting. I will be the wingmate if @kingli6 is unavailable. Ping me next week.

**Comment by overath2** [comment]
In step 5 - can we send link to self signup in Slack with the new noq-email in the same mail? Then we can skip 6.

**Comment by inhyenoq** [comment]
The Apps script project is ready. User Management: [https://script.google.com/d/1wSgaCbqBU3Oa0K6r0QIxNYEGcSCcvvBoCvqumBRRh34Rn-TZluBWcO1S/edit?usp=drive_link](https://script.google.com/d/1wSgaCbqBU3Oa0K6r0QIxNYEGcSCcvvBoCvqumBRRh34Rn-TZluBWcO1S/edit?usp=drive_link)

It consists of two script. 
### newUserRoutine.gs
**Script functions**
1. Collect user information from a [Google Sheet]: (https://docs.google.com/spreadsheets/d/1O48R1ewvlh2vvHfsv018soZM1q1kAPgMgtlMpCz0GlA/edit?usp=sharing)
2. Test user email availability and create an alternative if needed (add a few letters of last name. e.g. [inhye.p@noq.nu](mailto:inhye.p@noq.nu))
3. Create a new noq user account with the tested user email.
4. Send the noQ account invitation to private email and the Slack invitation to noQ email. 
5. Notify the requester about the process result
6. Add noQ gemensamma kalendern to user's noQ Google calendar.

**Internal workflow for new user creation**
1. A board member submits a request using a Google Form: (https://forms.gle/ska7T5wiABsZoNz28).
2. Google Superuser ([inhye@noq.nu](mailto:inhye@noq.nu)) receives a notification about the form submission.
3. Google Superuser executes newUserRoutine
Note that access to the script should be restricted to only google superusers as it contains Google Workplace admin credentials.

### inactiveUsers.gs
1. Generate a list of users who have not signed in noQ email during the recent 30 days.
2. Send a notification to each user via a recovery email or slack message.
3. Send the report about the inactive user list and notification results to the google admin.

**Comment by overath2** [comment]
Exiting. Ping when ready for test.

**Comment by WendyPark** [comment]
@overath2 you can test now. 
You may need to adjust the inactive user routine script a little bit to not send out notifications unnecessarily.
https://docs.google.com/open?id=1wSgaCbqBU3Oa0K6r0QIxNYEGcSCcvvBoCvqumBRRh34Rn-TZluBWcO1S

**Comment by overath2** [comment]
I will test today. Do not forget the demo so i can drag it to done later.

**Comment by overath2** [comment]
Fyllde i formuläret med ny user och min privata email.
Men det kom inget mail till min privata mail. Är det delay eller måste någon godkänna?
Ping @inhyenoq

**Comment by inhyenoq** [comment]
> I fillled in the form successfully and got a verification email to my noq-email but no mail to my private email. No user is created in admin as i can see? Ping @inhyenoq

Fixed! Nothing wrong with the script. The google sheet cells had indicated wrong reference cells.

**Comment by overath2** [comment]
OK, i will test again tomorow

**Comment by FannyBacklin** [comment]
@inhyenoq Kan du uppdatera den är tasken med guesstimat? :)

**Comment by overath2** [comment]
Testad again. Still no email to my private email. Ping @inhyenoq

**Comment by inhyenoq** [comment]
@overath2 I can see you have submitted a request on the form but didn't execute the script. What is the test process you think? Do you want me execute the script as you send a request?

**Comment by overath2** [comment]
Ah. I thought the script was executed automaticly?
Let me think....

**Comment by overath2** [comment]
The optimal way would be

1. User submit application after joining infomeeting.
2. Notications is automaticly sent via email to user and styrelsen@noq.nu (later hr@noq.nu) 
3. HR scans application and reach out to user for a F2F interview and gets earliest startdate.
4. HR decide on startdate in a team togehter with teamlead.
5. HR submits user, date etc in the system
6. Credentials to noq-email is sent to user private mail and HR when 5 is submitted
7. In this welcome email (6) link to our onboarding process plus expectatinons on startdate etc

**Comment by inhyenoq** [comment]
@overath2 This was not intended to automate whole onboarding process but for Google admin task automation. 
But, yes, it can trigger the script automatically. 
Please send me a sample email of a welcome email.

**Comment by overath2** [comment]
Hang on. This is the vision when we have HR onboard. I am just scetching out the routine for now... give me 5.
Meanwhile, check Playbook for this welcome mail.

**Comment by overath2** [comment]
But for now....

1. User submit application after joining infomeeting. https://docs.google.com/spreadsheets/d/1xoAlfllpLVBz7YJzU3UClyuT6wPtaTDv8bwNMbbnYnQ/edit?usp=sharing
2. We scan manually this sheet
3. We submit startdate, name, private email in our system after checking with teamlead
4. A new user in Google workspace is created
5. Credentials to new noQ-email is automaticly sent via private email to user and [styrelsen@noq.nu](mailto:styrelsen@noq.nu) (later [hr@noq.nu](mailto:hr@noq.nu))
6. In this welcome email (6) link to our onboarding process plus expectations on startdate etc

**Comment by inhyenoq** [comment]
<img width="641" alt="image" src="https://github.com/user-attachments/assets/26fdf11e-2c63-4227-8d5a-9763f8ebb760">
I guess it should be modified to specify the start date?

**Comment by overath2** [comment]
Exact

**Comment by overath2** [comment]
Also we should now think twice about language...

**Comment by overath2** [comment]
Note the link to "vårt intranät" where the user do all other applications for credentials etc.

**Comment by overath2** [comment]
Startdate = Agreement between HR/User/teamlead

**Comment by inhyenoq** [comment]
When is the date to create the new account?  The day HR submits startdate, name, private email in our system?

**Comment by overath2** [comment]
HR = Fanny and me until we get someone but pehaps create a new group/email for this where Fanny and i starts. I dont like HR though - perhaps People & Culture as a name?

**Comment by overath2** [comment]
Yes, HR submits the actual startdate after discussions.

**Comment by inhyenoq** [comment]
Okay, please finalise the welcome letter text. Meanwhile I will modify the script to this way:
3. Submitting startdate, name, private email triggers the execution of the script 
4. Create a new user in Google workspace and set the shared calendar, etc.
5. Credentials to new noQ-email is automaticly sent via private email to user, [styrelsen@noq.nu](mailto:styrelsen@noq.nu) (later [hr@noq.nu](mailto:hr@noq.nu)) and Google admin.
6. In this welcome email (5) link to our onboarding process plus expectations on startdate etc

**Comment by overath2** [comment]
OK text updated in Playbook. Now also in english.

**Comment by overath2** [comment]
Great work! I was not aware of this opportunity. It will help alot. I will contiune test next week if you think you are done by then. No hurry. Have a nice weekend @inhyenoq

**Comment by overath2** [comment]
If possible, send email to new group toolmasters@noq.nu as well on 5.

**Comment by overath2** [comment]
I will be on a short vacation. Hope to test on tuesday?

**Comment by inhyenoq** [comment]
@overath2 Thanks for checking up! Let me try!

**Comment by overath2** [comment]
This is superb @inhyenoq . Both the solution. As always some minors:

- [ ] The welcome mail should go to the new noq account and not the private
- [ ] Spelling Ervjudan in email title should be Erbjudan
- [ ] Link here in this ticket to folder where future Google toolmasters can easily modify and styrelse members easily can administrate. Sugg: demo film, flow, documentation.

**Comment by inhyenoq** [comment]
These are fixed.
- It will sends the welcome mail to the new noq account.
- Changed the noQ account invitation email title to "Skapa ditt nya noq-konto"
- A Toolmasters group: toolmasters@noq.nu - all [current toolmasters](https://noq2.slack.com/files/U06PWF3SDJ7/F07M83EK39A/img_3378.jpg) belong to. 

And please check these. @overath2 

- [ ] The system test checks availability of the user name. If the same first name exists, add few letters of the last name. (in the demo, because _inhye@noq.nu_ exists, it created _inhye.t_ for the first new user, inhye Today, and _inhye.to_ for the second new user, Inhye Tomorrow.).

- [ ] Sender email can be one of the email I have the access because the apps script processes through my account. I can change it to toolmasters@noq.nu. Will it be sufficient?

**Comment by inhyenoq** [comment]
Link to the folder for the administrators. (Access available for the Google toolmasters (editing) and Styrelsen (commenting) 
https://drive.google.com/drive/folders/1ag0tOIrVDDwSEGlPDmbZmNsrGuxgN4G6?usp=drive_link
- app script file
- demo film
- interaction flow
- the log sheets and documentation
- the form

**Comment by inhyenoq** [comment]
> ps. Can we create new user accounts for hemlösa/gäster like this as well? They often do not have email.
Please create another ticket!

**Comment by overath2** [comment]
> > ps. Can we create new user accounts for hemlösa/gäster like this as well? They often do not have email.
> 
> Please create another ticket!

https://github.com/noQ-sweden/noq/issues/563

**Comment by overath2** [comment]
All good. 

- [ ]  Pls create group google.toolmaster@noq.nu for this.
- [ ] Also move the folder to somewher everyone can access.

**Comment by overath2** [comment]
Moving to done. Congrats!
Lets see if @FannyBacklin can operate it as well.

**Comment by inhyenoq** [comment]
@overath2 The folder is now accessible for everyone in noQ. 
But I moved the apps script project in a separate place to allow only Google toolmasters access to the file. As it contains the Google Workplace admin credentials, the app script project shouldn't be accessible to non-admin users. 
Also, I will not place this folder under noQ delad enhet because editing the data file without understanding of the apps script will cause system errors. Note that limiting access to a particular file under the noQ delad enhet is not possible because all files and folders in a shared drive should always have the same access with the parent folder.
