### ISSUE TITLE
UX för Startsida Handläggare

### ISSUE THREAD

**Issue by RasmusOUX** [noQ-sweden/noq#413]
###Beskrivning
Som en handläggare behöver jag ha en fin design så att sidan känns välkomnande och användarvänlig.

###Acceptance Criteria
Förutsatt att man är inloggad som handläggare,
Då vill vi bli välkomnade av en snygg och användarvänlig design.

###Subtasks

###Definition of Done
OK from wingmate
Figma done
All subtasks done or cancelled

**Comment by Overath** [comment]
@RasmusOUX borde inte denna satts till done av Wingmate?
