### ISSUE TITLE
Ansöka om licenser för IntelliJ IDEA

### ISSUE THREAD

**Issue by SebbeKarner88** [noQ-sweden/noq#415]

**Comment by Overath** [comment]
Hur går det med denna? Wingmate?

**Comment by SebbeKarner88** [comment]
Har ej fått svar! Wingmate öppen för frivillig :)

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel. Ping @SebbeKarner88
