### ISSUE TITLE
 Utveckla och slutföra design för teamets logga

### ISSUE THREAD

**Issue by Mrsluggan** [noQ-sweden/noq#417]
Som en noQare vill jag ha en professionell och inspirerande design för teamets logga för att stärka vår identitet och samhörighet inom teamet.

Acceptance Criteria (AC):

1. Skapa initiala designförslag:
     Utveckla minst tre olika designkoncept som representerar teamets värderingar och identitet.
     Använd professionella designverktyg som Adobe Illustrator eller Photoshop.

2. Leverera förslagen som kan presenteras för teamet.
    Insamling av feedback från teamen: 
    Dokumentera feedback och förslag på förbättringar från samtliga teammedlemmar.

 3. Slutlig design och godkännande:
    Justera och förbättra designen baserat på den insamlade feedbacken.
    Presentera det slutgiltiga designförslaget för teamet för slutligt godkännande.
    Säkerställ att den slutliga logotypen finns i olika format (vektor, PNG, etc.) för både digital och tryckt användning.

**Comment by Overath** [comment]
Riktigt snyggt på demon men nu behöver vi en wingmate...

**Comment by FannyBacklin** [comment]
@RasmusOUX  är denna klar?

**Comment by RasmusOUX** [comment]
> @RasmusOUX är denna klar?

Ja

**Comment by overath2** [comment]
OK, sätter till done.
