### ISSUE TITLE
Härbärget - Landing page för härbärget

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#423]
###Beskrivning
Som en administratör på härbärget
behöver jag huvudsidan som ger mig möjligheten att navigera mellan mina uppgifter (updatera info, acceptera användare, ...)
så att jag kan hitta rätt och svara på och administrera förfrågningar.

###Acceptance Criteria
Förutsatt att admininistrator har loggat in i applikationen
Får jag fin vy med dom viktigaste sakerna jag ska jobba med och meny för saker jag behöver sällan
Då kan jag hitta rätt i applicakationen

###Subtasks
- #456 -> Done
- #368 -> Done
- #457 -> Done

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Denna uppfyller inte våra krav i Playbook för tickets i Github. Läs mer här: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.cg0m06jyj586
Jag sätter den i korrekt status. När åtgärdat flytta tillbaka denna.
/o
