### ISSUE TITLE
EPIC: Drop-in träning

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#424]
Vi tror att brukare behöver en mötesplats och motion på ett strukturerat sätt så att de känner samvaro och får bättre hälsa. Till skillnad från idag där detta saknas förutom träningar i fotboll med Gatans lag så skapar detta en fysisk mötesplats med en digital bokning.
Vi vet att detta är sant när minst 10 deltagare och 2 ledare kommer på den första träningen.

**Comment by Overath** [comment]
Först ut för att bryta ner denna är ett startmöte. Det team som tar sig an uppgiften bjuder in till detta med berörda.

**Comment by overath2** [comment]
Mapp för filer: https://drive.google.com/drive/folders/1cEF61XdTTav-fB-_SyHVpi7qDhkFEkW9?usp=drive_link

**Comment by overath2** [comment]
Gatans lag är intresserade av samarbete. De kommer med 2 ledare och förhoppningsvis kan dela kostnaden.
Styrelsebeslutvpå att testa 2 gånger och utvärdera

**Comment by overath2** [comment]
Pågår. Första test 18/10.

**Comment by overath2** [comment]
Två tillfällen inbokade i november.

**Comment by overath2** [comment]
Första gången avklarad. Andra planerad.
