### ISSUE TITLE
Samma kolumner i alla board i GitHub

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#426]
Som en noQare vbehöver jag känna igen mig oavsett vilken board jag använder så jag kan arbeta lätt i GitHub.

AC:
Givet jag vill jobba med tickets i Github
När jag byter vy mellan boards
Så ser jag samma layout avseende kolumner i alla boards och även dokumentation om detta i Playbooken.

**Comment by Overath** [comment]
Någonting fö @Gafrelek ?

**Comment by Gafrelek** [comment]
Could you clarify which boards should have same settings? Do you mean teams boards or others too?

**Comment by overath2** [comment]
I think this is done if you @Gafrelek do a review of the new project "Hösten 2024" i have created. I january i hope we can use this project as a template for next project "Våren 2025". Please check if it is good configured for our purposes.

**Comment by Gafrelek** [comment]
i tested, using that template will copy all without issues and pull requests, but all custom fields etc are reusable 
![image](https://github.com/user-attachments/assets/d315bb7b-b6ae-4ffc-a91a-57bd32cad6e2)
so all good
