### ISSUE TITLE
User Story: Teambuilding

### ISSUE THREAD

**Issue by kingli6** [noQ-sweden/noq#428]
### Beskrivning:
Som en noQare vill jag delta i ett teambuilding-event, antingen online eller i person, för att stärka banden med mina kollegor.

### Acceptance Criteria:
Förutsatt att vi har arrangerat ett teambuilding-event,
När vi utvärderar eventet,
Då har vi fått positiv feedback från deltagarna och sett en ökad sammanhållning i teamet.

### Subtasks:
- Undersöka möjliga platser och aktiviteter för ett fysiskt teambuilding-event.
- Planera och arrangera ett online teambuilding-event.
- Skicka ut inbjudningar och samla in anmälningar från medarbetarna.
- Organisera aktiviteter och material för både online och fysiska event.
- Utvärdera feedback från deltagarna efter eventet.

### Definition of Done:

-  OK från teammate.
-  Alla deluppgifter slutförda eller avbrutna.
-  Max 5 min demo video som sammanfattar eventet och feedback.

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel. Ping @kingli6
