### ISSUE TITLE
User Story: Community of Practice (CoP) Event

### ISSUE THREAD

**Issue by kingli6** [noQ-sweden/noq#429]
### Beskrivning:
Som en noQare som är intresserad av gemensamt lärande, vill jag delta i en Community of Practice-session där vi kan diskutera och utforska idéer som kan bidra till noQ's framtida utveckling.

### Acceptance Criteria:
Förutsatt att vi har arrangerat en CoP-session,
När vi utvärderar sessionen,
Då har vi samlat in värdefulla idéer och insikter som kan användas för framtida utveckling inom noQ och för egen intresse.

### Subtasks:

- Bestämma ett ämne för CoP-sessionen.
- Skicka ut inbjudningar och samla in anmälningar från intresserade medarbetare.
- Förbereda material och resurser för diskussionen. 
- Faciliera CoP-sessionen.
- Dokumentera idéer och insikter som framkommer under sessionen.
- Utvärdera sessionens framgång och samla in feedback.

### Definition of Done:

- OK från Teammate.
- Alla deluppgiter slutförda eller avbrutna.
- Max 5 min demo video som sammanfattar sessionen och de viktigaste idéerna.

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel. Ping @kingli6
