### ISSUE TITLE
User Story: noQare behövs för rekrytering av personal på härbärge och SOS-mottagning

### ISSUE THREAD

**Issue by kingli6** [noQ-sweden/noq#430]
### Beskrivning:
Som en noQare vill jag rekrytera volontärer från noQ som kan ringa upp personer som arbetar på härbärgen och SOS-mottagningar, så att vi kan rekrytera dem för intervjuer och förbättra vår plattform.

### Acceptance Criteria:
Förutsatt att vi har volontärer från noQ,
När de ringer upp personer som arbetar på härbärgen och SOS-mottagningar,
Då har vi rekryterat tillräckligt många personer för intervjuer och noterat deras uppgifter i ett dokument så att andra noQare kan intervjua dem om det behövs.

### Subtasks:
- Rekrytera volontärer från noQ som är villiga att delta i ringarbetet.
- Skapa en lista över härbärgen och SOS-mottagningar att kontakta.
- Förbereda en samtalsguide för volontärerna att följa.
- Organisera träningssessioner för volontärerna för att säkerställa att de vet hur de ska genomföra samtalen.
- Förse volontärerna med en mall för att notera kontaktuppgifter och rekryteringsstatus.
- Sammanställa och dela dokumentet med rekryterade kontakter med relevanta noQ-medlemmar.

### Definition of Done:
- OK fråm Teammate för rekryteringsinsatsen.
- Alla deluppgifter slutförda eller avbrutna.
- Max 5 min demo video som visar processen för att rekrytera och notera kontakter.

**Comment by overath2** [comment]
Sätter till done med anledning att detta inte kommer att göras. Om skaparen anser detta fel så sätt till backlog igen med kommentar varför.
