### ISSUE TITLE
Mall mailsignatur

### ISSUE THREAD

**Issue by RasmusOUX** [noQ-sweden/noq#434]
Som en noQ:are så behöver jag ha en signatur till min mail. Denna signatur behöver ha en mall som som säkerställer att den ser ut på samma sätt hos alla så att en person som mottar mail från flera noQ:are ska se olika signaturer.

Mallen måste innehålla. 
Namn
Titel/Arbetsuppgift följt av noQ
noQ.nu
potentiellt något som beskriver vad vi gör som t.ex. IT-lösningar som stödjer samhällets utsatta.

DoD:
Har presenterats i demokanalen
Mallen finns på google drive
Ok från Wingmate

**Comment by overath2** [comment]
Städar backloggen. Denna sätter jag till done då den inte fått någon kärlek på länge. Dra tillbaka till backlog med kommentar om detta är fel. Ping @RasmusOUX
