### ISSUE TITLE
Möte i kalender på fel dag

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#437]
Jag vidarebefordrade ett möte till min jobbkalender och den lade sig på fel dag. Här möte den 13e som ska vara 14e.

![Image](https://github.com/noQ-sweden/noq/assets/5494479/4d8741f4-e0c1-4793-b7da-eedbeecc9dce)

**Comment by RasmusOUX** [comment]
För mig så dök mötet upp i en kalender som jag endast använder för inloggning på datorn.

**Comment by overath2** [comment]
Kan du kolla @inhyenoq ?

**Comment by inhyenoq** [comment]
> För mig så dök mötet upp i en kalender som jag endast använder för inloggning på datorn.

@RasmusOUX Kan du ta skärmbilder på deviser när du kan inte se mötet?

**Comment by inhyenoq** [comment]
> Jag vidarebefordrade ett möte till min jobbkalender och den lade sig på fel dag. Här möte den 13e som ska vara 14e.

@overath2 
Kan du inbjuda mig till mötet som vara på fel dag? Jag måste kolla upp det mötet i kalendern.

**Comment by overath2** [comment]
Tror det är överspelat. Kan ej återskapa.

**Comment by overath2** [comment]
OK, jag säger till om det inträffar igen.  Jag stänger.
