### ISSUE TITLE
Toolmasters support

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#438]
Som en noquare behöver jag ha en enkel process för att få support med ett verktyg så jag kan komma förbi ett problem.

AC:

- En mailadress eller slackadress dit man kan posta så toolmasters ser
- En sida i playbook och på intranät där det framgår vilka som är toolmasters.

**Comment by FannyBacklin** [comment]
Det här finns redan så den här kanske vi kan stänga? @Overath

**Comment by overath2** [comment]
Japp!
