### ISSUE TITLE
BUG: Fel länkar i Onboarding

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#442]
Länkarna på Intranätet avseednde playbook går till den gamla:

![Image](https://github.com/noQ-sweden/noq/assets/5494479/614fcfd8-eabe-4e0e-8c2c-7582b7fdd577)

**Comment by FannyBacklin** [comment]
@natischmidt Hur går det med denna? Vill du ha någon support i denna? :)

**Comment by natischmidt** [comment]
den e klar
