### ISSUE TITLE
Main thread protection

### ISSUE THREAD

**Issue by Gafrelek** [noQ-sweden/noq#446]
###Beskrivning
Som githbub admin behöver jag en inställningar för att skydda huvudgrenen så att vi har kontroll över pushad kod,

###Acceptance Criteria
Förutsatt filialinställningar
När koden trycks till huvudgrenen
Då efter kodgranskning accepterar andra medlemmar av NoQ det

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Gafrelek** [comment]
Implemented by added minimum code review 
![image](https://github.com/user-attachments/assets/d3e0d510-c54e-4c10-8067-c7282b959fd4)
currently 1 review is needed.

**Comment by Gafrelek** [comment]
@Mrsluggan Can you take a look?

**Comment by FannyBacklin** [comment]
@Gafrelek Hello Gregor, who can be your wingmate on this one? :D

**Comment by Gafrelek** [comment]
@Mrsluggan ?

**Comment by FannyBacklin** [comment]
@natischmidt sätter dig som wingmate, hoppas de är ok? :)

**Comment by FannyBacklin** [comment]
@Gafrelek what is the guesstimate on this story? :)

**Comment by Gafrelek** [comment]
Well it's done, at least the basic version. I could be improved later with additional requirements etc.

**Comment by overath2** [comment]
@natischmidt status?
