### ISSUE TITLE
Enkät för intervju 

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#447]
###Beskrivning
Som en noQare behöver jag ha en enkät jag kan sända till en som ska intervjuas så att vi kan använda dessa svar i intervjun.

###Acceptance Criteria
Förutsatt vi gör nästa intervjun
När vi tittar i våra formulär
Då finns där svar vid kan ställa följdfrågor om

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Jag har skapat en prototyp här nu för någon att jobba vidare med: https://forms.gle/8Vscf2PCaq5uxtS6A.
Ligger i mappen formulär för editering.

**Comment by overath2** [comment]
Har skickat mail till alla noQ om feedback.
Mailar ut 2 augusti.

**Comment by overath2** [comment]
Fick ingen feedback. Flyttar till Done.
