### ISSUE TITLE
Samarbete https://soulidarityhr.com/stod-oss/

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#450]
###Beskrivning
Som en noqare behöver jag ha samarbete med partners så att vi kan växa tillsammans. 

###Acceptance Criteria
Förutsatt vi kontaktat dem
När de svarar 
Då är de intresserade av samarbete. 

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Ska bjuda in dem till referensgruppen så får vi se. @LudvigErlandsson eller @patrik-pwned som wingmate?

**Comment by LudvigErlandsson** [comment]
Jag är på som Wing mate! @overath2

**Comment by overath2** [comment]
Mailade om deltagande i referensgruppen idag.

**Comment by overath2** [comment]
Sätter denna in review. Dvs vi skiter i dom ifall de inte hör av sig.
![Image](https://github.com/user-attachments/assets/33413ac2-88c6-4c1a-adeb-a22ec38a7bdb)

**Comment by overath2** [comment]
James med i referensgruppen nu. Klar?

**Comment by LudvigErlandsson** [comment]
Snyggt @overath2 !
