### ISSUE TITLE
Ansikten på webben

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#451]
Som en besökare på vår hemsida vill jag se vilka som jobbar på noq så jag känner förtroende för oss.

AC:

- Alla som vill har sitt ansikte på https://noq.nu/om-oss/
- Alla som slutat tas bort från https://noq.nu/om-oss/

**Comment by overath2** [comment]
@dianayamout jag skrev på Slack en påminnelse till alla. Kan du starta denna ticket och slutföra den när alla har sagt ja/nej.

**Comment by dianayamout** [comment]
Hur startar man en ticket?

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Ove Holmberg (noQ) ***@***.***>
Skickat: Wednesday, July 10, 2024 5:13:40 PM
Till: noQ-sweden/noq ***@***.***>
Kopia: dianayamout ***@***.***>; Mention ***@***.***>
Ämne: Re: [noQ-sweden/noq] Ansikten på webben (Issue #451)


@dianayamout<https://github.com/dianayamout> jag skrev på Slack en påminnelse till alla. Kan du starta denna ticket och slutföra den när alla har sagt ja/nej.

**Comment by overath2** [comment]
Vi tar ett snack.  Boka mig innan 1/9.

**Comment by FannyBacklin** [comment]
@dianayamout jobbar du forfarande på denna?

**Comment by overath2** [comment]
Jag tar över denna.

**Comment by overath2** [comment]
Klart. Kan du reviewa @ChristofferEriksson-NoQ ?

**Comment by FannyBacklin** [comment]
Jag satte mig som wingmate  @Overath 

Några saker:
1. Ska de som är på paus vara med på bild eller hur tänker vi kring det? 
2. Är det möjligt att få alla bilder i samma storlek? Tänker exempelvis på att Janis, Selsabeels, Christoffer och din bild inte riktigt lirar med samma format som de andra men det kanske är svårt att få till.. 
3. Utifrån de som likeat ditt inlägg på slack med att synas på hemsidan saknas bild på Tobias och Mario

**Comment by ChristofferEriksson-NoQ** [comment]
Bara för att kort bygga på 4. av Fanny, blev fel roll för mig också. Om det kan ändras till UI/UX designer

**Comment by overath2** [comment]
Svar:

1. Ja det blir för mycket admin att ta bort
2. Ja men det behövs någon som är bra på att skala bilder först
3. Be dem maila styrelsen@noq.nu med ok att synas på hemsidan + en bra bild. (ny process)
4. Fixar

**Comment by overath2** [comment]
Demo: https://drive.google.com/file/d/16k2cuAx5_tnXB8PV_UHvpBzHvs6AaYsq/view?usp=drive_link

**Comment by FannyBacklin** [comment]
Bra förslag på att de får mejla styrelsen, jag kan lägga in det i vår onboarding-lista. 

Ny review @Overath 

1. Jag har bett de mejla bild 
2. Jag ser nu att vi blandar svenska och engelska under roller. Förslag att vi antingen väljer att använda oss av engelska eller svenska begrepp. Ex nu har vi Developer på någon och på någon annan utvecklare. Jag röstar nog för engelska men det är en smaksak!

**Comment by overath2** [comment]
1. Tack
2. Har skapat en ticket för #548 som vi behöver göra för detta

**Comment by ChristofferEriksson-NoQ** [comment]
Ser inga problem från min sida, informationen är korrekt nu. Det enda jag skulle kunna tänka mig är det som Fanny har redan nämnt.
