### ISSUE TITLE
Skapa funktion se lediga platser boende

### ISSUE THREAD

**Issue by Mrsluggan** [noQ-sweden/noq#453]
###Beskrivning
Som en handläggare vill jag se lediga platserna som finns på olika boenden

###Acceptance Criteria
- Det finns API för handläggare som skickar tillbaka listan av lediga platser i alla produkter i alla boenden handläggaren är  ansvarig för.
- Det finns tester i backend för API
- Det finns mock API i frontend
- Det finns frontend implementation som visar lediga platser för varje produkt/rum

###Subtasks

1. Utveckla backend-funktioner för att hämta information om lediga platser
2. Integrera funktionen med användargränssnittet
3. Testa funktionaliteten för att säkerställa korrekt datahämtning och visning
4. Skapa mock api för frontend
5. Skapa sida i frontend som hämtar information från backend och visar det för handläggaren
6. Skapa desing för informations sidan

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by jani-at-noq** [comment]
Ove har skapat grov skiss för framsidan för handläggare:
![image](https://github.com/user-attachments/assets/26ab2848-c051-484e-abed-3d2bf5b0f929)

**Comment by xelleze** [comment]
Waiting for the pr that fixes the caseworker api for testing. 

Det finns API för handläggare som skickar tillbaka listan av lediga platser i alla produkter i alla boenden handläggaren är ansvarig för.
Det finns tester i backend för API
Det finns mock API i frontend
Det finns frontend implementation som visar lediga platser för varje produkt/rum 

Will do a pr for this parts the sub task will be on their own pr since it will be a lot of stuff for one pr so I will split them into 2 might even split them into more pr's just for clarity and easier for reviewers. What do you think @jani-at-noq ?

**Comment by xelleze** [comment]
First pr:
Det finns API för handläggare som skickar tillbaka listan av lediga platser i alla produkter i alla boenden handläggaren är ansvarig för.
Det finns tester i backend för API

Sec pr:
Det finns mock API i frontend
Det finns frontend implementation som visar lediga platser för varje produkt/rum

and two task for each pr.

**Comment by ChristofferEriksson-NoQ** [comment]
Sätter igång med att skapa design i figma, siktar på att ha design redå för feedback innan måndag.

**Comment by jani-at-noq** [comment]
> Will do a pr for this parts the sub task will be on their own pr since it will be a lot of stuff for one pr so I will split them into 2 might even split them into more pr's just for clarity and easier for reviewers. What do you think @jani-at-noq ?

Sounds good. Always easier to review and merge small PR.

**Comment by ChristofferEriksson-NoQ** [comment]
Hejsan. Skulle vilja be om feedback för designen för 453. Den behöver fortfarande lite mer arbete utseendemässigt, men det kommer vara mindre tweaks det.
https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=3952-2084&t=6THSCE6ciFbOMOzK-1

**Comment by jani-at-noq** [comment]
> Hejsan. Skulle vilja be om feedback för designen för 453.
Jag har skrivit lite kommentarer. I övrigt ser det väldigt bra ut.

**Comment by ChristofferEriksson-NoQ** [comment]
Ny variant uppe för feedback!
https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=4170-2880&t=OWUZZYhisKLmwE0L-1
Ändringar:
Små slipat stilen för att vara uniform med resten av interfacet
Omformaterat titeln för att vara i linje med Oves specifikation
Tagit bort bild och gjort med utrymme för information
Minskat storlek på pil och tagit bort tillbaka knappen

**Comment by xelleze** [comment]
Done and mereged:
Det finns API för handläggare som skickar tillbaka listan av lediga platser i alla produkter i alla boenden handläggaren är ansvarig för.
Det finns tester i backend för API
