### ISSUE TITLE
Skapa funktion se hur många nätter brukaren har sovit

### ISSUE THREAD

**Issue by Mrsluggan** [noQ-sweden/noq#454]
###Beskrivning
Som en utvecklare behöver jag implementera funktion så handläggare kan se hur många nätter en brukare har sovit på specifkt härberge eller totalt

###Acceptance Criteria
När jag implementerar dessa operationer i backend
Då kan handläggaren se hur många nätter en brukare har sovit

###Subtasks
Utveckla backend-funktioner för att hämta information om hur många nätter **-> Done**
Integrera funktionen med användargränssnittet (rest API i backend) **-> Done**
Testa funktionaliteten för att säkerställa korrekt datahämtning och visning. Skapa automatiska tester.  **-> Ongoing **

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by tobbe-joh** [comment]
testar att försöka fixa denna, har aldrig skrivit python förut så det blir nytt. Börjar idag att kika i koden och hittade user_shelter_stay_count_view i views.py och undrar om någon redan börjat med denna eller om jag kan fortsätta härifrån. @Mrsluggan @jani-at-noq

**Comment by overath2** [comment]
Tja @tobbe-joh ! Vem är din wingmate?

**Comment by FannyBacklin** [comment]
> Tja [@tobbe-joh](https://github.com/tobbe-joh) ! Vem är din wingmate?

@xelleze Abdu är wingmate på denna!

**Comment by inhyenoq** [comment]
Design draft https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=4090-24771&t=XJtiuzNXzBwfGifl-4

**Comment by jani-at-noq** [comment]
Design looks good I think. I think it should be possible to get all bookings for all guests for tje time period and then a change to filter the list based on user or host. That would probably require a different backend API.

**Comment by jani-at-noq** [comment]
> Design draft https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=4090-24771&t=XJtiuzNXzBwfGifl-4

One comment. The list should be inside the white panel. It’s a common component on all pages.

**Comment by inhyenoq** [comment]
@jani-at-noq That's also a necessary function, I guess. The only thing I'd like to check is how much load on the system this feature will have. If it fetches the history of all guests every time this page is loaded, will our system have any trouble handling such queries?

**Comment by inhyenoq** [comment]
Jag skapade två alternativa flöden. Hur tänker ni? https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=4090-24771&t=XJtiuzNXzBwfGifl-4

**Comment by FannyBacklin** [comment]
@xelleze kikar du på denna om den här är klar? :)

**Comment by tobbe-joh** [comment]
> [@xelleze](https://github.com/xelleze) kikar du på denna om den här är klar? :)

@FannyBacklin Jag har informerat honom, så han tar det när han har tid :)

**Comment by tobbe-joh** [comment]
> [@jani-at-noq](https://github.com/jani-at-noq) That's also a necessary function, I guess. The only thing I'd like to check is how much load on the system this feature will have. If it fetches the history of all guests every time this page is loaded, will our system have any trouble handling such queries?

@inhyenoq Jag kan försöka minska datan som hämtas vid ett api anrop och lägga till paginering till funktionen? det kanske gör lite skillnad när det börjar bli långa listor som hämtas. @jani-at-noq använder vi någon typ av caching?

**Comment by overath2** [comment]
Status @AbubakerSalah ?

**Comment by overath2** [comment]
Gör reopen eftersom oklart om den är klar.

**Comment by jani-at-noq** [comment]
Inte klart. Backend ok, frontend inte.
