### ISSUE TITLE
Uppdatera design för överblick komponent

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#459]
###Beskrivning
Som en härbärge behöver jag ha snabb överblick för bokningar så att jag känner till hur mycket lediga platser och brukare vi har.

###Acceptance Criteria
Förutsatt att härbärge användare har loggat in
När hen öppnar appen
Då ser hen överblick för dagens bokningar

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Denna uppfyller inte våra krav i Playbook för tickets i Github. Läs mer här: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.cg0m06jyj586
Jag sätter den i korrekt status. När åtgärdat flytta tillbaka denna.
/o

**Comment by overath2** [comment]
@jani-at-noq har du någon wingmate?

**Comment by natischmidt** [comment]
yes, jag är det nu

**Comment by overath2** [comment]
Nästan. Fältet saknas ;)

**Comment by natischmidt** [comment]
Appen tycker inte om mig just nu, har försökt byta värde till mitt namn... lägger till det senare

**Comment by jani-at-noq** [comment]
Jag kunde ändra wingmate, så det är uppdaterad nu.

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @jani-at-noq ?

**Comment by jani-at-noq** [comment]
Ja. Blir klar innan sista augusti.
