### ISSUE TITLE
Uppdatera backend API för hämtning av överblick information

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#461]
###Beskrivning
Som en härbärge behöver jag kunna hämta information från backend som kan visas i appen för överblick av bokningar.

###Acceptance Criteria
Förutsatt att härbärge användare har loggat in
När hen öppnar appen
Då ser hen överblick för dagens bokningar som hämtas från backend

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
@jani-at-noq kan du ta denna?

**Comment by overath2** [comment]
Ping @Ovura-noq . Får vi denna klar?

**Comment by natischmidt** [comment]
Det finns en PR, väntar på feedback etc
