### ISSUE TITLE
Miljöer - Test av userflows i Demomiljö

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#462]
###Beskrivning
Som en utvecklare behöver jag verifiera att användarflödena för olika roller
(gäst, handläggare, boende/härbärge) fungerar korrekt i demomiljön.

###Acceptance Criteria
Förutsatt att användarrollerna är korrekt konfigurerade,
När jag loggar in som olika användare, 
Då kan jag se och använda de funktioner som är specifika för varje användare (gäst/boende/handläggare).

###Subtasks
**•	Gästens  inlogg och flöde =**
1) från login till att visa dashboard.
2) Där ska brukare/gäst kunna se en överblick över det viktigaste  (lediga sovplatser mm).
3) Sedan skall denna kunna reservera en sovplats.
#464 

**•	Handläggarens inlogg och flöde =** 
1) från login till att visa dashboard.
2) Där ska handläggare på socialtjänsten kunna se en överblick över det viktigaste (lediga sovplatser, bokningar, utcheckningar, risker (se epic Riskbedömning) mm).
3) Sedan skall denna kunna reservera en sovplats.
#466 

**•	Boendets/Härbärgets inlogg och flödet**
1) från login till att visa dashboard.
2) Där ska en admin på boendet kunna se en överblick över det viktigaste (lediga sovplatser, bokningar, utcheckningar, risker (se epic Riskbedömning) mm).
3) Sedan skall denna kunna godkänna/avslå en reservation av sovplats.
#465 

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @xelleze ?

**Comment by jani-at-noq** [comment]
Jag tror vi behöver beskriva flöde i lite mer detaljer för varje användare. Vad exact ska olika användare kunna göra efter dom har loggat in?

**Comment by jani-at-noq** [comment]
Eller är detta story för test?

**Comment by overath2** [comment]
Jag vill att rollerna ovan kan logga in och komma till en relevant startsida där man ser en överblick/dashboard över möjligheter som tex boka som är steget efter dashboarden.

Tänkbara möjligheter:

- Brukare - boka sovplats
- Handläggare - se nuvarande beläggning på alla härbärgen
- Härbärge - godkänna bokning, checka in, checka ut.

**Comment by overath2** [comment]
Ping @xelleze . Kan du fixa en wingmate till denna?

**Comment by overath2** [comment]
Denna kan vara till hjälp: https://drive.google.com/file/d/1RoxWE7l4q76xEkkvDyiEC9bVVeGSMF7J/view?usp=sharing

**Comment by overath2** [comment]
Kan du kolla denna @FannyBacklin?

**Comment by xelleze** [comment]
En litten fråga vilka user är klara för att testas ?

**Comment by jani-at-noq** [comment]
Samma som är listade i frontend repo

su 18.8.2024 klo 17.54 Abdulmsih Nashef ***@***.***>
kirjoitti:

**Comment by xelleze** [comment]
Så dessa twå User:
email: user.user@test.nu 
Password: P4ssw0rd_for_Te5t+User

Host:
email: user.host@test.nu
Password: P4ssw0rd_for_Te5t+User ?

**Comment by jani-at-noq** [comment]
Ja, ett är användare ett host.

su 18.8.2024 klo 19.14 Abdulmsih Nashef ***@***.***>
kirjoitti:

**Comment by xelleze** [comment]
När jag försöker att testa det så kan man logga in men sen så finns det inget efter man har loggat in är det intended ?

**Comment by jani-at-noq** [comment]
Ja, så är det idag. Det är mycket funktionalitet som saknas. Brukare har
ingen kontent. Host har lite, men förfrågningar till exempel är tom för det
kommer inte in nya bokningar.

Vi har att göra.

Jag har föreslagit att vi ska fokusera på bokking use case för alla
användare grupoer så vi har ett use case som funkar helt och kan demas.

ma 19.8.2024 klo 9.45 Abdulmsih Nashef ***@***.***> kirjoitti:

**Comment by xelleze** [comment]
För host så fungerar:
Förfrågningar sidan som det ska. 
Bostället sidan fungerar som det ska, men button färgen är Blue-green med svarft text svårt att se 

Allt annat ser inte klart ut, för tillfället så är detta en test jag kan göra.

**Comment by jani-at-noq** [comment]
Ta bild på skärmen och posta i demo kanal. Det är jätte bra vi får in alla
observationer från våra tester.

ma 19.8.2024 klo 9.52 Abdulmsih Nashef ***@***.***> kirjoitti:

**Comment by jani-at-noq** [comment]
Nu ser jag att mina svar via mail ser ut så där. Kommer undvika att göra det i framtiden :-)

**Comment by overath2** [comment]
Har uppdaterat acceptanskriteria ovan. Detta är flödet vi kommer dema den 10 oktober.

**Comment by overath2** [comment]
Jag har dessutom skapat tre users om vi kan använda dessa istället?

1. Host/Härbärge: frida-harbarge@noq.nu pw: noQFrida
2. Gäst/Brukare: lena-brukare@noq.nu pw: noQLena99
3. Handläggare på socialtjänsten: pelle-handlaggare@noq.nu pw: noQPelle

**Comment by overath2** [comment]
Film: https://drive.google.com/file/d/1qgoECBZ3FidaGMmDU-AU1EO_M5kkR0-6/view?usp=drive_link

**Comment by overath2** [comment]
ps. Saknas wingmate

**Comment by overath2** [comment]
Kan vi flytta denna till något team som inte är Sommar?

**Comment by xelleze** [comment]
Måste inte funktionerna som vi vill testa vara färdiga för att kunna slutföra tasken.  Jag tror att vi kan skriva om tasken till Continues testing där vi hella tiden testar nya funkionerna som blir merged till main project vad tycker du @overath2, @jani-at-noq, @natischmidt

**Comment by overath2** [comment]
Vi behöver sätta ett datum då denna ska vara klar. Om den inte är klar måste vi ställa in demon 10/10.
Jag säger senast 2/10?

**Comment by overath2** [comment]
Ping @natischmidt . Vad händer här?

**Comment by natischmidt** [comment]
@overath2 det jag vet är att rasmus jobbar med subtasks till denna

**Comment by overath2** [comment]
Denna är in progress va? Och helst klar imorgon. Ping @jani-at-noq och @xelleze
