### ISSUE TITLE
Miljöer - Skapa *User Roles*

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#463]
###Beskrivning
Som en utvecklare behöver jag skapa/hantera olika användare
så att vi kan simulera olika användarflöden i demon.

###Acceptance Criteria
Förutsatt att användarroller är konfigurerade*
, När en användare loggar in, 
Då tilldelas de korrekt roll och rättigheter baserat på deras roll.

###Subtasks
•	Testa användarinloggning med olika roller.

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by natischmidt** [comment]
*konfigurerade - Här menas att vi ska ha 3 olika fasta inlogg för varje använderoll. dvs om någon av dem ska kolla på demomiljö ska dem får ett testinlogg och använda det. Dessa kan vi skapa/ta bort regelbundet, t.ex en inlogg funkar i en vecka så dem kan testa.

**Comment by overath2** [comment]
Hur går det med denna @natischmidt ?

**Comment by overath2** [comment]
Ping @natischmidt

**Comment by natischmidt** [comment]
den är inprogess

**Comment by jani-at-noq** [comment]
> Jag har skapat tre login med noq-mail. Använd dessa please.

Var kan jag hitta dom?

**Comment by overath2** [comment]
Se mail

**Comment by overath2** [comment]
Mail till @jani-at-noq alltså.

**Comment by overath2** [comment]
Och @natischmidt har också admin till Google worlspace och kan fixa usrar att använda.

**Comment by overath2** [comment]
Ping @elajth och @natischmidt . Kan en av er ta denna? Den andra som wingmate?

**Comment by elajth** [comment]
Kollar med @natischmidt på Slack om det är nåt jag kan hjälpa till med

**Comment by jani-at-noq** [comment]
Backend APIs är tillgängliga baserad på användarroll, samt routes i frontend (se App.jsx), så det som är kvar är att testa. Det finns automatiserade tester för backend API, men ingenting för frontend.

**Comment by jani-at-noq** [comment]
Jag har lagt till dom tre användare i vårt demomiljö.

**Comment by overath2** [comment]
Kan du dokumentera detta någonstans och sedan dra till In Review så ska jag kolla.

**Comment by jani-at-noq** [comment]
Vad menar du med dokumentera? Vad ska dokumenteras och i vilken format?

**Comment by overath2** [comment]
Så det finns nedskrivet någonstans hur man gör tex när vi ska testa. Loginuppgifter mm.

**Comment by overath2** [comment]
Kan vi stänga denna?

**Comment by elajth** [comment]
Jag tror vi kan stänga den ja @overath2
