### ISSUE TITLE
Logga in som gäst och testa flöden

### ISSUE THREAD

**Issue by RasmusOUX** [noQ-sweden/noq#464]
###Beskrivning
För att säkerställa att alla funktioner som brukaren ska kunna använda fungerar som de ska fungera och att de flödet fungerar som det ska göra. Resultatet av detta ska dokumenteras.

###Acceptance Criteria
Om man är inloggad som brukare så kan man genomföra de aktiviteter som brukare ska kunna genomföra i den ordningen som de ska genomföras.

###Subtasks
• Skapa tester baserat på brukares flöde. 

###Definition of Done
OK from wingmate
Documented
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Jag är gärna med och testar och sätter mig som wingmate. Hojta när den ska börja.

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @RasmusOUX ?

**Comment by overath2** [comment]
Kan du kolla denna @FannyBacklin ?

**Comment by overath2** [comment]
@RasmusOUX kan du ta denna?

**Comment by FannyBacklin** [comment]
Vem tar över den här storyn under din tid på paus @RasmusOUX @callekrook?

**Comment by overath2** [comment]
Flyttar till sprint 10.

**Comment by overath2** [comment]
Jag flyttar denna till klar.
