### ISSUE TITLE
Logga in som härbärge  och testa flöden

### ISSUE THREAD

**Issue by RasmusOUX** [noQ-sweden/noq#465]
###Beskrivning
För att säkerställa att alla funktioner som härbärget ska kunna använda fungerar som de ska fungera och att de flödet fungerar som det ska göra. Resultatet av detta ska dokumenteras.

###Acceptance Criteria
Om man är inloggad som härbärget så kan man genomföra de aktiviteter som härbärget ska kunna genomföra i den ordningen som det ska genomföras.

###Subtasks
• Skapa tester baserat på härbergets flöde.

###Definition of Done
OK from wingmate
Documented
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Jag är gärna med och testar och sätter mig som wingmate. Hojta när den ska börja.

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @RasmusOUX ?

**Comment by SelsabeelA** [comment]
Demolänk: https://drive.google.com/file/d/1Ddr7TukjASN-53pVukgaCQSX8ErC6eLc/view?usp=drive_link
