### ISSUE TITLE
Skapa testdokumentation

### ISSUE THREAD

**Issue by RasmusOUX** [noQ-sweden/noq#467]
###Beskrivning
Som en utvecklare behöver jag ha dokumentation så att jag vet hur systemet har betett sig tidigare.  Detta för att kunna jämföra för t.ex. regressionstester.

###Acceptance Criteria
Test dokumentation finns tillgänglig i någon form. 
Use-Cases är skapade

###Subtasks
• 

###Definition of Done
OK from wingmate
Documented
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Saknar guesstimat

**Comment by RasmusOUX** [comment]
> Saknar guesstimat

Fixat

**Comment by FannyBacklin** [comment]
@RasmusOUX Reviewar du den här under nästa vecka? :)

**Comment by RasmusOUX** [comment]
Har ändrat och Use-Cases skapas som en del av testdokumentationen. Testerna i detta fall är E2E.
Har demats av Jani 29/6
