### ISSUE TITLE
Kalender fix

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#469]
Som en noQare vill jag ha koll på alla våra gemensamma kalenderhändelser så att jag kan närvara på dessa utan strul

AC

- En gemensam Googlekalender som man kan se och uppdatera när man använder sitt noQ konto.
- När jag loggar in i ett möte så slipper jag vänta på insläpp i lobbyn
- Möjlighet för alla (även de som inte skapat mötet) att spela in mötet (detta är nice-to-have)
- När jag kallar till ett möte som inte är regelbundet (ex Scrum-möten) så får alla inbjudna detta i sin egen noQ kalender.
- Alla kan prenumerera på den gemensamma kalendern så den syns i sin privata kalender.
- Alla i noQ har gjort tumme upp på att man kan detta ovan.
- Instruktioner i Playbook uppdaterade

Se även buggar #436 och #437

**Comment by inhyenoq** [comment]
@overath2 Det här är svar. Komma till baka om något jag förstod inte. Annas alla har klart.

> - En gemensam Googlekalender som man kan se och uppdatera när man använder sitt noQ konto.
- Vi har den här gemensam kalendern: https://calendar.google.com/calendar/embed?src=c_7d4de8338a7cada36ed65a424a34cd0550293c642c34d2d998327b3d71e5cfa7%40group.calendar.google.com&ctz=Europe%2FStockholm
- Kolla instruktioner i Playbook: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.87rgirxwcuvy

> - När jag loggar in i ett möte så slipper jag vänta på insläpp i lobbyn
- The default meeting setting has been changed to allow joining a meeting without permission. This will apply every participant including those not noQ members. 
- Note that individual meeting organiser still can change this setting to wait invitees to wait for permission.

> - Möjlighet för alla (även de som inte skapat mötet) att spela in mötet (detta är nice-to-have)
- Tyvärr kan vi inte spela in mötet med Google feature eftersom det inte ingår i vår prenumeration (Google Workspace for Nonprofits). Kolla den här länken: https://support.google.com/a/answer/7557052?hl=sv#:~:text=L%C3%A4rare%20kan%20spela%20in%20m%C3%B6ten,m%C3%B6te%20f%C3%B6r%20n%C3%A5gra%20m%C3%A5nader%20sedan.

> - När jag kallar till ett möte som inte är regelbundet (ex Scrum-möten) så får alla inbjudna detta i sin egen noQ kalender.
- När du sätter ett möte i en kalender men inbjuda ingen ska mötet vara i den här kalender. 
- Dock alla noQarer kan se mötet i gemensam kalendern när du kallar till ett möte i där fastän du lägg ingen gäster. 
- Om du behöver att inbjuda och få alla noQarer detta i sin egen noQ kalender vill du lägg **alla@noq.nu** til gäster.
- Kolla en kort video om vår kalender här: https://youtu.be/MzoSCkBh54g?feature=shared

> - Alla kan prenumerera på den gemensamma kalendern så den syns i sin privata kalender.
- Det är redan möjligt.

**Comment by inhyenoq** [comment]
> - När jag loggar in i ett möte så slipper jag vänta på insläpp i lobbyn

The changed default meeting setting will apply when setting a new meeting.
Remember to change this setting for existing meetings if needed.

https://github.com/user-attachments/assets/5f07089b-9088-42b4-8034-2b2f4f216ebd

**Comment by overath2** [comment]
Great. It works. Can we save this to faq?

**Comment by overath2** [comment]
Vem är wingmate och kan testa?

**Comment by inhyenoq** [comment]
@kingli6 Kan du blir wingmate och testa?

**Comment by inhyenoq** [comment]
@natischmidt  Kan du blir wingmate och testa?

**Comment by natischmidt** [comment]
Ok!

**Comment by FannyBacklin** [comment]
@inhyenoq Uppdateras mejlslingan alla@noq.nu automtiskt när vi har nya som börjar och som slutar eller måste det läggas till manuellt?

**Comment by inhyenoq** [comment]
@FannyBacklin alla aktiva mejl är alla@noq.nu automtiskt!

**Comment by FannyBacklin** [comment]
@natischmidt ping!
