### ISSUE TITLE
Uppdatera utseende för förfrågningssida

### ISSUE THREAD

**Issue by SelsabeelA** [noQ-sweden/noq#472]
###Beskrivning
Som en utvecklare behöver jag uppdatera utseende för förfrågningssidan enligt design i Figma för att skapa bättre användarupplevelse.

noQ appen ska se ut så här:
https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=2749-1009&t=zShcQJn1zaykJeyc-4

###Acceptance Criteria
noQ fröfrågningssida uppdaterad med ny utseende

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Denna uppfyller inte våra krav i Playbook för tickets i Github. Läs mer här: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.cg0m06jyj586
Jag sätter den i korrekt status. När åtgärdat flytta tillbaka denna.
/o

**Comment by overath2** [comment]
@jani-at-noq kan du plocka denna sedan med mig som wingmate?

**Comment by SelsabeelA** [comment]
Den var ungefär 70% klar, men utseendet behöver fortfarande fixas. Jag är inte säker på om det skulle vara lättare att börja om eller fortsätta från min egen branch, men jag kan lägga det jag gjorde i en ny branch om det behövs.

Här är hur den ser ut:

![Image](https://github.com/user-attachments/assets/f5207aa5-bdd1-457a-8a8b-13cb54dd5073)

**Comment by overath2** [comment]
Hur ser du på denna @jani-at-noq ?

**Comment by jani-at-noq** [comment]
Jag ska leverera saker som är in progress och sen kan jag dra detta. Om någon annan är ledigt och sugen på att jobba med frontend är det helt ok om nån annan tar detta.

**Comment by overath2** [comment]
@FannyBacklin kan du kika på denna?

**Comment by jani-at-noq** [comment]
Jag har börjat jobba på detta. Kommer föreslå lite ändringar till bilder i figma som första steg. Bokningsprocess har många steg, så vi borde visualisera dom på något sätt tänker jag.

**Comment by overath2** [comment]
vem är wingmate?

**Comment by FannyBacklin** [comment]
@SelsabeelA Kan du vara wingmate för denna?

**Comment by SelsabeelA** [comment]
Ja det kan jag vara

**Comment by jani-at-noq** [comment]
Vi kan stänga detta. Jag har uppdaterad för handläggare, och det är samma fil man delar med härbärge och handläggare. Jag stänger detta ticket.
