### ISSUE TITLE
Add new APIs for Backend to fetch information needed in the host frontpage

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#477]
###Beskrivning
Som en härbärge behöver jag ha snabb överblick för bokningar så att jag känner till hur mycket lediga platser och brukare vi har.

###Acceptance Criteria
Förutsatt att härbärge användare har loggat in
När hen öppnar appen
 Då ser hen överblick för dagens bokningar

###Subtasks
- Create API to get host information
- Create API to get available places for each product for the host in a date range

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Hej @jani-at-noq ! Jag är redo för review. Kan du fixa en demo (film?) först?
Och länka här i ticketen till det jag kan reviewa?
/o

**Comment by jani-at-noq** [comment]
Hejsan,

Här är PR: https://github.com/noQ-sweden/noq_backend_python/pull/33

/Jani

Den sön 7 juli 2024 kl 21:55 skrev Ove Holmberg (noQ) <
***@***.***>:

**Comment by FannyBacklin** [comment]
@overath2  hinner du kika på den här idag? Tänker ifall det är något du behöver synka med Jani för han går på semester nästa vecka :)
