### ISSUE TITLE
Backend: count_bookings returns wrong value for available places

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#478]
Function count_bookings (api/host/count_bookings) returns wrong value for available places (available_products.

**Comment by overath2** [comment]
Hur går det med denna @jani-at-noq ?

**Comment by jani-at-noq** [comment]
Detta blir löst med ändringar jag har gjort i PR#43. Ticket 501. Ingen kod leverans för detta ticket, så vi kan sätta det som duplikat eller reject.

**Comment by jani-at-noq** [comment]
Eller Done efter #43 är inne.
