### ISSUE TITLE
BUG: Man kan inte lägga till ny host utan att fylla in blocked clients.

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#482]
När man försöker lägag till nya host i Django admin sidan går det inte om man inte väljer Blocked clients. Orimligt krav för ny Host. Se bilden för mer detaljer.

![Image](https://github.com/user-attachments/assets/fc073f97-51dc-4243-a6e9-397262836273)

**Comment by overath2** [comment]
Hur går det med denna @jani-at-noq ?

**Comment by jani-at-noq** [comment]
Det är i backlog. Inte kritisk just nu så ingen progress.
