### ISSUE TITLE
BUG: Kan inte skapa client i django admin

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#483]
Det går inte att skapa client i Django admin. Client kräver koppling till "user id". Men det finns ingen fält för att välja användare (se bilden). När man trycker på "SPARA" får man följande felmeddelande:

NOT NULL constraint failed: client.user_id
Request Method: | POST
http://127.0.0.1:8000/admin/backend/client/add/
4.2.10
IntegrityError
NOT NULL constraint failed: client.user_id

![Image](https://github.com/user-attachments/assets/ee968be6-6bf5-4b22-87b8-425abd53b9ee)

**Comment by overath2** [comment]
Hur går det med denna @jani-at-noq?

**Comment by overath2** [comment]
Hur går det med denna @jani-at-noq?

**Comment by jani-at-noq** [comment]
Jag flyttar detta till Saturnus. Vi ska handläggare ska hantera kunder. Assignar till mig också.

**Comment by jani-at-noq** [comment]
Detta var jätte liten ändring. I granskning nu.
