### ISSUE TITLE
Deploy noq application as docker images

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#485]
###Beskrivning
Som utvecklare vill jag leverera noq web applikation på webserver så det blir tillgängligt för användare. För detta vill jag skapa container images som kan utplaceras i webtjänst som aws.

###Acceptance Criteria
- Skapa image för noq webapplikation
- Image ska innehålla: Webserver nginx, wsgi server uwsgi, postgresql db, noq backend och noq frontend
- Image har blivit utplacerad i webtjänst och den är tillgängligt för almänheten.
- Process and details for the environment variables are documented in the noq intranet

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by tobbe-joh** [comment]
Har du lyckats med denna: Image har blivit utplacerad i webtjänst och den är tillgängligt för almänheten. ? antar det går att stänga denna då.

**Comment by overath2** [comment]
Om OK @jani-at-noq dra till review så får @tobbe-joh dra till done.

**Comment by jani-at-noq** [comment]
Noq sidan är inte tillgängligt i server än, så vi kan inte stänga. Jag hoppas vi kommer vara klara med detta till 4:e augusti. Borde inte ta lång tid när jag har mögligheten att jobba med ticket igen (onsdag 31:a juli).

**Comment by overath2** [comment]
Blir denna klar till 10 oktober @jani-at-noq ?

**Comment by jani-at-noq** [comment]
Ja, detta kommer vara klart till slutet av nästa vecka tänker jag. Vi har docker filer på plats och har dom körande på server just nu. Vi behöver uppdatera dokumentation och testa lite mer, men annans är vi klara. Tänkte spela in demo under helgen.

**Comment by tobbe-joh** [comment]
När alla är klar med review och det är mergat, ska jag då dra över till done

**Comment by jani-at-noq** [comment]
Ja, när alla delar är ok och merged är det klart. Frontend och backend. Jag
tänker att vi ger tills onsdag för gransknings kommentarer och mergar sen
om det inte finns nånting att fixa.

ma 12.8.2024 klo 15.42 Tobias Johansson ***@***.***>
kirjoitti:
