### ISSUE TITLE
Merch 

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#491]
###Beskrivning
Som en medlem behöver jag ha merch så att jag känner vi känsla. 

###Acceptance Criteria
Förutsatt vi har minst 10 medlemmar 
När vi fått betalt medlemsavgifterna
Då kan vi sända ut merch till dessa

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Heja. Ta gärna fram en prototyp vi kan diskutera. Vill gärna ha slogan under loggan.

**Comment by ChristofferEriksson-NoQ** [comment]
![IMG_3550](https://github.com/user-attachments/assets/691456d2-5413-4eb5-b38f-f28d2e5298c5)
Skapade ett test snitt som jag visade upp på Slack förra veckan av transfer vinyl som kan pressas på kläder för ett permanent tryck. Dessvärre är heattransferpressen jag hade åtkomst till under reparation, men det ska vara möjligt att utföra en transfer med ett väldigt varmt strykjärn. Detta är något som jag ska testa och ha redo för nästa demo.

**Comment by ChristofferEriksson-NoQ** [comment]
Copy paste from slack: Utfört ett test tryck på en gammal sliten levis tshirt (ni ser lite av liggan bakom Q'et). Det är fullt möjligt att utföra trycket med ett strykjärn, men det är svårt att få en snygg finish. Syns ej på foto, men det blir en aningen prickig finish på trycket i vissa områden, jag antar det är pga ojämn värme fördelning. Men heat transfer pressen verkar vara under reparation nu hos Makerspace, så det kan bli ett alternativ. 
![IMG_3729](https://github.com/user-attachments/assets/9cac97ee-a161-437b-abd8-14c3e188eab7)

**Comment by overath2** [comment]
Avvakta att pressen blir klar samt vi får en slogan under. Vore najs att ha klart till 10 oktober dock.

**Comment by ChristofferEriksson-NoQ** [comment]
Uppdaterar med information från Slack:
Vi har nu tillgång till en fungerande heat transfer vilket ger nu snygga tryck på tröjor! Det enda som kvarstår är våran slogan, därefter är merch redo för produktion.

För Ove, här är ett par tider då jag kan ta möte i veckan:
Tisdag: 10-12, 17-19
Onsdag: 10-14
Torsdag: 9-12
Fredag: 10-11, 17-19

**Comment by overath2** [comment]
OK, jag kallar till något samt lägger in länk till beroendet: #492

**Comment by overath2** [comment]
Skickat till torsdag 09:00

**Comment by ChristofferEriksson-NoQ** [comment]
Skriver information från slack här! T-shirts är nu tillgängliga för noQ medlemmar som vill ha de. Ni kan lämna information om vilken storlek och färg kombination ni vill ha på tröjan här i formuläret : https://forms.gle/rtfXW9E2tbSn2RPM6. Eftersom vi inte har ännu en automatiserad process får ni kontakta mig på slack för hur ni vill ha det levrat + avgifter för att skapa tröjan (framtida plan är att detta ingår i avgiften för medlemmar).
Den kommande onsdagen (9/10) så kommer vi ha en afterwork, för de som bor i Stockholms området och lägger in en beställning för en tröja så kan jag leverera de direkt till er där.

**Comment by overath2** [comment]
Klar!
