### ISSUE TITLE
Slogan

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#492]
###Beskrivning
Som en noQare behöver jag ha slogan så att folk förstår varför vi finns till

###Acceptance Criteria

1. Förutsatt jag surfar till vår hemsida;
När jag tittar bredvid vår logga i headern;
Då ser jag vår nya slogan som består av max tre ord.

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
@FannyBacklin gör röstning och levererar resultatet kl 15 på fredag till @ChristofferEriksson-NoQ

**Comment by overath2** [comment]
@FannyBacklin kan du dra till done?

**Comment by FannyBacklin** [comment]
@overath2  ser inte vår slogan på hemsidan, vart finns den inlagd?

**Comment by overath2** [comment]
Kolla med @djigna och @Ovura-noq om de kan lägga in den på något bra ställe?

**Comment by overath2** [comment]
Klar va @FannyBacklin ?

**Comment by FannyBacklin** [comment]
@overath2 Hmm kan fortfarande inte hitta vår slogan på hemsidan. Kan ni hjälpa mig att få upp den på hemsidan @djigna @Ovura-noq? :D

**Comment by overath2** [comment]
![image](https://github.com/user-attachments/assets/e68b1f8b-160d-4081-8257-ad25bda4d1d0)

**Comment by FannyBacklin** [comment]
Hahaha oj rakt framför näsan! Letade överallt men inte just där 👯 @overath2
