### ISSUE TITLE
BUG: Proxy is not routing request directly when accessing react path

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#495]
On the production server when I type in address http://serveraddresss/host/ to get directly into the host page, server should redirect me to login page. In the current set-up I get 404 error message.

**Comment by natischmidt** [comment]
I dont get it

**Comment by natischmidt** [comment]
Elaborate pls

**Comment by jani-at-noq** [comment]
Jag försöker förklara bättre. Tanken är att om användare sätter bookmark till noq.app.nu/host/request ska man komma till rätt sida i appen. Först får man login sidan (se bild 2) och sen får man rätt kontent. I vår public server funkar inte detta. Istället får man 404 server error när man försöker gå till nån annan länk än server address.

I vår publik server instance:
![image](https://github.com/user-attachments/assets/bfd72ab4-6aa7-48f6-b064-fd61f98338a7)

Det ska funka så här:
![image](https://github.com/user-attachments/assets/e247f3d1-9a6d-4bb5-921c-87d34cb9c2ba)
