### ISSUE TITLE
Hur man gör en demo

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#497]
Som en noQare vill jag veta hur jag gör en film så vi alla gör på samma sätt när vi gör en demo eller beskrivning av en epic.

AC:

- Playbook uppdaterad
- Film som beskriver processen

**Comment by jani-at-noq** [comment]
Jag undrar om det behövs film för demo? Om filmen ska vara för användning av olika verktyg är det mycket bättre att lita på Youtube. Playbook update med länkar till instruktioner borde räcka tänker jag.

**Comment by overath2** [comment]
Menar du film för demo genrellt eller film för denna demo?
Låt oss höras i september. Jag blir wingmate.

**Comment by jani-at-noq** [comment]
AC är Playbook uppdaterad & **Film som beskriver processen**. Så jag undrar vilken process ska man beskriva i videon.
- Hur man använder verktyg? (Youtube är bättre)
- När man ska göra demo och vad det ska innehålla?

Jag kommer spela in demo för själva github ticket, men AC del 2 är lite oklart för mig.
