### ISSUE TITLE
Vulnerability alerts

### ISSUE THREAD

**Issue by tobbe-joh** [noQ-sweden/noq#498]
## To be fixed ##
inside repo: noq-frontend

### Server-Side Request Forgery in axios
 - axios 1.7.2 allows SSRF via unexpected behavior where requests for path relative URLs get processed as protocol 
   relative URLs.
- Affected versions: >= 1.3.2, <= 1.7.3

### Uncontrolled resource consumption in braces
  - The NPM package braces fails to limit the number of characters it can handle, which could lead to Memory 
    Exhaustion. In lib/parse.js, if a malicious user sends "imbalanced braces" as input, the parsing will enter a loop, 
    which will cause the program to start allocating heap memory without freeing it at any moment of the loop. 
    Eventually, the JavaScript heap limit is reached, and the program will crash.
-  Upgrade braces to a later version.

# DoD #
-  verifiera att inga brytande förändringar påverkar funktionaliteten.
- Kör "npm audit" i terminalen i noq-frontend: Kontrollera att alla sårbarheter verkligen blev lösta.
- Bygg applikationen: Se till att applikationen byggs korrekt utan fel

**Comment by overath2** [comment]
Hur går det @tobbe-joh ?

**Comment by tobbe-joh** [comment]
jag ska se hur det går för min wingmate! @overath2

**Comment by jani-at-noq** [comment]
Jag har grankat och mergat patchen. Mario kan inte göra review i github än. Jag sätter detta till Done.
