### ISSUE TITLE
Lint errors in frontend

### ISSUE THREAD

**Issue by tobbe-joh** [noQ-sweden/noq#499]
###Syfte
För att adressera det stora antalet lint-fel vi stöter på varje gång vi kör lint-tester, har jag tänkt att migrera från JSX till TSX. Denna migrering syftar till att dra nytta av TypeScript
typkontroller och förbättra kodens robusthet. Genom att använda TSX kan vi få mer exakt typkontroll och därmed minska antalet lint-fel och andra problem relaterade till typning.

###Acceptance Criteria
- Lint-fel som "is missing in props validation" ska vara åtgärdade och inte längre förekomma.

###Subtasks
- Kör npm run lint och dubbelkolla att inga relevanta lint-fel kvarstår.
- Bygg appen och testa med både mock-data och verklig data för att säkerställa att migreringen inte har 
   introducerat några regressionsfel.

###Definition of Done
 OK from wingmate
Code checked in
Inga kvarstående lint-fel relaterade till props validation.
Appen fungerar som förväntat med både mock-data och verklig data.

**Comment by jani-at-noq** [comment]
Vi kan väl stänga detta? Frontend lint testerna är gröna nu.

**Comment by overath2** [comment]
Saknas wingmate för att stänga.

**Comment by overath2** [comment]
Ping @tobbe-joh . Vad händer här?

**Comment by overath2** [comment]
Ping @tobbe-joh . Ska vi ta med den i sprint 9?

**Comment by tobbe-joh** [comment]
> Ping [@tobbe-joh](https://github.com/tobbe-joh) . Ska vi ta med den i sprint 9?

har kollat, någon annan fixade upp i en annan issue/task. Jag stänger nu denna.
