### ISSUE TITLE
BUG: Internal Server Error when Deleting Product

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#500]
We get internal server error when Product is deleted and there is bookings for the product. This is what happens.
1. Product is deleted
2. As Booking has Product as Foreign key with on_delete.CASCADE policy bookings are deleted
3. When Booking is deleted it will try to update availability before being deleted. Available model has also Product as foreign key with on_delete.CASCADE policy.
4. This leads to some conflicts and it's not possible to delete Available and Booking for the Product

How to solve.
One alternative is to add pre_delete signal for Product and remove the bookings and availability information before the Product is deleted.

This bug is not high prio as we probably don't want to allow Product deletions in the production environment so we don't loose important data about bookings. But when we do testing and fill and delete data in staging server for example we might want to remove old data time to time.

**Comment by FannyBacklin** [comment]
@Ovura-noq hur går det för dig med denna ticket? :)

**Comment by natischmidt** [comment]
Status?

**Comment by FannyBacklin** [comment]
@natischmidt reviewar du den här? Eller har ni någon ny wingmate? :)

**Comment by natischmidt** [comment]
ahmad assigne, jag är wing
