### ISSUE TITLE
UX rekrytering

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#505]
Vi behöver bli 2-3 fler på UX. En rekryteringssväng.

**Comment by overath2** [comment]
Kan du hänga på som wingmate @FannyBacklin ?

**Comment by FannyBacklin** [comment]
Japp, jag kan ta ett varv och kolla mina kontakter på gamla skolan om de har några UX:are!

**Comment by FannyBacklin** [comment]
Kontaktat 2 UX:are för att se om de kan hoppa in, avvaktar tills jag fått svar annars fortsätter jag att jaga @overath2
