### ISSUE TITLE
Skapa funktionalitet, godkänn/neka bokning - handläggare

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#516]
###Beskrivning
Som en handläggare vill jag kunna godkänna eller neka bokning som användaren har gjort.

###Acceptance Criteria
- Det finns API för handläggare som ändrar bokning status från pending till accepted.
- Det finns tester i backend för API
- Det finns mock API i frontend
- Det finns frontend implementation som visar bokningar och låter handläggaren godkänna eller neka dom

###Subtasks
- Utveckla backend-funktioner för att ändra status för bokning **-> Done**
- Integrera funktionen med användargränssnittet **-> Done**
- Testa funktionaliteten för att säkerställa korrekt datahämtning och visning **-> Done**
- Skapa mock api för frontend **-> Ready for review**
- Skapa sida i frontend som hämtar information om bokningar och låter handläggaren att godkänna/neka bokningar **-> Ready for review**
- Skapa design för sidan som hanterar bokningar **-> Done**

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by jani-at-noq** [comment]
Ove har skapat grov skiss för första sidan för handläggare:
![image](https://github.com/user-attachments/assets/ef340c93-c3e7-4fa2-b247-5e870a83717e)

**Comment by jani-at-noq** [comment]
Backend delar är nu inne i main. Frontend kvar.

**Comment by overath2** [comment]
Snyggt jobbat @jani-at-noq. Ser fram emot att vi nu kan neka/godkänna i flödet. Heja!

**Comment by ChristofferEriksson-NoQ** [comment]
Design redo, har skrivit lista med skillnader mot nuvarande implementerad design i Slack.
https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=3900-1788&t=HpyhDEZN4N7a50QE-1

**Comment by overath2** [comment]
Kommentarer i Figman

**Comment by ChristofferEriksson-NoQ** [comment]
Gjort ändringar enligt feedback och flyttat frame med kommentarer till work in progress sidan.

**Comment by ChristofferEriksson-NoQ** [comment]
Nya förslag -> https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=3905-2648&t=HpyhDEZN4N7a50QE-1
Ändrat namn formatet på sidan och tagit bort den självstående Boknings rubriken.
Lagt till en tilldela alla knapp (överväger alternativ färg)
har en variant till höger som inkluderar lediga platser, med tanke på att Handläggare ska kunna se sådant enligt [ticket 436](https://github.com/noQ-sweden/noq/issues/453)

**Comment by overath2** [comment]
Detta ser riktigt bra ut. Jag kommer testa ordentligt i nästa vecka. Tre snabba synpunkter

1. Börja använda våra testusrar som heter *handlä[ggare@noq.nu](mailto:ggare@noq.nu) mm istället för caseworker så blir det tydligare vem som jobbar i systemet.
2. En handläggare (case worker) kan inte "tilldela". De kan dock neka/godkänna en förfrågan. Tilldelningen av sovplats sker av bostället/härbärget i sista hand. En handläggare har "veto" typ.
3. Istället för att dela upp på olika boställen - går det att ha en enda lista som man kan filtrera på boställen? Detta är nice to have efter 10/10 om inte för stort jobb.

Bra jobbat! Nu ser jag fram emot gäst och boställets interaktion i flödet.

**Comment by ChristofferEriksson-NoQ** [comment]
Uppdaterat figma och redo för ny rond feedback - en till variant finns till höger om länkade framen
https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=4173-3092&t=OWUZZYhisKLmwE0L-1
Ändringar:
Boende är nu en kolumn istället för rubrik/fönster
Rad för flaggor
Ändrar avstånd mellan kolumner
Testar 2 set av ikoner för flaggor
Testar om ordningen av kolumner bör vara Datum, gäst, boende... eller Datum, boende, gäst...
Tagit bort UNO kod kolumn
Ändrat rubrikordning enligt Oves specifikation

**Comment by overath2** [comment]
Det här börjar ser sjukt bra ut! Glöm inte bort att det är fokus på flödet Gäst-Admin/Boställe-Handläggare/Soc. Inställningar och rumstyper är finlir som kommer efter 10/10 när vi fått feedback. Men finns tiden så...

**Comment by jani-at-noq** [comment]
Ser bra ut. Ove ville ha filtrering på bostället också. Var ska vi placera den?

**Comment by overath2** [comment]
Det är nice to have. Dvs efter 10/10. Men idealt kan man via dropdownlist på respektive rubrik både filtrera och sortera. Skriv gärna två storys om detta.
