### ISSUE TITLE
Skapa sidomeny för handläggare

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#520]
###Beskrivning
Som en handläggare vill jag kunna navigera runt i appen med hjälp att menu på vänster sidan av fönster.

###Acceptance Criteria
Vi har egen sidomeny på plats för handläggare

Sidomenyn ska innehålla
- länk till handläggarens huvudsida
- länk till hantering av bokningar
- länk till hantering av användare (brukare/gäst)
- länk till statistik från härbärgen

###Subtasks
- Skapa sidomeny för handläggare
- Uppdatera app så att rätt sidomeny visas när handläggaren loggar in
- Design för ikoner för meny items

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by jani-at-noq** [comment]
Demo: [https://drive.google.com/file/d/1-NPScPJ0hlfc2bxWpmiXfkz9hi3yeu0q/view?usp=drive_link](https://drive.google.com/file/d/1-NPScPJ0hlfc2bxWpmiXfkz9hi3yeu0q/view?usp=drive_link)

Ikonerna i meny är färdiga ikoner från font awesome och är inte beskrivit i nån grafiskprofil för noQ. Har använt dom som känns passande, tills vi har förslag från UI/UX.

**Comment by overath2** [comment]
Mycket snyggt. Tre synpunkter:

1. Vi måste renodla vokabulären. Caseworker/Handläggare tex. Ska vi ha engelska internt och svenska externt?
2. Login vill jag sker med de usrar är skapade med noq-mail Ex: kalle.boende@noq.nu istället för caseworker.host...
3. Kan vi få in vald ikonuppsättning i den grafiska profilen tills vi har något som vi har utrett?

**Comment by jani-at-noq** [comment]
1. Vi hade discussion i våras att i koden är allt på engelska och då bestämde vi att använda dessa tre begrepp (user, host caseworker). I UI är allt på svenska.

**Comment by overath2** [comment]
Bra. Bara det är beslutat och dokumenterat så det inte blir hörsägen.
