### ISSUE TITLE
Navigering

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#522]
Som en användare vill jag att min navigering visar de moduler jag har valt under inställningar så att jag kan få en kort navigeringsmeny och ta mig till modulens arbetsyta.

AC

- [ ] Fungerande navigeringsmeny
- [ ] Ikoner i navigeringsmenyn satta i den grafiska profilen
- [ ] Navigeringsmenyn öppnar upp modulen i arbetsytan vid klick

**Comment by FannyBacklin** [comment]
@SelsabeelA @natischmidt Är den här påbörjad och blir klar till onsdag? :)

**Comment by SelsabeelA** [comment]
Ja, jag uppdaterar er imorgon.
