### ISSUE TITLE
Rubrikrad

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#523]
Som en användare vill jag se vem som är inloggad samt vilken modul som visas i arbetsytan så jag lätt kan känna mig hemma.

AC

- [ ] Rubrikraden för samtliga moduler i appen visar modulens namn som visas i arbetsytan.

**Comment by overath2** [comment]
@patrik-pwned kan du ta denna som wingmate?

**Comment by patrik-pwned** [comment]
Javisst @overath2

**Comment by patrik-pwned** [comment]
@jani-at-noq är granskare
