### ISSUE TITLE
Anmälningsformulär

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#530]
Som en deltagare vill jag ha ett enkelt sätt att anmäla mig så jag kan delta

AC

- [ ] Formulär för anmälan länkat till nyhet på hemsidan

Denna task tillhör epic #328

**Comment by overath2** [comment]
@FannyBacklin kan du reviewa: https://forms.gle/EoyfB1WCjrMN5jSP7

**Comment by FannyBacklin** [comment]
Jag testade att anmäla mig och det funkar fint. Kan vi fixa till bilden dock på enkäten för noQ blir kapat på hälften? @overath2

**Comment by overath2** [comment]
Ska försöka fixa till bilden.

**Comment by overath2** [comment]
Nä länk till formuläret. Kika att det går att anmäla sig OK från vår hemsida också: https://forms.gle/Cqot58itgmjyVcyn9

**Comment by overath2** [comment]
Demo: https://drive.google.com/file/d/1VwUWw77y7d91g1CnzGWk3e3m4kt1H-D4/view?usp=drive_link

**Comment by overath2** [comment]
Dax igen för review @FannyBacklin

**Comment by FannyBacklin** [comment]
Sorry missat din kommentar, kikar på den under dagen! @overath2

**Comment by FannyBacklin** [comment]
Det funkar fint att anmäla sig, när jag anmält mig så får jag dock upp text på svenska men anmälan i formuläret är på engelska, ok eller bör vi kanske vara enhetliga med språket? @overath2 
![Image](https://github.com/user-attachments/assets/b444d856-b4b4-4cf4-8f39-f29e598b081c)

**Comment by FannyBacklin** [comment]
På hemsidan fungerar inte "anmäl" knappen:
![Image](https://github.com/user-attachments/assets/07d7ce40-c858-45c0-a6c9-8dac6128d1ce)

**Comment by overath2** [comment]
Vi avbokar hela Hackathon pga för få anmälningar
