### ISSUE TITLE
Regler

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#531]
Som en deltagare så vill jag ha tydliga och enkla regler för tävlingen så det blir fair play.

AC:

- [x] Regler funna på vår hemsida
- [x] Reglerna korrlästa och feedbackade

Denna task tillhör epic #328

**Comment by overath2** [comment]
Kla för test: https://noq.nu/inbjudan-hackathon-for-hemlosa/

**Comment by FannyBacklin** [comment]
@FannyBacklin https://noq.nu/inbjudan-hackathon-for-hemlosa/

**Comment by FannyBacklin** [comment]
Här kommer feedback @overath2 

Förslag på ändring i texten:
1. Teamuppsättning
Antal deltagare per team: Varje team får bestå av 2–5 personer.
Individuell anmälan: Om du inte har ett team vid anmälan kan arrangörerna hjälpa till att matcha dig med andra. Fyll **i detta på anmälan** _"Fyll i detta i anmälningsformuläret"._


Under "priser", hur mäter vi kategoring "bästa teamwork?. 


Längre ner ovanför bannern: 
**Här några banners du kan lägga på din sida.** 
Förslag till ändring: Nedan finner du några banners du kan lägga upp på din sida.

**Comment by overath2** [comment]
Klart. Kan du reviewa @FannyBacklin ?
Ang frågan: Tog bort den.

**Comment by FannyBacklin** [comment]
![Image](https://github.com/user-attachments/assets/68d80392-df85-4c34-89e9-ca3ea122cfea)

Texten är i en anmälningslänk, se bild @overath2 

Utöver det så ser allt bra ut!

**Comment by overath2** [comment]
@FannyBacklin jag förstår inte din "bug" ovan?

**Comment by overath2** [comment]
Demo: https://drive.google.com/file/d/1foIouuDi6ek1ywDJLyrcgDr8dxTyRAoh/view?usp=drive_link

**Comment by overath2** [comment]
OK, detta är en WP bug jag inte kan. Vi får spara den. Kan du skriva en bug på det? Och sen dra till done?

**Comment by FannyBacklin** [comment]
Fixat! @overath2 La den dock så länge i sprint 9, vet inte om det är rätt?
