### ISSUE TITLE
Bekräftelse på förfrågan

### ISSUE THREAD

**Issue by callekrook** [noQ-sweden/noq#539]
Som gäst vill jag veta att min förfrågan skickades iväg och kommer att behandlas. 

Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
5 min demo

**Comment by overath2** [comment]
Hej @Gafrelek ! När kan denna starta?

**Comment by Gafrelek** [comment]
Ill have time this weekend, Had talk with @DiakoIsmail do technically i started 😀 updated status

**Comment by jani-at-noq** [comment]
https://github.com/noQ-sweden/noQ-Frontend/pull/42

**Comment by patrik-pwned** [comment]
Är denna fortfarande i review eller är vi klara?

**Comment by jani-at-noq** [comment]
done.
