### ISSUE TITLE
Inkludera användarens namn i LoginSchema

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#552]
###Beskrivning
Som användare vill jag se mitt namn i olika delar av appen.

###Acceptance Criteria
Frontend useLogin har information om användarens första namn och efternamn
LoginSchema i login API är uppdaterad med användarens första namn och efternamn
Mock API i frontend är uppdaterad
Header för frontend är uppdaterad att använda första namn och efternamn

###Subtasks
- Uppdatera loginSchema i Backend
- Uppdatera mockApi för frontend
- Uppdatera header med första namn och efternamn

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by FannyBacklin** [comment]
@MarioDanilo0111 @jani-at-noq  är den här påbörjad eller behöver ni stöttning från någon av de andra för att den här ska kunna startas? :)

**Comment by jani-at-noq** [comment]
Backend is ready. Mario works eith frontend changes. No support needed right now.

**Comment by FannyBacklin** [comment]
Ok good, thanks for the update Jani. Then I will move this ticket to "in progress"!

**Comment by FannyBacklin** [comment]
@MarioDanilo0111 vem är din wingmate på den här tasken? :)

**Comment by jani-at-noq** [comment]
> [@MarioDanilo0111](https://github.com/MarioDanilo0111) vem är din wingmate på den här tasken? :)

Jag är wingmate, uppdaterade infon nu.
