### ISSUE TITLE
Mätning trivsel, engagemang och ledarskap

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#553]
Som HR-ansvarig vill jag designa en undersökningsmall som täcker arbetsmiljö, ledarksap och företagskultur, så att jag får relevant feedback från medarbetarna.

Ref mot epic Mätning https://github.com/noQ-sweden/noq/issues/513

AC1:
Förutsatt att en noq:are klickar på länken till enkäten
När hen ska svara på frågor om noQs arbetsmiljö, ledarskap och kultur och klickar sedan på "skicka"
Skickas en sammanställning av svaren från enkäten som styrelsen kan läsa

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo

**Comment by overath2** [comment]
kan vi köra denna i sprint 10?

**Comment by FannyBacklin** [comment]
Jaa det tycker jag! @overath2

**Comment by overath2** [comment]
Flyttad.

**Comment by FannyBacklin** [comment]
Enkät utskickad, deadline att svara är 23/10

**Comment by FannyBacklin** [comment]
@overath2 ping!

**Comment by overath2** [comment]
Bra. Jag flyttar till Done.
