### ISSUE TITLE
Lista över boställen Backend

### ISSUE THREAD

**Issue by marco-noq** [noQ-sweden/noq#554]
Redan nu finns en enkel hantering av detta men jag skapar en task för att ev. behöva göra ändringar och för att logga ärende status. 

###Beskrivning
"Som inloggad gäst vill jag kunna se en lista med Boställen och dess rum och sängplatser."

**Given:** Gästen är en användare av NoQ-appen.
**When:** Gästen har loggat in.
**Then:** Då ska en lista med boställen som har lediga sängplatser visas.

**Comment by FannyBacklin** [comment]
Hej @marco-noq 

Bra om du följer mallen för user story så att det blir tydligt vad utkomsten av den här storyn sa vara samt att wingmate vet hur den här ska testat för att kunna flyttas till done :) 

Se mall:
**Story**
As a [user] i need to [action/title of this story] so i can [value].

**Acceptance Criteria (checklist)**
- [ ]  One
- [ ]  Two
- [ ]  Three

**Acceptance Criteria (BDD)**

AC1:
* Given [status/place]
* When [action]
* Then [result/output]

AC2:
* Given [status/place]
* When [action]
* Then [result/output]


- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by marco-noq** [comment]
@FannyBacklin Japp jag ska beskriva ärendet lite bättre. Men eftersom det bara är en Task och inte en User story så blir det inte helt lätt att följa Story-mallen.

**Comment by jani-at-noq** [comment]
PR är i granskning. Ett litet ändring behövs. https://github.com/noQ-sweden/noq_backend_python/pull/57
