### ISSUE TITLE
Analysera resultat från medarbetarundersökning

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#555]
Som analytiker vill jag sammanställa och analysera resultaten för att identifiera mönster och förbättringsområden gällande trivsel, psykologisk trygghet och ledarskap.

Ref mot epic Mätning https://github.com/noQ-sweden/noq/issues/513

AC1: 
Förutsatt att noq:are svarat på enkäten om trivsel, trygghet och ledarskap
När jag klicka på "se svar" och transportera svaren till excel eller dylikt verktyg
Så får jag en sammanställning och kan utefter den sammanställningen analysera och identifiera förbättringsområden

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo

**Comment by FannyBacklin** [comment]
@overath2 Vill du va wingmate på denna?

**Comment by overath2** [comment]
Tjohoo!

**Comment by overath2** [comment]
Ska vi flytta denna till sprint 10?

**Comment by FannyBacklin** [comment]
Jaa, jag hinner nog inte med den här sprinten @overath2

**Comment by overath2** [comment]
OK, du flyttar.

**Comment by FannyBacklin** [comment]
@overath2 ping!

**Comment by overath2** [comment]
Flyttar till Done
