### ISSUE TITLE
Mätning sprintleveranser

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#556]
Som Scrum Master vill jag skapa en rapport som presenterar sprintleveransinsikter, och föreslå förbättringsåtgärder till ledningen och projektet.

Ref mot epic Mätning https://github.com/noQ-sweden/noq/issues/513

AC1:
Förutsatt att det genomförst en sprint 
Kan jag klicka ta ut en rapport i GitHub som jag sedan kan transportera till excel 
Så får jag ut en sammanställning som jag kan analysera

###Subtasks

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo

**Comment by FannyBacklin** [comment]
@Gafrelek Can you be wingmate on this task? :)

**Comment by filipamo** [comment]
yes @FannyBacklin

**Comment by FannyBacklin** [comment]
Kan den här vara ett sätt att följa upp under sprintens gång? Har du någon erfarenhet av burn-ups? @filipamo 

![Image](https://github.com/user-attachments/assets/3a4c3506-e55e-4ea1-8243-362071cb0d3a)

**Comment by filipamo** [comment]
ja men inte i githuben. vart kan jag hitta den funktionen?

**Comment by FannyBacklin** [comment]
Jag föreslår på att vi kör burn-up under sprintarna för att visa på status hur vi ligger till vs det vi committat till. Vi kan använda det för att följa upp status för hela projektet respektive team.

**Comment by FannyBacklin** [comment]
@filipamo vill du reviewa :)

**Comment by filipamo** [comment]
done @FannyBacklin
