### ISSUE TITLE
Skapa reklampost att sätta upp på stan

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#558]
Som noq:are vill jag skapa en poster som går att skriva ut posters så att jag kan sätta upp dom på stan för att sprida informationen om noQ:s applikation till allmänheten

Ref EPIC: Marknadsföring [#512](https://github.com/noQ-sweden/noq/issues/512)

AC1: 
- [ ] Skapa poster med information hur man går tillväga för att komma till appen och länk till www.noq.nu

**Comment by FannyBacklin** [comment]
@ChristofferEriksson-NoQ eller @inhyenoq Can you maybe take a look at this ticket? I need design-skills so we can print out a nice poster :D

**Comment by ChristofferEriksson-NoQ** [comment]
Ursäkta det sena svaret. Lite osäker hur det kommer se ut med tid just under November månad så jag vill inte lova mig själv som assignee än, men jag stödjer gärna uppgiften som wingmate och att finslipa design och liknande.

**Comment by inhyenoq** [comment]
Har en design idé men svårt att hitta tid till att jobba med det! När är deadline?

**Comment by FannyBacklin** [comment]
@inhyenoq @ChristofferEriksson-NoQ Vi får stämma av med våra POs när det här ska planeras in, när tror ni vi behöver få ut den här senast @LudvigErlandsson @patrik-pwned?

**Comment by patrik-pwned** [comment]
Jag tänker mig att vi marknadsför lanseringen i sprint 12 

Bör vi ha detta på plats först #602 ?

**Comment by inhyenoq** [comment]
Poster PDF filen
https://drive.google.com/drive/folders/1SdPNReJscURZepWgsKQIuTD4sp1_P4cV?usp=drive_link

**Comment by patrik-pwned** [comment]
Ser koolt ut! Ska det vara kod i bakgrunden?

**Comment by inhyenoq** [comment]
@patrik-pwned Jo, jag tror att det ser ut intressant till IT folk.

**Comment by ChristofferEriksson-NoQ** [comment]
Jag ser inga problem med designen för postrarna! Tror att de är redo för produktion

**Comment by FannyBacklin** [comment]
Jaa kanske är en smart idé faktiskt att prov-skriva ut en för att se att det ser bra ut! @overath2 kunde du testa?

**Comment by overath2** [comment]
Japp. Skicka en PDF bara?

**Comment by overath2** [comment]
De som ligger i mappen ovan är från 6 nov.

**Comment by FannyBacklin** [comment]
Japp, fixar du @inhyenoq

**Comment by overath2** [comment]
![image](https://github.com/user-attachments/assets/eaf489b4-eb8b-47e4-bca6-6488f530b360)

**Comment by overath2** [comment]
Har skapat en spec med tillägget att A4 ska ha en baksida: https://docs.google.com/document/d/1SmykYSOCVpQMqszox4VPX_F5guCOq3IZs8KKXUjZI0U/edit?usp=drive_link
Drar tillbaka till In progress. Ping @inhyenoq och @ChristofferEriksson-NoQ

**Comment by overath2** [comment]
Notera att det är två olika målgrupper:

1. Att marknadsföra oss för blivande volontärer på noQ och här behöver vi också tänka på "Volontärer på stan"
2. De hemlösa för utdelning direkt så volontärer kan hjälpa dem.

**Comment by FannyBacklin** [comment]
Ja funderar på, borde vi göra texten större så at det syns mer och mindre text av "programmeringsspråk" eller vad tycker ni? @overath2 @inhyenoq @ChristofferEriksson-NoQ

**Comment by ChristofferEriksson-NoQ** [comment]
En aning kanske, som poster vi vill ha den fångar uppmärksamhet, och sedan går snabbt till poängen innan man hinner gå ifrån. Så man kanske kan få in en rad med lite större text om att vi behöver volontärer och att man kan få hjälp av de?

**Comment by FannyBacklin** [comment]
hur går det för er med denna @inhyenoq @ChristofferEriksson-NoQ

**Comment by inhyenoq** [comment]
@FannyBacklin @overath2  hej, jag tror att jag har mist några här. 

1. Jag tänkte att vi har en type poster till varje målgrupp och min design blir en för "Volontärer på stan". Det finns Crhistoffers design för hemlösa https://github.com/noQ-sweden/noq/issues/669#issuecomment-2496152481 
Men ni diskutera om en specen med tillägget att A4 https://github.com/noQ-sweden/noq/issues/558#issuecomment-2497325594 
Det ser ut som att vara för den annan gruppen, de hemlösa. Eller?

2. Och tidigt var det commenter om storlek - vi planerade att skriv ut A4 eller hur? Vill ni behöver tre olika storlek?

3. När är deadline till poster? Under sprint 10, har jag skapade den design och få några feedback. Det såg ut som att det fick ett okej innan sprint 11 då jag har fokuserat #674 #635 under denna sprinten. Dem tre ticket är ganska stor tillsammans och det finns fortfarande 20-30% kvar i #674. Om det är okej skulle jag färdigställa dem.

**Comment by overath2** [comment]
Svar:

1. Posters på stan skulle jag vilja blir posters för univesritet etc. Dvs en mindre men bättre målgrupp.
2. A3 om det är poster. A4 om det är flyer.
3. Ingen brådska med posters. Flyers däremot måste vara klara 6/12.

**Comment by inhyenoq** [comment]
@overath2 Thanks. Kan du förklara lite mer?

#### 1. A3 poster
- målgrupp?
- vilken poster design blir det?
- vad behöver du att redigera på design? 
#### 2. A4 flyer: 
- målgrupp?
- vilken poster design blir det?
- vad behöver du att redigera på design?

**Comment by overath2** [comment]
Svar ang målgrupp:

1. De som kanske vill börja jobba med oss = A3 poster för uppsättning på högskolor etc
2. De hemlösa = A4 på olika språk för utdelning.

**Comment by overath2** [comment]
Klar för mig. Wingmate?

**Comment by ChristofferEriksson-NoQ** [comment]
Alla mål och feedback uppnådda & snygg design!

**Comment by inhyenoq** [comment]
Updaterade! (samma url)

**Comment by ChristofferEriksson-NoQ** [comment]
Perfekt! Inga fler förslag från min sida

**Comment by inhyenoq** [comment]
@overath2 OBS! Jag rättade en stavfel! Ladda ner igen innan att skriva!
