### ISSUE TITLE
Boka sovplats Backend

### ISSUE THREAD

**Issue by marco-noq** [noQ-sweden/noq#564]
Redan nu finns en enkel hantering av detta men jag skapar en task för att ev. behöva göra ändringar och för att logga ärende status.

### Beskrivning: "Jag vill boka en sängplats för nästkommande natt."

**Given**:
Gästen har loggat in i appen, valt ett boställe och ser en lista över rum med lediga sängplatser.

**When**:
När gästen trycker på knappen Välj så skickas anropet till api:t.

**Then**:
En bokningsförfrågan skapas.

**Comment by jani-at-noq** [comment]
Detta funktionalite är inne redan. Vad är skillnad med det som redan finns?
