### ISSUE TITLE
Webmaster sociala medier & MF

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#567]
Som marknadsföringsansvarig vill jag att en webmaster ska hantera vår webbplats och sociala mediekanaler, så att vi säkerställer att vår digitala närvaro är professionell, aktuell och engagerande för vår målgrupp.

Ref till EPIC: Marknadsföring [#512](https://github.com/noQ-sweden/noq/issues/512)

AC (Acceptance Criteria):

- [x] Ha minst 2 webmasters
- [x] Webmastern ska regelbundet uppdatera hemsidans innehåll, säkerställa att alla länkar fungerar och att designen är mobilvänlig.
- [x] Sociala medier ska hanteras genom att skapa och schemalägga inlägg i enlighet med marknadsföringsplanen.
- [x] Alla inlägg och uppdateringar ska vara konsekventa med noQs varumärke och budskap.
- [x] En tydlig arbetsplan ska finnas för att koordinera insatserna mellan webbplatsen och sociala mediekanalerna.
- [x] Fixa rollbeskrivning för webmaster

**Comment by overath2** [comment]
@FannyBacklin kan du ta denna i sprint 9?

**Comment by FannyBacklin** [comment]
@OssianAxelman  kan du vara min wingmate?

**Comment by FannyBacklin** [comment]
Tillfälligt jag & @overath2 som är webasters.

**Comment by FannyBacklin** [comment]
https://docs.google.com/document/d/1J3k388PVZidwu0OZvqY2AdH_4k3nsLJLqN9O9SCSCsU/edit

**Comment by FannyBacklin** [comment]
Aktivitetsplan:
https://docs.google.com/document/d/1GVOlW2iGFRbMMGl0hLlQFHbS5Gmi7JzJvxamOnuNWDk/edit#heading=h.gd6jclosnt5i

**Comment by FannyBacklin** [comment]
Ping @callekrook

**Comment by callekrook** [comment]
"En tydlig arbetsplan ska finnas för att koordinera insatserna mellan webbplatsen och sociala mediekanalerna." - Var kan jag hitta denna?

**Comment by FannyBacklin** [comment]
@callekrook Jag tänkte nog att den ingår i aktivitetsplanen, funkar det eller borde jag göra på något annat sätt? 
https://docs.google.com/document/d/1GVOlW2iGFRbMMGl0hLlQFHbS5Gmi7JzJvxamOnuNWDk/edit#heading=h.wyerl8kl2g9i

**Comment by FannyBacklin** [comment]
@patrik-pwned Skulle du vilja vara min wingmate på denna istället pga att CJ är på paus?

**Comment by patrik-pwned** [comment]
javisst ska jag börja kika igenom länkarna bland kommentarerna?

**Comment by FannyBacklin** [comment]
@patrik-pwned Tack, det låter grymt!!

**Comment by patrik-pwned** [comment]
Jag kom inte på något mer i stunden men återkommer lite senare!

Kanske @LudvigErlandsson har lite feedback på [marknadsföringsplanen](https://docs.google.com/document/d/1GVOlW2iGFRbMMGl0hLlQFHbS5Gmi7JzJvxamOnuNWDk/edit#heading=h.wyerl8kl2g9i)?

**Comment by FannyBacklin** [comment]
@patrik-pwned känns den här klar tycker du för tillfället eller är det något som saknas tycker du för att den ska vara klar?

**Comment by patrik-pwned** [comment]
Jag är inte jätte insatt i denna epic men jag får känslan av att vi är klara. Om du gör bedömningen att vi är klara så är jag nöjd :)
