### ISSUE TITLE
BUG: Booking that starts in the past can't be approved

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#569]
Backend returns 500 internal server error when host or caseworker tries to approve/decline a booking that has start date in the past and doesn't handle the booking.

Either we need to filter the booking away from the list or handle the command in backend in a graceful way.

Date for the image is 27th of September 2024. When Tilldela or Neka is pressed server returns following:
`PATCH http://51.20.75.35/api/host/pending/11/appoint 500 (Internal Server Error)`

And frontend logs:
`index-CDMmtU1t.js:207 Error while updating booking status.
z {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}`

![Image](https://github.com/user-attachments/assets/1ded8616-1bf8-4d7a-a27d-14552b2bd1c7)

**Comment by FannyBacklin** [comment]
@AhmadHajAhmad kunde du starta med denna? :)

**Comment by AhmadHajAhmad** [comment]
@FannyBacklin Jag ska göra mitt bästa för att slutföra det före fredag. 
Ska wingmaten vara från Mars-teamet?

**Comment by FannyBacklin** [comment]
Det är nog bra, dock hjälper de flesta till på Saturnus nu. @natischmidt har du möjlighet att vara wingmate på denna eller vet du någon annan vi kan höra med?
