### ISSUE TITLE
BUG: User can make conflicting bookings

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#570]
When user makes a booking, he/she can double book same dates. Backend will only check that the start date is not the same for two bookings.

Booking 1: Sep 23 - Sep 26 -> OK
Booking 2: Sep 24 - Sep 26 -> OK

It should not be possible to create Booking 2.

**Comment by FannyBacklin** [comment]
@AhmadHajAhmad Har du möjlighet att starta med denna? :)

**Comment by jani-at-noq** [comment]
Fix is merged to main. @djigna you can close the issue (wingmate sets to done and closes ticket).
