### ISSUE TITLE
Meddelande till gäst

### ISSUE THREAD

**Issue by OssianAxelman** [noQ-sweden/noq#572]
Som gäst vill jag se meddelanden från härbärgen.

Jag vill kunna: 
- se att jag har fått en godkänd sovplats
- se att jag har fått en sovplats under granskning
- se att jag har fått en nekad sovplats

Definition of Done

Definition of Done
OK from wingmate
OK from PO
5 min demo video

**Comment by callekrook** [comment]
Ska även ett tredje alternativ in här som då är "bokning granskas"?

**Comment by RasmusOUX** [comment]
https://drive.google.com/file/d/1o2sdl6ZhN9hKovQSTVQFt1z0UJUQ38ms/view?usp=sharing

**Comment by FannyBacklin** [comment]
Vem tar över den här storyn under din tid på paus @RasmusOUX @callekrook?

**Comment by callekrook** [comment]
Denna är klar, bara inte flyttad till done.
