### ISSUE TITLE
First drop-in

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#573]
**Story**
As noQ we need to do the first drop-in training so i can evaluate the concept for continue or abort

**Acceptance Criteria (checklist)**
- [ ]  One (of two) drop-in done
- [ ]  Feedback from visitors adn trainers noted
- [ ]  Three

**Other info:** 
See epic #424 

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
Efter samtal med gatans lag kommer första tillfället bli 8 november. Jag flyttar denna ticket till denna sprint.

**Comment by overath2** [comment]
@patrik-pwned skulle du kunna vara min wingmate här?

**Comment by overath2** [comment]
Två tillfällen inbokade. Se vår kalender.

**Comment by patrik-pwned** [comment]
> Två tillfällen inbokade. Se vår kalender.

Under vilken kalenderprenumeration hittar jag dem? Ser dem inte i min kalender

**Comment by overath2** [comment]
![image](https://github.com/user-attachments/assets/85a11ae1-f2ad-47dd-853b-a02d4fc3db57)
Kolla playbooken för hur du får dit denna om  du inte har den.

**Comment by patrik-pwned** [comment]
Flagga som spill eftersom sprint 10 avslutas idag?

**Comment by overath2** [comment]
Klar va @patrik-pwned ?
