### ISSUE TITLE
Second drop-in

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#574]
**Story**
As noQ we need to do the first drop-in training so i can evaluate the concept for continue or abort

**Acceptance Criteria (checklist)**
- [ ]  Two (of two) drop-in done
- [ ]  Feedback from visitors adn trainers noted
- [ ]  Three

**Other info:** 
See epic #424 

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
Två tillfällen inbokade. Se vår kalender.
@patrik-pwned kan du vara min wingmate här?

**Comment by overath2** [comment]
Yes.

**Comment by patrik-pwned** [comment]
Tråkigt
