### ISSUE TITLE
Demon 10/10

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#580]
**Story**
As a  noqare i need to have a great demo so i can great feedback

**Acceptance Criteria (BDD)**

AC1:
* Given the demo has been done
* When i check the feedback results
* Then i see at least three great feedbacks

**Other info:** 

- [x] Skapa team för demon
- [x] Narrativ skapat
- [x] Inbjudningar skickade
- [x] Träna minst en gång
- [x] Filma en gång
- [x] Genrep
- [x] Genomförande
- [x] Sammanställ feedback

- [x]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
Team: @FannyBacklin @jani-at-noq @natischmidt @callekrook @patryk-banach  @overath2

**Comment by overath2** [comment]
Narrativ mm i denna katalog: https://drive.google.com/drive/folders/1rqczoy38KEAdhmmcLTa4tqgG4wLzrNJV?usp=drive_link

**Comment by FannyBacklin** [comment]
Noteringar från demon:
https://docs.google.com/document/d/1s5GUxVyZSaBQLeZSEuy_QH0GxXAK6cPrgGO6R3uN_I8/edit

**Comment by overath2** [comment]
Vi har fått in tre svar. @FannyBacklin kan du sätta till done?
