### ISSUE TITLE
Skapa datateamet

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#581]
Sätta upp datateamet så detta kan börja jobba i backloggend med start sprint 10 senast.

- [x] 1 namngiven teamlead
- [x] 4 namngivna teammedlemmar
- [x] 2 epics nedbrutna: GDPR + 1 till
- [x] 10 stories/tasks skapade
- [x] 1 möte per vecka inbokat
- [x] Presentation av teamet gjort på Slack samt i fredagsmöte

**Comment by overath2** [comment]
Status @elajth ?

**Comment by overath2** [comment]
Hur går det här @elajth och @filipamo ?

**Comment by overath2** [comment]
När kan jag reviewa?

**Comment by elajth** [comment]
Jo men det går framåt men vi har inte gjort presentation än. Är osäker på om vi kommit upp i antal tickets än heller

**Comment by patrik-pwned** [comment]
Om ej klar flagga med spill :)

**Comment by overath2** [comment]
Status @elajth och @filipamo ?

**Comment by filipamo** [comment]
Vi saknar 10 stories, vi kommer nå den nästa sprint. @overath2
