### ISSUE TITLE
Docker Images and Deployment to Web Service

### ISSUE THREAD

**Issue by natischmidt** [noQ-sweden/noq#583]
**Story**
Som utvecklare behöver jag skapa Dockerbilder för vår applikation och deploya dem till webbtjänsten för att säkerställa att vår applikation fungerar konsekvent över olika miljöer.

**Acceptance Criteria (checklist)**
- Dockerbilderna måste byggas framgångsrikt utan fel.
- Applikationen måste deployas till den angivna webbtjänsten.
- Den deployade applikationen måste vara tillgänglig och fungera som förväntat.

**Acceptance Criteria (BDD)**

AC1:
* Given att Dockerfile och alla beroenden är korrekt konfigurerade
* When jag bygger Dockerbilderna
* Then bilderna ska byggas utan felmeddelanden

AC2:
* Given att Dockerbilderna har pushats till registret
* When jag deployar applikationen till webbtjänsten
* Then  applikationen ska vara tillgänglig via webbtjänstens URL och fungera som förväntat

**Other info:** 
Ex: Links, Solutions, best practices etc.

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by natischmidt** [comment]
WIP @jani-at-noq kan du fylla i resten??

**Comment by overath2** [comment]
Hur går det med denna så vi kan stänga epicen?

**Comment by natischmidt** [comment]
Hur går det med denna?

**Comment by natischmidt** [comment]
@jani-at-noq ?

**Comment by jani-at-noq** [comment]
Vi bygger docker filerna utan problem. Men än så länge har vi inte pushat nånting till register. Samt det finns issues med automatisk deployment. Jag skriver ticket för deployment problem och vi kan fixa det under nästa sprint. Osäkert om vi behöver pusha till Docker Registry.

**Comment by overath2** [comment]
Denna blev ej ready i sprintplaneringen så jag flyttar till sprint 11

**Comment by tobbe-joh** [comment]
Iom BUG 621 är fixad så deployas nu koden till server.
@natischmidt  menar du docker hub när du skriver registry?  i vår deploy process bygger vi och startar kontainrar direkt på servern.

**Comment by overath2** [comment]
@tobbe-joh är du driver/asignee? Om så, försök få denna till status ready (DoR)

**Comment by natischmidt** [comment]
Vad är status på denna

**Comment by jani-at-noq** [comment]
Det här story är done. Vi ska ta borta krav för registry. Vi har continuous deployment på plats för demo server.
