### ISSUE TITLE
Färger på demon

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#584]
Vi har fyra färger (beige, orange, grön, grå) definerade i vår grafiska profil.
För att skilja mellan de olika aktörerna i systemet vi demon är mitt förslag att vänster och toppmarginal får en av dessa färger så man märker att aktörerna byter i demon.
Detta kan vi ta bort efter demon.

**DoD**
OK from wingmate
OK from PO
5 min demo video

**Comment by callekrook** [comment]
Förslag att ge feedback på finns redo i Figma.

**Comment by overath2** [comment]
OK, feedback givem. @callekrook skulle återkomma.

**Comment by overath2** [comment]
Men vi är nära med färgerna. Glöm inte demo sedan.

**Comment by overath2** [comment]
Demo av denna ticket dvs.

**Comment by callekrook** [comment]
Justering gjord så feedback efterfrågas. Om allt ok skapar jag demo.

**Comment by overath2** [comment]
OK, kör!

**Comment by overath2** [comment]
Status @callekrook ?

**Comment by overath2** [comment]
Snyggt! Lägg alltid länken till demon i ticketen bara @callekrook

**Comment by overath2** [comment]
Drar tillbaka till in progress och unassignar så det kan implementeras också. Pingar @jani-at-noq så han kan hitta någon som kan göra det.
