### ISSUE TITLE
Ansök till StartupGarage Bootcamp

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#588]
Som verksamhetsutvecklare för noQ vill jag ansöka till StartupGarage bootcamp för att få tips och feedback på noQs idé, pitcha den för en jury och tävla om 10k, så att jag kan utveckla noQs verksamhet vidare.

**Acceptance Criteria (checklist)**
- [ ]  Ansök via Drivshusets länk på linkedin

![Image](https://github.com/user-attachments/assets/031907e1-d253-4f1e-b869-1ae858e32dc7)

**Comment by overath2** [comment]
Hur gick det @FannyBacklin ? Försent?

**Comment by FannyBacklin** [comment]
@overath2 I och med att vi inte uppfyllde kraven så kan vi inte anmäla oss till den här. Men de ska ha en ny tävling runt feb/mars där man som startup kan vara med och tävla om 50k!

**Comment by overath2** [comment]
OK, ja sätter till done. Skriv en påminnelse om nästa gång.
