### ISSUE TITLE
Kommunkation Slack

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#589]
**Story**
Som medlem i teamet vill jag få snabbare reaktioner och svar på inlägg i Slack och mail, samt säkerställa att alla team är representerade i möten, så att kommunikationen och beslutsfattandet blir mer effektivt och inkluderande.

**Acceptance Criteria (checklist)**
- [x]  Påminn alla i fredagssync och i slackkanaler att cred till de som ger feedback (Fanny)
- [x] Påminn alla i fredagssync och i slackkanaler att påpeka när en saknar feedback/tar för lång tid. Uppmuntra till att våga (Fanny.
- [x] Ove (?) kör en workshop i CoP där mer erfarna utvecklare hjälper mer oerfarna.
- [x] Uppmuntra och påminn i fredagssync att hellre ha öppna diskussioner, våga ställa dumma frågor (Fanny)

Ref: Retrospective 29/30

**Comment by FannyBacklin** [comment]
@overath2 Känner du dig bekväm att köra WS med CoP eller ska jag ta den?

**Comment by overath2** [comment]
Vi kan snacka om det imorgon.

**Comment by FannyBacklin** [comment]
@overath2 kommer att dra igång med noQ academy och då kommer den här delen att täckas in med psykologisk trygghet.

**Comment by overath2** [comment]
Sätt till In review så kan jag sen sätta till done.

**Comment by overath2** [comment]
Done!
