### ISSUE TITLE
Lead Time granskningar för lång

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#590]
**Story**
Som teammedlem vill jag att Lead Time för granskningar förkortas, och att alla får utbildning i vad 'in review' och 'wingmate' innebär, så att vi kan effektivisera granskningsprocessen och förbättra vårt samarbete. 

**Acceptance Criteria (checklist)**
- [x]  Utbildning i vad är wingmate och "in review" innebär
- [x] Uppmuntra på fredagssync och i våra Slackkanaler att våga granska, våga ta hjälp om du är osäker.
- [x] Undersök om det finns någon variant av clappy - det var ett bra sätt att ge mikro-feedback.
- [x] Sätta upp önskemål/krav att det är prio 1 med granskning före utveckling i vår playbook.

Ref Retrospective 29/9

**Comment by FannyBacklin** [comment]
@jani-at-noq Satte dig som wingmate, hoppas det känns ok?

**Comment by FannyBacklin** [comment]
Film postad i general-chatten!

**Comment by FannyBacklin** [comment]
En variant på Clappy är att köra mentimeter som jag skickar ut varje fredag, kan det vara något @jani-at-noq @overath2? Se nedan:

![Image](https://github.com/user-attachments/assets/2e4e2818-405d-43d2-b2fc-15606a3bb09e)

![Image](https://github.com/user-attachments/assets/e4e03f13-54cd-4dbd-ba98-a5490a53754b)

**Comment by overath2** [comment]
Kör!

**Comment by FannyBacklin** [comment]
Ping @jani-at-noq

**Comment by jani-at-noq** [comment]
Ok för min del och det funkade också bättre denna sprinten.
