### ISSUE TITLE
SPIKE: Data storage in line with GDPR

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#592]
As an organisation, NOQ needs to have a secure data storage
In this spike we are only concerned about how to store data. We will investigate WHAT in another spike

We need to clarify what this means for us!

Our investigation is updated here:

Requirements (to be updated)
- [ ] Data is stored in a secure location (hack-proof)
- [ ] Data stored in line with GDPR and Dataskyddsförordningen
- [ ] Data stored in line with requirements from our partners

Investigation so far:
https://docs.google.com/document/d/1utlo7GV0N8tZnMZgksxt8p4h1e4Vxsq-cGX8EqqqPns/edit?tab=t.vdss2w9lv7er#heading=h.yrtj60nf9tpa

**Comment by filipamo** [comment]
@elajth @overath2 I have done some research on two possibilities of how to store data. I think me and Johan already touched upon some of the points in our discussions but we will need to choose one direction for our data strategy. [Document here](https://docs.google.com/document/d/1utlo7GV0N8tZnMZgksxt8p4h1e4Vxsq-cGX8EqqqPns/edit?tab=t.vdss2w9lv7er#heading=h.yrtj60nf9tpa)

**Comment by overath2** [comment]
Excellent Spike. As such this is sufficient. Please create an story for next step in next sprint. Involve @jani-at-noq in this for more tech-eyes onboard.

**Comment by patrik-pwned** [comment]
So flag this ticket as "spill"?
