### ISSUE TITLE
SPIKE: GDPR documentation

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#593]
As an organisation, NOQ need to have a GDPR/Dataskyddsförordningen plan so we know how to set up our data.

The purpose of this spike is to enable us to write a GDPR document

We will investigate (to be updated)

- [x] #610 

Investigation below:
Document findings in
https://docs.google.com/document/d/1i12Z_wpvWHbl0i8R4QkE18z5DlMVm6O79AHeS6b-zEI/edit?usp=drive_link

**Comment by patrik-pwned** [comment]
Om ej klar flagga med spill. Tack på förhand!

**Comment by elajth** [comment]
Review document please:
https://docs.google.com/document/d/1i12Z_wpvWHbl0i8R4QkE18z5DlMVm6O79AHeS6b-zEI/edit?usp=drive_link
