### ISSUE TITLE
HR-app i Slack

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#598]
**Story**
As a noQ person i need to get feedback, praise etc so i can improve and grow myself.

**Acceptance Criteria (checklist)**
- [ ]  App added to Slack
- [ ]  Process for how to work with it documented
- [ ]  People educated in this

**Other info:** 

- [ ] https://noq2.slack.com/marketplace/category/At0EFT6893-hr-team-culture
- [ ] https://getculturebot.com/blog/7-top-hr-apps-for-slack/

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
https://getculturebot.com/blog/7-top-hr-apps-for-slack/

**Comment by natischmidt** [comment]
behöver wingmate! :D

**Comment by overath2** [comment]
Ask Jessica. She has not GitHub yet though.

**Comment by natischmidt** [comment]
Jag har inte hittat någon helt gratis app för detta, men! Jag har hittat denna https://github.com/mmcdole/heyemoji?tab=readme-ov-file#setup - Så man installera den helt själv på vår workspace liksom :) installation kan jag fixa

**Comment by overath2** [comment]
Den ser spännande ut. Vi testar.

**Comment by natischmidt** [comment]
Denna ä WIP, hejemoji krävde en egen server jag kollar vidare efter bra gratis app :)

**Comment by overath2** [comment]
Bra förslag. Lägg en ticket i sprint 11 på första punkten tycker jag.

**Comment by natischmidt** [comment]
Stänga denna? har skapat ny ticket för skapande av app

**Comment by overath2** [comment]
Japp!
