### ISSUE TITLE
caseworker, crud operation for user/client - Backend

### ISSUE THREAD

**Issue by tobbe-joh** [noQ-sweden/noq#599]
**Story**
As a caseworker, I need to be able to handle a user/client in the system.
I should be able to register a new user, get the users information, update a user and delete a user.

**Acceptance Criteria**

* A caseworker can register a new user with mandatory fields.
* A caseworker can get client information.
* A caseworker can delete an existing user from the system, by user id.
* A caseworker can update user details/information.
* Proper error messages are displayed when the user cannot be registered, updated, or deleted.
* Successful operations (create, delete, update) return a success message.

**Acceptance Criteria (BDD)**

AC1: Registering a new user with valid data
  Given a caseworker is registering a user,
  When they provide a unique email and valid user details.
* Then the system creates the user and client records, ensuring all changes are saved atomically, and returns a 
  success message with the user ID.
* And if the region does not exist, the system returns an error indicating that the region is invalid.
* And if the email already exists, the system returns an error indicating the email is already in use.

AC2: Deleting an existing user by email
  Given a caseworker wants to delete a user,
  When they provide a valid email address of a user who belongs to the "user" group,
* Then the system removes the user from the database and returns a success message.
* And if the email does not exist, the system returns an error message indicating that the user does not exist.
* And if the user does not belong to the "user" group, the system returns an error indicating the user is not 
  eligible for deletion.

AC3: Updating user details
* Given a caseworker wants to update a user's details (e.g., name, phone number, or region),
* When they provide the correct user ID and new valid details,
* Then the system updates the user's information and returns a success message.
* And if any required field is missing or invalid (e.g., an invalid region), the system returns an error indicating 
   what is missing or incorrect.
* If the user ID does not exist, the system returns an error indicating the user does not exist.

AC4: Get user/client information
* after creating a user fetch client information by using the user id after registeration

 Definition of Ready OK?
1) skriven i User Story formatet
2) Har acceptanskriteria
3) Är lagom stor 
4) Har en driver

 Definition of Done OK?
OK from wingmate
Code checked in
All acceptance criterias done or cancelled

**Comment by FannyBacklin** [comment]
@MarioDanilo0111 vad är statusen på denna? :)
