### ISSUE TITLE
SPIKE: Find solution for production environment

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#602]
**Hypothesis**
We believe that a production environment separated from others (demo, test, dev etc) will help users achieve the exepcted value from our app.

Unlike today when users use demoenvironment
Our solution will make sure users gets ability to work with live data.
We know this is true when the following metrics has been ticked off:

**Acceptance Criteria**
* When the board has taken decision on what solution to issue

**Comment by overath2** [comment]
Hej @jani-at-noq . Jag skulle vilja att du tar hand om denna i slutet på oktober och har klart till december?

**Comment by overath2** [comment]
Tillsammans med devopsarna som börjar strax.

**Comment by overath2** [comment]
De nya behöver handledning här. Ping @jani-at-noq

**Comment by overath2** [comment]
Denna är brådskande också för mvp. Ping @LudvigErlandsson och @patrik-pwned

**Comment by overath2** [comment]
https://www.squad.se/hur-mycket-kostar-molntjanster/
Publik molntjänst?

**Comment by LudvigErlandsson** [comment]
Jani har tagit fram två förslag för molntjänster som kan hosta våra system. Sammanställer dessa förslag och pris i nästa steg så att styrelsen kan ta beslut.

**Comment by overath2** [comment]
Bra. Bolla detta med @jani-at-noq så vi får med detta i vår budget för #470

**Comment by LudvigErlandsson** [comment]
@jani-at-noq  Hello, jag har skapat en till PBI som är själva för uppsättningen. #680 

Den är ju beroende på att vi tar denna Spike i mål och styrelsen ger beslut. När tror du att ditt beslutsunderlag kan vara framme? 

Tack!

**Comment by jani-at-noq** [comment]
Förslag:
Ha 3 stycken AWS lightsail instanser för vår produktionsmiljö: 1 för development, med continuous deployment, 1 för staging för test innan release och 1 för produktion.

Noq ska skaffa aws konto och sen kan vi använda detta för att skapa server instanser.

Kostnad:
Varje instans har kostnad på runt 130 kr/månad. Det kommer också kostnader för produktions server för TLS certifikat på $18 per månad. Det är möjligt att gå med i awd non-profit program för 1100 sek/år och med det får man $100 credit per månad, vilket ska täcka alla kostnader.

**Comment by overath2** [comment]
Ser bra ut. Jag tar detta med styrelsen. Länk att jobba vidare med? Ping @jani-at-noq

**Comment by jani-at-noq** [comment]
Skapa AWS konto: https://signin.aws.amazon.com/signup?request_type=register
AWS för non-profits: https://www.techsoup.se/node/7436

**Comment by overath2** [comment]
Bra jobbat! Jag tar upp kostnaden på nästa styrelsemöte.

**Comment by jani-at-noq** [comment]
Vi har AWS miljö på plats nu. Jag stänger ticketen.

**Comment by LudvigErlandsson** [comment]
Snyggt jobbat @jani-at-noq!
