### ISSUE TITLE
Send credentials for new users on scheduled start date

### ISSUE THREAD

**Issue by inhyenoq** [noQ-sweden/noq#607]
Enhance #411 :
- Create a new user account when submitting the request.
- Then send credentials for on scheduled start date. 
- Allow hr person to change welcome message directly without Google tool masters' help.

Note from the board

> Tror du att det går att skicka mail till de nya innan de börjat? Dvs man skapar kontot när man fyller i formuläret men perosnen får ej login förrän startdagen.
mvh Ove

### Metrics

1. On the day that the request arrives, the script performs all other functions as it works now except sending credentials to the new member's private email.
2. On the start day, the script performs the excluded process on step 2: sending credentials to the new member's private email.
3. The script can create the welcome message by loading text from a Google document where HR person can write.

### Acceptance Criteria

- [x] All metrics measured on at least one testing case
- [x] Updated documentation
- [x] Updated playbook
- [x] A demo video

**Comment by overath2** [comment]
Att lära upp alla Googlemasters på denna process samt be Jessica om feedback på processen och därefter skapa en ny ticket för implementation i sprint 11.

**Comment by inhyenoq** [comment]
> Att lära upp alla Googlemasters på denna process samt be Jessica om feedback på processen och därefter skapa en ny ticket för implementation i sprint 11.

#608

**Comment by inhyenoq** [comment]
@overath2 
Kan du kolla igen welcome meddelande?

1. Ett welcome meddelande ska skickas till noQ-email. Det betyder att ny noQarer ser meddelandet efter de har skapat sin noq-mail. Jag tror att den texten nedan inte passar på flöden.
> "Du har i ett mail till din privata mailadress fått inlogg hit, till din nya noQ-mail." 

2. Ny person ska få ett mail som bjuda in att skapa sin noQ-mail på startdatum. Därför man måste har svarat med önskat startdatum före, eller hur? 
> "... du startar när du svarar på detta mail med önskat startdatum."

Jag skapade en verktyg till hr person. Nu kan du ändra två meddelanden som skickas till nya personer på den här formen. Apps script ska läsa texten direkt och skriva mailet.
https://docs.google.com/spreadsheets/d/1O48R1ewvlh2vvHfsv018soZM1q1kAPgMgtlMpCz0GlA/edit?gid=1353820704#gid=1353820704&range=C12

**Comment by overath2** [comment]
Perfekt med att kunna ändra texten. Jag kan göra det men undrar om den gröna eller/och gula är där jag ändrar?

**Comment by overath2** [comment]
Uppdaterat texten

**Comment by overath2** [comment]
Guesstimate missing

**Comment by inhyenoq** [comment]
Additionally, it will send the information of the new account to the person who filled the form.

**Comment by inhyenoq** [comment]
Demo video
https://drive.google.com/file/d/1t9Tk0Wmx1X3fDcLx6HwcAC0DApurjQcp/view?usp=drive_link

**Comment by overath2** [comment]
This is awesome. Both the process and the film as such. Great work. I as a wingmate will with pride set this to done and bookmark this ticket as a template for future trainings on how we work in the sprint board. Thanks!
But please make sure P&C, the board and toolmasters have seen the film.
