### ISSUE TITLE
Read up on GDPR plans

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq#610]
- [x] Read up on requirements 
- [x] Read other GDPR plans
- [ ] Document here and in #593
https://docs.google.com/document/d/1i12Z_wpvWHbl0i8R4QkE18z5DlMVm6O79AHeS6b-zEI/edit?usp=drive_link

**Comment by overath2** [comment]
Denna behöver dor. Ping @elajth

**Comment by filipamo** [comment]
@elajth I think we have done all the research we could so far. shall we move this to done?

**Comment by elajth** [comment]
Yes
