### ISSUE TITLE
BUG: Menylänk Bli Partner funkar inte på hemsidan

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#612]
Länken leder till gamla sidan med gröna bakgrunden

**Comment by overath2** [comment]
Pingar @Ovura-noq och @djigna eftersom den är kritisk.

**Comment by djigna** [comment]
Har ändrat så den kommer till rätt sida

**Comment by overath2** [comment]
Flyttar till sprint 10.

**Comment by overath2** [comment]
Vem är din wingmate för review @djigna ?

**Comment by djigna** [comment]
@Ovura-noq

**Comment by patrik-pwned** [comment]
Kvarstår problemet?
