### ISSUE TITLE
Feedback från användare

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#624]
**Story**
Vi har en utmaning i att vi fått in för lite "kundfeedback" under utvecklingen av applikationen. Detta är viktig input så att vi vet att vi bygger rätt produkt. 

**Acceptance Criteria (checklist)**
- [x] skapa ett utkast till feedback formulär
- [x] hitta 3-4 användare som kan testa och lämna feedback
- [x] Sätta upp en user group som arbetar med att samla in och analysera feedback

Ref retrospective från sprint #9

**Comment by FannyBacklin** [comment]
@patrik-pwned  @overath2 satte er på den här ticketen, funkar det?

**Comment by patrik-pwned** [comment]
Jag är på.

Ser dock utmaningar i att hinna med detta under en och samma sprint:
- skapa enhetlig feedback formulär
- hitta lagom många användare som kan testa appen och lämna feedback inom rimlig tid
- få ihop lagom mycket tillförlitlig data att kunna dra slutsatser

De primära 'panelerna' vi behöver etablera är gäster, boställen och kommunen. Sekundära men ändå snart aktuella är stödpersoner.

Eller så överskattar jag allt detta! Säg gärna till :)

**Comment by overath2** [comment]
Japp. Klyv den och ta den enklaste och viktigaste först. Här finns olika taktiker. Vissa vill ta det svåraste först.

**Comment by patrik-pwned** [comment]
Apropå 'Sätta upp en user group som arbetar med att samla in och analysera feedback', är tanken att vi bildar en grupp (kanske en från varje team) som får det operativa ansvaret med datainsamlingen? Och att produktägaren leder gruppen utåt mot panelen?

**Comment by patrik-pwned** [comment]
@FannyBacklin Jag har uppdaterat AC, ser det okej ut?

**Comment by FannyBacklin** [comment]
Jättebra AC @patrik-pwned, om möjligt kanske formulera om "lagom mycket" i och med att det kanske är svårt att mäta när det målet är uppnått. Förslagsvis att du skriver "hitta 3-4 personer som....." :)

**Comment by patrik-pwned** [comment]
Instämmer! 3-4 låter rimligt

**Comment by patrik-pwned** [comment]
https://docs.google.com/spreadsheets/d/1y6Rt17c7JktyEurimdACK5cuQNlNRgm50-zounFE5rI/edit?gid=0#gid=0

**Comment by overath2** [comment]
Bra början. Förstår dock inte strukturen. Skapa dessutom en lista på vilka som ingår i vår user group så ska jag försöka fylla denna.

**Comment by patrik-pwned** [comment]
Strukturen på frågorna eller på hur vi ska jobba löpande?

**Comment by overath2** [comment]
Strukturen på frågorna. Vet du hur du skapar ett google formulär? Hojta annars så visar jag. Bättre om du gör det och får feedbacke där?

**Comment by patrik-pwned** [comment]
Ah okej jag testar och återkommer! Ville bara få ut ett utkast snabbt :)

**Comment by patrik-pwned** [comment]
Formulär på svenska: https://docs.google.com/forms/d/10VnXvd6Nh8qpz4r6q122rPKIMMfjtzkssu4ijEBVdLA/edit

**Comment by patrik-pwned** [comment]
wingmate @overath2 

behöver review:as :)

**Comment by overath2** [comment]
Skulle vilja ha en demofilm också på denna så får vi bli bättre på dessa. innan jag sätter till done. Drar tillbaka till In progress.

**Comment by patrik-pwned** [comment]
Fixar demo imorgon kväll

**Comment by patrik-pwned** [comment]
Allt är klart!

**Comment by overath2** [comment]
Bytte namn på formuläret till Feedback på noQ och satte till done
