### ISSUE TITLE
Frontend för att se hur många nätter brukaren har sovit

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#626]
**Story**
As a caseworker I need to see statistics about the users and how many nights they have been in the shelter, so I can Check that against the invoices.

**Acceptance Criteria (checklist)**
- [x]  Mock api in place (should match backend rest API in #454 
- [x]  Create a statistics page that fetches data and displays it as described in figma (https://www.figma.com/design/CwWSHrCSf7igChqclirwLp/noQ?node-id=4090-24771&t=XJtiuzNXzBwfGifl-4)

**Acceptance Criteria (BDD)**

AC1:
* Given [status/place]
* When caseworker clicks on Statistics
* Then caseworker will see a list of user statics

**Other info:** 
Ex: Links, Solutions, best practices etc.

- [x]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by patrik-pwned** [comment]
Spill-flaggning på denna va?

**Comment by patrik-pwned** [comment]
Inte aktuellt för en caseworker i dagsläget men för bostället, ja.

**Comment by jani-at-noq** [comment]
Samma kod ska använda för handläggare och bostället när det gäller frontend. Liten ändring i url baserad på andvändare grupp behövs. För backend grävs ny api för bostället.
