### ISSUE TITLE
Story: Create Kickstarter account for NoQ

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#628]
Som styrelse för NoQ, vill jag ha konto i kickstarter.com för att kunna köra kampanjer för NoQ.

Krav för konto: (från: https://help.kickstarter.com/hc/en-us/articles/115005128594-Who-can-use-Kickstarter)
- If raising funds as an entity (business or nonprofit), you must launch your project in the country where the entity is registered. The individual setting up the project on the entity’s behalf must be an owner or executive of the entity, and have authorization to represent it. All beneficial owners of the entity, and directors as requested, must also be disclosed and verified. You need government issued IDs and tax documents for the primary entity raising funds for the project as well as for all individuals and other entities you verify

- You need a [supported bank account](https://help.kickstarter.com/hc/en-us/articles/115005136114-What-type-of-bank-account-can-I-use-to-set-up-my-project-) located in the same country you set up your project. This account must be owned by and in the name of the individual or entity raising funds.

- You have a major credit or debit card registered to the individual or entity (or entity’s owner) raising funds for this project, and in their name.

AC:
- NoQ har konto i Kickstarter

**Comment by overath2** [comment]
Om OK sätt till ready.

**Comment by jani-at-noq** [comment]
Jag kan inte ändra dom delarna i mobilappen. Du kan sätta mig som wingmate och ticket till ready. Annans fixar jag det efter vårt möte idag

**Comment by jani-at-noq** [comment]
Det gick, behövde bara hitta rätt knapp.

**Comment by overath2** [comment]
Ska vi ha ett snack i veckan @jani-at-noq ?

**Comment by jani-at-noq** [comment]
Hejsan,

Ja, efter academy?

/Jani

ma 21.10.2024 klo 19.34 Ove Holmberg (noQ) ***@***.***>
kirjoitti:

**Comment by overath2** [comment]
OK:
Kickstarter snack #628
Onsdag, den 23 oktober · 20:15–20:40
Tidszon: Europe/Stockholm
Google Meet anslutningsinformation
Videosamtalslänk: https://meet.google.com/nit-vbqh-npc
Eller ring: ‪(SE) +46 8 505 455 73‬ Pinkod: ‪348 364 461‬#
Fler telefonnummer: https://tel.meet/nit-vbqh-npc?pin=8609854789816

**Comment by overath2** [comment]
Har nu skapat konto men behöver en collaborator. Kan du öppna eget konto @jani-at-noq ?

**Comment by overath2** [comment]
Feedback link: https://www.kickstarter.com/projects/noq/884297151?ref=f2blf8&token=25e8b2e2

**Comment by overath2** [comment]
För review @jani-at-noq

**Comment by jani-at-noq** [comment]
> Har nu skapat konto men behöver en collaborator. Kan du öppna eget konto @jani-at-noq ?

Jag har skapat konto nu (jani@noq.nu).

**Comment by jani-at-noq** [comment]
Jag antar att vi kommer byta videon senare. Den hade nämligen lite problem med ljudet (echo för nån anledning). Men denna storyn är godkänt. Vi har konto och bra beskrivning av NoQ i sidan. Jag flyttar till done.
