### ISSUE TITLE
Story: Define rewards for the kickstarted Campaign

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#630]
**Story**
As a donator I need to know what rewards are available so I feel I get some appreciation back from the NoQ organization when I donate money.

**Acceptance Criteria (checklist)**
- [x] We have defined rewards and list them in the campaign page
- [ ] We have process the produce and deliver rewards in place

**Other info:** 
Ex: Links, Solutions, best practices etc.

- [ ]  **Definition of Ready OK?**

- [ ]  **Definition of Done OK?**

**Comment by overath2** [comment]
To produce rewards we will do after the campaign. Else OK. @jani-at-noq  can you be my wingmate?

**Comment by jani-at-noq** [comment]
Ok
