### ISSUE TITLE
Story: Create Promo Material & Promote the Kickstarter Campaign

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#632]
**Story**
- As a NoQ member I need promotion material for the NoQ Kickstarter campaign so I can spread it via my channels.
- As a NoQ member I need to promote NoQ Kickstarter campaign so we can create awareness of our campaign to reach as many donators as possible.

**Acceptance Criteria (checklist)**
- [x]  Promotion material for the Kickstarter campaign available for spreading. Material should include: LinkedIn post, Facebook post, Instagram post, Webpage promo (noq.nu), ... more platforms?
- [x]  NoQ team members have spread the information via their channels

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by FannyBacklin** [comment]
@patrik-pwned vill du vara wingmate?

**Comment by patrik-pwned** [comment]
Javisst!

**Comment by FannyBacklin** [comment]
@jani-at-noq ska kampanjmaterialet vara klart till MVPn eller vad har ni kommit överens om?

**Comment by jani-at-noq** [comment]
Kickstarter kampanj ska vara live imorgon, 13:e november tror jag och då ska vi börja promota också.

**Comment by FannyBacklin** [comment]
Skrev ett inlägg på linkedin, funkar detta eller ska jag justera något? Ska jag skapa plattform på insta och facebook och lägga upp samma inlägg? @patrik-pwned @jani-at-noq @overath2 
![Image](https://github.com/user-attachments/assets/353e76ca-2c00-498b-9472-aeeb7de5c912)

**Comment by overath2** [comment]
Japp. Har ändrat på Linkedin.

**Comment by FannyBacklin** [comment]
Ska skriva en artikel på vår hemsida om nästa demo samt att vi nu lanserat vår nya hemsida - när det är klart publicerar jag det på LI.

**Comment by FannyBacklin** [comment]
Klar (dock är detta projekt nedstängt).
