### ISSUE TITLE
 AI-chatbot integrerad i appen

### ISSUE THREAD

**Issue by SelsabeelA** [noQ-sweden/noq#637]
As a homeless individual or vulnerable user, I want an AI-chatbot integrated into the noQ app, So that I can get help navigating the app's main features like registration and account creation.
Acceptance Criteria:

The AI chatbot is integrated into the app interface.
The chatbot is accessible from the app’s home screen.
Users can initiate chatbot conversations from any screen.

**Comment by FannyBacklin** [comment]
Hej!  Denna verkar inte ha slutförts enligt vår DoD. Dvs Filipa drar till done och att det finns en demo. Vill ni kika på denna igen :) @filipamo @SelsabeelA

**Comment by SelsabeelA** [comment]
Ja förlåt jag glömde, det är lite pga ingen faktiskt har jobbat med en chatbot förr. Jag har spelat in demo:n och lagt upp den och fick min kod granskat av Náti. Ska öppna igen ticketen med denna kommentaren tills den blir granskat.👍

**Comment by filipamo** [comment]
@elajth could you have a look at this?

**Comment by elajth** [comment]
Looks fantastic @SelsabeelA! @filipamo you can move to done
