### ISSUE TITLE
Spelregler kommunikation för Team Mars

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#638]
**Story**
Som noQ:are vill jag att vi kommer överrens om hur vi ska kommunicera statusuppdateringar och hinder med varandra så att jag får information om hur vi ligger till med vårt arbete, samt att jag kan få hjälp snabbt om jag fastnat med något. 

**Acceptance Criteria (BDD)**

AC1:

- [x] Diskutera och komma överens om hur vi vill kommunicera med varandra. Exempel på frågor: Hur kommunicerar vi med varandra bäst? Via Slack? Via avstämningar? Både och? Hur lång tid från att jag skrivit ett inlägg förväntas jag få svar på min fråga? Varför är det viktigt för oss med kontinuelig kommunikation? 

- [x] Dokumentera spelreglerna och lägga upp den i vår team-mapp

Ref till task: Förbättra kommunikation gällande statusuppdateringar [#622](https://github.com/noQsweden/noq/issues/622)

**Comment by FannyBacklin** [comment]
@natischmidt hur går det med denna? :)

**Comment by natischmidt** [comment]
Jag tänkte ta det denna vecka! på torsdag (teammöte) :)

**Comment by natischmidt** [comment]
detta blev inte av, försöker få till ett nytt möte där alla faktiskt delta

**Comment by natischmidt** [comment]
Vi ska fixa detta ikväll!
