### ISSUE TITLE
Volontär kan boka sovplats åt gäst

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#644]
**Story**
Som en volontär vill jag kunna boka en sovplats åt en gäst, så att jag kan säkerställa att gästen har en trygg och reserverad plats att sova på.

Ref to EPIC: Ny roll - Volontär [#509](https://github.com/noQ-sweden/noq/issues/509)

**Acceptance Criteria (checklist)**

**Val av sovplats:**
- [x] Volontären ska kunna se en lista över tillgängliga sovplatser, inklusive relevant information som plats, och datum.
- [x] Volontären ska kunna filtrera sovplatser baserat på datum, plats eller tillgänglighet.

**Bokning av plats:**
- [x] Volontären ska kunna välja en specifik sovplats och boka den åt en gäst.
- [x] Efter bokningen ska det tydligt framgå att sovplatsen är reserverad för den specifika gästen.

**Bekräftelse:**
- [x] Volontären ska få en bekräftelse på att bokningen har genomförts, med information om vilken sovplats som är bokad och för vilken gäst.
- [x] En bekräftelse ska också skickas till gästens kontaktinformation om den finns registrerad.

**Acceptance Criteria (BDD)**

AC1:
Givet att jag är inloggad som volontär,
När jag navigerar till sidan för att boka sovplatser,
Så ska en lista över tillgängliga sovplatser visas med information om plats och datum.

AC2:
Givet att jag har valt en tillgänglig sovplats,
När jag anger gästinformation och bekräftar bokningen,
Så ska systemet markera sovplatsen som reserverad för den specifika gästen,
Och jag ska få en bekräftelse på bokningen.

###Definition of Done
OK from wingmate
Documented
All subtasks done or cancelled
Max 5 min demo video

**Comment by patrik-pwned** [comment]
@xelleze kan du ändra statusen i ticketen så den flyttas ifrån backlogen?

**Comment by patrik-pwned** [comment]
sorry @xelleze att jag är lite jobbig här - du som assignee behöver flytta den här ticketen ur backloggen (om du jobbar på den) så vi PO kan förebereda planeringen för nästa sprint

**Comment by patrik-pwned** [comment]
du saknar en wingmate också

**Comment by FannyBacklin** [comment]
@xelleze @jani-at-noq vem är wingmate på denna? :D

**Comment by LudvigErlandsson** [comment]
@xelleze @jani-at-noq Hej, hinner vi med denna eller ska den flyttas till Sprint 11 istället?

**Comment by patrik-pwned** [comment]
Denna är top priority så om ej klar måste den med i sprint 11. Flagga med spill om ej klar tack!

**Comment by overath2** [comment]
Ping @FannyBacklin och @xelleze

**Comment by FannyBacklin** [comment]
@djigna har du reviewat den här innan den drogs till done? En lite påminnelse att det är wingmaten som reviewar och drar den till done :) @xelleze @djigna

**Comment by xelleze** [comment]
@FannyBacklin Han har inte kontaktat mig och jag har fått mina pr reviewed och merged @djigna vet inte ifall du är aktiv eller inte men kontakta mig via slack
