### ISSUE TITLE
Spelregler kommunikaton Team Pluto

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#651]
Story
Som noQ:are vill jag att vi kommer överrens om hur vi ska kommunicera statusuppdateringar och hinder med varandra så att jag får information om hur vi ligger till med vårt arbete, samt att jag kan få hjälp snabbt om jag fastnat med något.

AC1:
- [ ] Diskutera och komma överens om hur vi vill kommunicera med varandra. Exempel på frågor: Hur kommunicerar vi med varandra bäst? Via Slack? Via avstämningar? Både och? Hur lång tid från att jag skrivit ett inlägg förväntas jag få svar på min fråga? Varför är det viktigt för oss med kontinuelig kommunikation?
- [x] Dokumentera spelreglerna och lägga upp den i vår team-mapp

Ref till task: Förbättra kommunikation gällande statusuppdateringar [#622](https://github.com/noQsweden/noq/issues/622)

**Comment by patrik-pwned** [comment]
Denna känns klar va? Flytta över den från progress till review/done tack :)

**Comment by filipamo** [comment]
Vi skrev ett teamskontrakt som vi kommer diskutera igen om 6 månader.
[Här är länken](https://docs.google.com/document/d/1mKe53Y_Bu8-OuGdxugVBpowDmfiFheBkSSndk50YT78/edit?tab=t.gkhmfew3jl0h)
