### ISSUE TITLE
Förmåga att svara på vanliga frågor i realtid

### ISSUE THREAD

**Issue by SelsabeelA** [noQ-sweden/noq#652]
As a user of noQ, I want the chatbot to answer my frequently asked questions in real-time, So that I can get quick help without needing to browse the app.
Acceptance Criteria:

- [x] Chatbot has a database of FAQs that it can pull from.
- [x] Chatbot responds to user queries within 3 seconds.
- [x] Chatbot provides correct and relevant answers to at least 90% of the FAQs tested.

- [x]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by filipamo** [comment]
@bubblyc would you like to be wingmate on this?

**Comment by bubblyc** [comment]
@filipamo @SelsabeelA sure I assigned myself

**Comment by patrik-pwned** [comment]
Har vi förresten en FAQ? @overath2 kanske vet?

**Comment by overath2** [comment]
Nix. Chatboten vorde kunna svara på FAQ. Ex. Var är det ledigt ikväll (eller vanligtvis).

**Comment by bubblyc** [comment]
The current bot is able to answer the questions defined in the faq, and able to improvise on undefined questions, and it's able to guide a person throughout the registration process step by step. Great job! @SelsabeelA  
The bot needs to be moved to the registration/login page for the registration help to be available for unregistered users. 
And the FAQ and be extended by anyone by sending in questions and answers to @SelsabeelA (or me)
