### ISSUE TITLE
Chatbot kan guida användare genom appens viktigaste funktioner (registrering, konton, etc.)

### ISSUE THREAD

**Issue by SelsabeelA** [noQ-sweden/noq#653]
As a user with limited digital literacy, I want the chatbot to guide me through important features like registration and account creation, So that I can successfully complete these actions without help.
Acceptance Criteria:

Chatbot can guide users through the registration process.
Chatbot can assist in account creation.
Chatbot provides step-by-step prompts and explanations to the user.

- [x]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by filipamo** [comment]
@bubblyc would you like to be wingmate on this?

**Comment by bubblyc** [comment]
@filipamo @SelsabeelA I can be the wingmate here too :)
