### ISSUE TITLE
Typo corrections in booking reservation page

### ISSUE THREAD

**Issue by patrik-pwned** [noQ-sweden/noq#658]
Correct a spelling mistake and replace one term in the booking reservation page.

AC:
* Given the page where I can make a booking reservation
* When I scroll down to the "Skicka medelande till härberget"
* Then I want to see "Skicka meddelande till bostället" instead

Note: correct spelling is "meddelande" and we use the umbrella term "bostället" and not härbärget.

**Comment by tobbe-joh** [comment]
@RasmusOUX Nu har jag gjort en PR i frontend. 
det ser ut som det är mycket som är ändrat och jag vet ej varför... det är som att min program har bytt ut alla ' ' till " ", till exempel. Ändrade namn på en fil från env.dev till env.development och i den ändrade jag också url, vet inte varför det var ändrad men så ska den vara för development mode med docker.

**Comment by RasmusOUX** [comment]
@tobbe-joh Kommer sätta mig och granska under morgondagen. Återkommer imorgon kväll senast.

**Comment by RasmusOUX** [comment]
Funderar möjligen på om man kanske ska ändra placeholder texten på rad 202 på AccomodationBooking.jsx. Det står på engelska nu. Men det är petigt och inte korrigeringen som nämns här.
