### ISSUE TITLE
Study for setting up BIMI

### ISSUE THREAD

**Issue by inhyenoq** [noQ-sweden/noq#664]
Story
As Google Workplace admins, we review the need for BIMI support as a recommended preventive measure that helps our emails be sorted correctly in the mail services. [See BIMI on Google Help Centre document](https://support.google.com/a/answer/10911320)

DoR
- [x] Study the method to set BIMI and assess the cost and time to setup
- [x] Make a conclusion for the short-term plan and share with Styrelsen and Google toolmaster.

**Comment by inhyenoq** [comment]
What is Brand Indicators for Message Identification (BIMI)? 

> When BIMI first rolled out in 2021, it was intended to give large brands a way to prove to readers that their emails were legitimate. Apple, Gmail, and Yahoo offer support for BIMI. Verified users will see a logo next to a brand’s name in the inbox. ... Gmail and Yahoo also show a verified checkmark at the top of the email to prove you’re getting a legitimate email. BIMI was designed to help alleviate concerns about spam and spoofing. If readers see that logo or checkmark, they know they can trust the email and the links inside. / see [the source](https://inboxcollective.com/what-is-a-common-mark-certificate-and-should-i-set-it-up-for-my-newsletter-what-you-need-to-know/)

The actions below are the preceding conditions for setting BIMI.

1. get a Verified Mark Certificate (VMC) or a Common Mark Certificate (CMC) issued by a certificate authority (CA).
2. set up SPF, DKIM, and DMARK (“quarantine” or “reject.” level)
3. ensure the use of a public web server to support BIMI.

The main issue is VMC or CMC. Obtaining VMC requires registering the logo as a trademark, which takes multiple months and a high cost (€850 to €1000). Therefore, a realistic option could be CMC, and its preceding conditions are below.
1. maintain the logo for at least one year
2. buy CMC from a certificate authority.

Currently, DigiCert and Entrust are the CAs that sell the CMC or VMC, and CMC is only available from DigiCert. The cost is $99 per month.

Based on the above information, I conclude it is too early to set BIMI for our organisation.
After all, it only adds the organisation’s logo to outgoing email messages. This action can reduce being treated as spam by recipients but does not affect the prevention of being sorted as spam on the technical side.

**Comment by inhyenoq** [comment]
@AbubakerSalah @FannyBacklin @overath2 
This is research related to [EPIC: Prevent spoofing, phishing, and spam](https://github.com/noQ-sweden/noq/issues/625)
Initially, I planned to set up BIMI, but I found it is not suitable for us at the moment. However, I documented the information collected for the archive. Please reply if you agree with the conclusion. If so, I'll close this issue without further action.

**Comment by overath2** [comment]
Pass. Ping new POs @patrik-pwned and @LudvigErlandsson

**Comment by LudvigErlandsson** [comment]
@inhyenoq Hello, good analysis and summary. I agree with you, likely not worth the spend for just adding the logo in email communications.

@patrik-pwned FYI
