### ISSUE TITLE
Kartläggning boställen

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#665]
Som noQ behöver vi veta alla befintliga boställen i Stockholm och deras kontaktpersoner för att kunna skapa sovplatser i vår app.

AC:

- [x] Denna fil är uppdaterad: [Externa](https://docs.google.com/spreadsheets/d/1spC3rpzhPONIb56-10wlM6hMJIypNWZot05_sdqoPoE/edit?gid=0#gid=0)
- [x] Minst 10 boställe kartlagt så att vi kan skicka förfrågan dit
- [x] Inleda kontakt och undersök om vår lösning kan adopteras av minst 3 av dem

**Comment by patrik-pwned** [comment]
@kan du assigna dig själv för denna och jag blir din wingamte?

**Comment by overath2** [comment]
Adding me as wingmate

**Comment by patrik-pwned** [comment]
Vi behöver boka ett kort möte och synka snart. Nästa vecka?

**Comment by overath2** [comment]
Sure: https://calendar.app.google/Tfq2pyNyHhkn5DKk9

**Comment by patrik-pwned** [comment]
@overath2 hur ska jag göra praktiskt med denna ticket? Det finns bara två härbärgen där Ny Gemenskap vill köra sitt och Frälsis vill vänta tills efter demon

**Comment by overath2** [comment]
Satsa allt på fälsis till demon.
