### ISSUE TITLE
Demokonton för referensgruppen

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#667]
As a member of the reference group i need login(s) i can use to test the application,

AC:

- [x] Ability to login
- [x] Ability to test each user
- [x] Ability to avoid conflicts with concurrent testers

**Comment by overath2** [comment]
Denna är brådskande så vi kan ge referensgruppen login. Senast 15/11 om möjligt? Ping @LudvigErlandsson och @patrik-pwned

**Comment by patrik-pwned** [comment]
Håller med. Vi tar in den i sprint 11

**Comment by patrik-pwned** [comment]
Kommer konflikt att uppstå om två pers använer samma konto samtidigt?

**Comment by jani-at-noq** [comment]
Vilken roll ska dom ha? Hndläggare, boställe, gäst eller volontär?

**Comment by jani-at-noq** [comment]
Jag tänker att vi kan dela dom referens användaren vi redan har för alla grupper. Dom finns i sida 8 i dokumentet för deployment: https://docs.google.com/presentation/d/1_uOMHUhDzGz8oVoecij03kRrmrzTMr3ILxx3DyNZseA/edit?usp=sharing

**Comment by jani-at-noq** [comment]
Eller är syftet nått annat?

**Comment by jani-at-noq** [comment]
Om det är bara att testa, då har vi redan olika användare på plats. Samma som vi själv använder för test.

**Comment by jani-at-noq** [comment]
> Blir det inte risk för konflikt då med inloggade samtidigt.

Vet inte riktigt hur system kommer att bete sig om två loggar in med samma konto samtidigt :-) Kanske bra att testa det nån gång. Vet inte hur ofta referens gruppen kommer använda sidan och om det blir konflikt. För att undvika detta kan vi skapa nya test användare för varje medlem i referens gruppen.

Ref medlem 1 till x: gäst login, volontär login, boställe login och handläggare login

Ska jag skapa 4 logins för varje 8 ref medlemmar?

**Comment by overath2** [comment]
Idealt har varje medlem i referensgruppen sitt eget login. Helst med deras egna email. Annars kanske test1@noq.nu osv
Men går det inte att administrera får vi ha minst ett login per usertyp. Konflikten tror jag inte blir aktuell.
Viktigt att det inte blir strul vid första inloggning.

**Comment by jani-at-noq** [comment]
Om det är bara 1 login, vilken användare grupp ska login gälla för? Gäst, boställe, handläggare volontär?

**Comment by overath2** [comment]
Om bara ett login måste man kunna välja vilken roll man har efter login eftersom processerna ser helt olika ut. Kan man ha en första sida som säger typ "välkommen till vår demomiljö - vilken roll vill du testa med? "Och så fyra val.

**Comment by jani-at-noq** [comment]
Spontant tänker jag att det är mycket jobb för liten nytta. Det är kanske bäst att vi börjar med att dela login uppgifter för vår test användare vi redan har. Och om det blir konflikter och problem kan vi skapa nya konton. Jag tänker att referensgruppen kommer testa tjänsten då och då och inte för längre tid i taget så risken för konflikt är acceptabel just nu.

**Comment by overath2** [comment]
Ok. Let's do it. Kan vi skapa instruktioner för refgrp hur logga in och testa?

**Comment by FannyBacklin** [comment]
@jani-at-noq är du driver på denna eller vem kör denna?

**Comment by overath2** [comment]
Jag vill skicka ut instruktionerna till referensgruppen senast 23/11.

**Comment by tobbe-joh** [comment]
@overath2,  går användare med inlogg till referensgruppen ut idag?

**Comment by overath2** [comment]
Tja @tobbe-joh ! Lämnar du över denna till någon när du tar paus?

**Comment by jani-at-noq** [comment]
Instruction document is ready for review:
https://docs.google.com/document/d/1W-tUOUpUAiQTWWzwrt0y2_Xldd_vP6LQZdf7lU_gE1Y/edit?usp=drive_link

**Comment by overath2** [comment]
Har ej provat att logga in på respektive. Skriver en separat test för detta. Annars super! Drar till done.
