### ISSUE TITLE
Skapa en poster för att informera gästerna

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#669]
Som noq:are vill jag skapa en poster som går att skriva ut posters så att jag kan sätta upp dom på stan för att sprida informationen om noQ:s applikation så att gästerna vet hur de ska göra för att boka en sovplats.

Ref EPIC: Marknadsföring https://github.com/noQ-sweden/noq/issues/512

AC1:

- [ ] Skapa poster med information hur man går tillväga för att komma till appenm hur man bokar sovplats och länk till [www.noq.nu](http://www.noq.nu/)/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

**Comment by overath2** [comment]
Jag skulle vilja ha med mig posters riktade till hemlösa nu på fredag. Jag kan printa ut om jag får A4 PDF senast fredag kl 10.
Kan vi knö in denna i pågående sprint @FannyBacklin ?

**Comment by FannyBacklin** [comment]
@inhyenoq och @ChristofferEriksson-NoQ har börjat kika på denna @overath2, tror ni att ni kan få den klara till fredag kl 10? :)

**Comment by overath2** [comment]
Inga problem men till 1/12 måste denna vara klar för utdelning av "oss på stan".

**Comment by inhyenoq** [comment]
Oj. Jag förväxlade det med #558. Jag har ganska många ticketen innan sprint 11. Kan du jobbar på det?@ChristofferEriksson-NoQ

**Comment by ChristofferEriksson-NoQ** [comment]
Ha den redo tills den första december? Det ska kunna ordnas!
Jag skulle föreslå att vi skapar en enklare url att inkludera, så att det blir enklare att anteckna/komma ihåg för de som inte kan ta bild/gå till webbsidan direkt.
(Dessutom så funderar nuvarande link inte)

**Comment by overath2** [comment]
Och QR kod?
Fundera på språk också. Svenska, Finska, Ukrainska, Spanska och arabiska är de vanligaste.

**Comment by overath2** [comment]
Jag signar upp som wingmate.

**Comment by overath2** [comment]
Manus:

Vill du ha en sovplats inomhus i natt?
noQ är en ideell organisation som hjälper hemlösa att hitta sovplatser i Stockholm. Kontakta vårt team som finns på stan så hjälper de dig. Vi har gula västar med noQ på ryggen om du ser oss, eller så ring xxxx, maila [xxxx@noq.nu](mailto:xxxx@noq.nu) eller om du har en smartphone, försök själv att hitta sovplats via [www.noq.nu/sovplats](http://www.noq.nu/sovplats) . [QR-kod]

**Comment by overath2** [comment]
Denna skulle jag vilja ha klar senast 27/11 om OK @ChristofferEriksson-NoQ ?

**Comment by ChristofferEriksson-NoQ** [comment]
Hej ursäkta tystnaden!

Jag bifogar samma version som jag har skickar i slack. Det jag är fundersam över är typsnitt, samt layout och hierarkin av information (vad är viktigast, och vad blir mindre prioriterat). Jag uppskattar tankar och feedback från teamet! 

Jag är även lite fundersam över hur vi uttrycker oss, då man vill uppmuntra till beslut. Samt så är jag lite fundersam över "Om du har en smartphone kan du göra detta själv", vilket kanske kan upplevas som lite passiv aggressivt av vissa

Jag har även uppdaterat prototyp dokumentet med översättningar.
![Vill du ha en sovplats inomhus i natt noQ är en ideell organisation som hjälper hemlösa att hitta sovplatser i Stockholm  Kontakta vårt team som finns på stan så hjälper de dig  Vi har gula västar](https://github.com/user-attachments/assets/baddadf5-bed1-4a18-b398-67877cbc160d)

**Comment by overath2** [comment]
Kommer att printa 9 december så bör ha klart till 6 december

**Comment by ChristofferEriksson-NoQ** [comment]
All feedback jag har fått hittills är implementerad och filerna i driven är up-to-date. Är det något jag har glömt?

**Comment by FannyBacklin** [comment]
Kom ihåg att uppdatera till "otherwise" om det inte är fixat! :) @ChristofferEriksson-NoQ

**Comment by ChristofferEriksson-NoQ** [comment]
Det är fixat det!

**Comment by ChristofferEriksson-NoQ** [comment]
ping wingmate @overath2 är detta klart eller har vi glömt något?

**Comment by overath2** [comment]
Klart med beröm!
