### ISSUE TITLE
Fritextfält UNO-kod för bokning via volontär

### ISSUE THREAD

**Issue by LudvigErlandsson** [noQ-sweden/noq#673]
**Story**
Som en volontär vill jag kunna boka en tid på ett härbärge för en gäst, genom att fylla i UNO-kod i ett fritextfält på bokningssidor, så att bokningen genomförs.

**Acceptance Criteria (checklist)**
- [x] Det ska finnas ett fritextfält ovanför "välj datum" där man kan fylla i UNO-kod
- [x] Fritextfältet ska ha en rubrik det där står "Ange gästens UNO-kod"
- [x] Det ska finnas logik som validerar att fältet fylls i
- [x] Logiken för formatet som fylls i ska vara enligt UNO-kod.

**Other info:** 
UNO-koden måste fyllas i för att Härbärget ska kunna matcha mot rummet. 

Logik för UNO-kod:

**Comment by LudvigErlandsson** [comment]
@djigna Hej Noah! Snyggt jobbat med guesstimate, och att du och Nati tagit denna. Säkerställ gärna att den här är Definition of Ready inför kvällens sprint-planering:

- Är den tydligt nedbruten som user story?
- Finns det fler acceptanskriterier än de jag skrev?
- Finns det några dependencies på andra tasks?

**Comment by djigna** [comment]
Hej! Vi kanske behöver validering av UNO-koden? Till exempel att kontrollera att fältet inte är tomt och att UNO-koden har rätt format om det finns några specifika krav på den

**Comment by LudvigErlandsson** [comment]
Det tycker jag låter som en bra plan Noah, la till ett acceptanskrav kring det! @djigna  

@overath2 Kan du hjälpa till att beskriva logiken för Uno-kod i denna ticket så att vi kan validera fritextfältet för UNO-kod ordentligt. Dvs, ska det vara första bokstaven i för och efternamn, sen födelsedatum och sista 4 siffror? 

Så att utvecklarna kan få tydliga instruktioner för logiken!

**Comment by natischmidt** [comment]
@djigna Hur går det?

**Comment by AbubakerSalah** [comment]
Hej, behöver du hjälp med den här?

**Comment by AbubakerSalah** [comment]
Volontärssidan är inte på plats och jag ser ingen ”välj datum” i Figma designen utan endast kalender. 
Jag är osäker på vart jag ska placera UNO-kod fältet 😅
Har jag missförstått eller missat något?

**Comment by overath2** [comment]
Tänk så  här:

1. Jag är volontär på stan.
2. Jag frågar hemlös om hen vill ha någonstans att bo över natten?
3. Om ja, frågar jag om hen har smartphone.
4. Om ja ,scannar denne vår QR kod och vi visar hur hen gör
5. Om nej ingen smartphone så kickar denna ticket in:

1. Volontär frågar vad hen heter och när denne är född
2. Svar Kalle Olsson 21 januari 1967
3. Volontär matar in KO6721 i ett textfält i vår app och trycker "Skicka förfrågan" (OBS! inget datum, den gäller för kommande natt Bara ett fält och en knapp alltså)
4. Boställe får förfrågan och svarar ja/nej
5. Volontär får svaret och meddelar beslut och eventuell karta till bostället.

OK @AbubakerSalah

**Comment by overath2** [comment]
Byggde den prototyp:
![image](https://github.com/user-attachments/assets/3c428759-2e44-4e4a-83e1-6c160b189124)

**Comment by AbubakerSalah** [comment]
Tack @overath2  Problemet är löst nu!

**Comment by LudvigErlandsson** [comment]
Bra sammanfattat @overath2!

**Comment by FannyBacklin** [comment]
@AbubakerSalah @natischmidt är den här klar eller blir det spill på denna?

**Comment by natischmidt** [comment]
Klar

**Comment by overath2** [comment]
Jag har skapat en bug som är prio 1 i nästa sprint. Se #706

**Comment by natischmidt** [comment]
Backend bli klar imorgon så tycker att denna kan vara kvar det är ju samma saker liksom

**Comment by jani-at-noq** [comment]
Backend är redo för granskning. Med API backend, kom lite ändringar i frontend kod också.

**Comment by overath2** [comment]
Heja!

**Comment by overath2** [comment]
Klar @natischmidt ?

**Comment by FannyBacklin** [comment]
@natischmidt ping!

**Comment by natischmidt** [comment]
Klar

**Comment by LudvigErlandsson** [comment]
Snyggt jobbat!
