### ISSUE TITLE
BUG: API for user statistics for Caseworker doesn't return first name and last name for the user

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq#681]
When we worked with the frontend for getting user stays we noticed that the API doesnt' return any other user information than id. According to the design we should show users first name and last name too. There is two ways to solve the issue: 1. call another api to get user information or 2. add first_name and last_name to the data that is returned for the statistics (/guests/nights/count/{start_date}/{end_date}).

I think adding the first_name and last_name to the returned schema would be the best solution as it limits the API calls to the server.

**Comment by patrik-pwned** [comment]
Jag tror att vi kan ta den till sprint 12 om det inte är brådis?

Jag har förstått det som att volontären ska kunna boka gäst med en unokod (istället för ett gästkonto) och då ingår inte personuppgifter väl, eller?

**Comment by jani-at-noq** [comment]
Nej. Kanske det ska vara unokod i stället för first_name, last_name i så fall.

**Comment by patrik-pwned** [comment]
Ah jag förstår! Vi har inte kommit längre i personuppgiftsfrågan så om vi kan leva med unkod för stunden vore det enklast tror jag. Ska vi sikta på sprint 12 istället?

**Comment by jani-at-noq** [comment]
Sprint 11 blir bra. Detta är redan 3:e sprint vi jobbar med detta så det är dags att avsluta jobbet.
