### ISSUE TITLE
Förberedelse demo 29/11

### ISSUE THREAD

**Issue by FannyBacklin** [noQ-sweden/noq#692]
**Story**
Som en medlem i noQs referensgrupp vill jag kunna delta på demon av MVPn 29/11 för att få insikter och förståelse för noQs app och kunna ge feedback på applikationen. 

**Acceptance Criteria (checklist)**
- [x]  Inbjudan utskickad
- [x] Synk senast tisdag  samma vecka om vi kör eller inte för att se om vi måste skjuta på demon en vecka
- [x] Förbereda upplägg för själva demon
- [x] Genomföra 2-3 genrep för att säkerställa att vi är ordentligt förberedda inför demon
- [x] Marknadsföra att vi kommer köra en demo 29/11 på linkedin
- [x] Skapa ett feedback-dokument @NJen9 
- [x] Skicka ut mejl till ref-gruppen med sammanställning från feedbacksvaren @patrik-pwned @LudvigErlandsson 
- [x] Bestämma vilka som antecknar feedback under själva demon @FannyBacklin @NJen9 antecknar
- [x] @ChristofferEriksson-NoQ spelar in demon
- [x] ladda upp deltagarlista här: https://drive.google.com/drive/folders/17w8kEVc97dv9pUay0RXWJPdZRVbuplMj

**Comment by FannyBacklin** [comment]
Förslag på upplägg som synkats med PO & devleads: 

Här kommer förslag på hur vi lägger upp demon 29/11 hojta gärna om ni inte håller med eller vill göra på något annat sätt:

12:15-12:20 Fanny & @NJen9  intro till noQ och syfte med demo
12:20-12:30 **Demo** inlogg gäster och hur de bokar sovplats @jani-at-noq demar eller representant från Saturnus.
12:30-12:45 **Demo** av inlogg handläggare boställen och hur de hanterar bokningar. Därefter demo av inlogg av volontärer och hur de hjälper gästerna med bokning av sovplats. @natischmidt demar eller representant från mars.

12:45-12:55 frivilliga kan testa logga in och testa applikationen själva, ställa frågor och ge feedback

Tänker att vi förhoppningsvis får frågor när ni också demar men om inte så har vi lite slottid i slutet för generell feedback och frågor. 

@elajth @filipamo är med i demon för att svara på frågor relaterade till säkerhet och GDPR. 

@overath2 feedback? :)

**Comment by FannyBacklin** [comment]
@NJen9 satte dig som wingmate, funkar?

**Comment by overath2** [comment]
Bra. En sak till: Hur ta vara på feedback.

**Comment by LudvigErlandsson** [comment]
@FannyBacklin Snyggt, känns som en bra plan detta!

**Comment by FannyBacklin** [comment]
@LudvigErlandsson @patrik-pwned tycker ni att vi också ska dema chat-botten? på ca 5min

**Comment by patrik-pwned** [comment]
Det tycker jag! Det är ett utmärkt tillfälle att visa upp utåt och internt vad Pluto har gjort :)

**Comment by LudvigErlandsson** [comment]
Jaa men absolut! Men kanske köra lite kortare, då det är mer Nice to have än MVP-funktionalitet?  @FannyBacklin @patrik-pwned

**Comment by FannyBacklin** [comment]
@ChristofferEriksson-NoQ Sa du att du skulle spela in demon 29/11? :)

**Comment by FannyBacklin** [comment]
@NJen9 skulle du kunna börja med att ta fram feedback-formuläret? :)

**Comment by NJen9** [comment]
Yes, har gjort ett utkast nu - "Feedback på noQ demo 29 november 2024". Kursiv text i inledningen ska ändras till vad den aktuella demon innehållit. 

Jag delade upp feedbacken i de avsnitt vi siktar på att ha, så säg till om ni hellre vill ändra tillbaka till mer likt tidigare format på formuläret. 

Lämna gärna feedback :)!
https://docs.google.com/forms/d/1Jz8jn3LaN6URAVGO_NADbF0-arO7RpOjdxQBtl94wxA/edit

**Comment by FannyBacklin** [comment]
@NJen9 vi kikade lite på formuläret under genrepet, vi tror vi behöver rikta frågorna mer mot att referensgruppen ger mer feedback på själva produkten, alltså frågor kopplat till själva applikationen istället för att de ska ge feedback på själva demon om du förstår vad jag menar. Vi kan ha en fråga i slutet om feedback på demon men att det bara är en fråga och vi lägger mer tyngd på själva applikationen så vi förstår om vi byggt rätt grejer eller tänkt helt fel

**Comment by NJen9** [comment]
Hej Fanny!Fattar, jag missförstod syftet med enkäten. Den är uppdaterad nu men blev rätt lång utefter Ludvigs förslag. Den kan nog komprimeras lite för den som ska svara genom att slå ihop alla frågor som rör samma avsnitt. Kolla och se vad du tycker funkar bäst!Med vänlig hälsningNatali Jenner 25 nov. 2024 kl. 11:34 skrev FannyBacklin ***@***.***>:﻿
@NJen9 vi kikade lite på formuläret under genrepet, vi tror vi behöver rikta frågorna mer mot att referensgruppen ger mer feedback på själva produkten, alltså frågor kopplat till själva applikationen istället för att de ska ge feedback på själva demon om du förstår vad jag menar. Vi kan ha en fråga i slutet om feedback på demon men att det bara är en fråga och vi lägger mer tyngd på själva applikationen så vi förstår om vi byggt rätt grejer eller tänkt helt fel

**Comment by LudvigErlandsson** [comment]
Jaa men låt oss komprimera den, väldigt bra input @NJen9 ! Den känns mastig nu ja!

**Comment by ChristofferEriksson-NoQ** [comment]
@FannyBacklin Yes, det är planen! Riggat upp OBS på min laptop så det ska vara redo för det

**Comment by FannyBacklin** [comment]
@NJen9 ska du och jag kanske anteckna det som sägs under själva feedbacken? :)

**Comment by NJen9** [comment]
> @NJen9 ska du och jag kanske anteckna det som sägs under själva feedbacken? :)

Yes, ser till att anteckna under feedbacken!

**Comment by FannyBacklin** [comment]
@NJen9 laddar du upp deltagarlistan sen också om du inte gjort det :)

**Comment by FannyBacklin** [comment]
@LudvigErlandsson @patrik-pwned har ni mejlat referensgruppen? Tänker om jag kan markera den här som klar :)

**Comment by LudvigErlandsson** [comment]
@FannyBacklin @patrik-pwned  Patrik skickade ut ett grymt mail i lördags så den går att markera som klar nu! :)

**Comment by FannyBacklin** [comment]
@NJen9 skriver du när du laddat upp deltagarlistan så kan vi markera denna som klar :)

**Comment by FannyBacklin** [comment]
@NJen9 ping wingmate!
