### ISSUE TITLE
Testa referensgruppens konton

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#695]
Innan demon behöver vi kolla igenom att alla våra testkonton här
https://docs.google.com/document/d/1W-tUOUpUAiQTWWzwrt0y2_Xldd_vP6LQZdf7lU_gE1Y/edit?usp=sharing

- [x] Går att logga in
- [ ] Att vi kommer till rätt landningssida för respektive användargrupp och inte annan.
- [x] Att det inte blir konflikt om två loggar in samtidigt med samma user

**Comment by FannyBacklin** [comment]
@LudvigErlandsson hur har det gått med den här?

**Comment by LudvigErlandsson** [comment]
@FannyBacklin Det gick bra i det stora hela. 

Vi har noterat utfallet från våra tester här:

https://docs.google.com/document/d/15Y2XbFGeATOjOlzjuJdoLBemVP6EdjJ-oq5w_naQiZ4/edit?usp=sharing

Så fort buggen med att startsidan för Ville Volontär ej dyker upp är åtgärdad måste vi testa volontärflödet igen innan vi lägga denna issue som in review. 

Hoppas allt funkar inför att referensgruppen ska testa, varit offline hela dagen.

**Comment by overath2** [comment]
Skapar bug för Ville Volontär

- [ ] Det går ej att logga in i demomiljön med Ville Volontär
